# =============================================================================
# 07_lib_gwctl.sh — installs /usr/local/bin/grin-gateway-ctl (single WG mutation path)
# =============================================================================
# One root-owned executable is the ONLY code that mutates the pool's WireGuard
# config (/etc/wireguard/wg-grinpool*.conf) and the region_ports map in the pool
# JSON config. Both callers go through it:
#   · the CLI  — 07_grin_mining_public_pool.sh menu W (thin pretty-printers)
#   · the panel — back-end-pool/index.js via `sudo grin-gateway-ctl …`
#     (scoped sudoers written by pool_deroot(); the de-rooted grin-pool-manager
#     may run this ONE binary as root and nothing else)
# so the wg peer list and pool.json region_ports can never drift apart, and the
# admin panel can pair a gateway without an SSH session.
# Design: docs/generated/script07_design.md §13.
#
# Subcommands (stdout is ALWAYS one JSON object; non-zero exit + {ok:false,error}
# on any failure so execFile callers get one parse path):
#   add-peer    --net N --region R --pubkey K   → assign /32 + region port, append
#               [Peer], wg syncconf, persist region_ports. Dup pubkey → no write,
#               existing:true (preserves the 2026-07-05 cryptokey-routing lesson).
#               Same region + NEW pubkey → key swapped IN PLACE (region keeps its
#               tunnel IP + port — the gateway-box-replacement flow, §13.10d).
#   remove-peer --net N --region R              → drop [Peer] + region_ports[R]
#   list        --net N                         → pairing strings re-derived live
#   status      --net N                         → per-region handshake + rx/tx
#
# The helper validates ALL inputs itself (never trusts the caller, even root)
# and computes AllowedIPs internally — 0.0.0.0/0 is unrepresentable.
#
# Convention: sourced lib → NO shebang / NO `set -e`.
# =============================================================================

[[ -n "${_GRIN_GWCTL_SH_LOADED:-}" ]] && return 0
_GRIN_GWCTL_SH_LOADED=1

GWCTL_BIN="${GWCTL_BIN:-/usr/local/bin/grin-gateway-ctl}"

if ! declare -F info    >/dev/null 2>&1; then info()    { echo "[INFO]  $*"; }; fi
if ! declare -F success >/dev/null 2>&1; then success() { echo "[OK]    $*"; }; fi

# Write (regenerate) the helper. Idempotent — call on every hub setup run, like
# the other generated units. The payload is fully self-contained (derives every
# per-network path itself) so `sudo grin-gateway-ctl` works with no toolkit env.
pool_gwctl_install() {
    cat > "$GWCTL_BIN" <<'GWCTL'
#!/bin/bash
# grin-gateway-ctl — AUTO-GENERATED by scripts/lib/07_lib_gwctl.sh. Do not edit.
# The ONLY code path that mutates the pool's WireGuard peers + region_ports.
# Always prints ONE JSON object on stdout; non-zero exit ⇒ {"ok":false,...}.
set -uo pipefail
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

jerr() { printf '{"ok":false,"error":"%s"}\n' "$1"; exit 1; }

[[ ${EUID:-$(id -u)} -eq 0 ]] || jerr "must run as root (use sudo)"
command -v node >/dev/null 2>&1 || jerr "node not found (pool hub prerequisite)"

CMD="${1:-}"; shift 2>/dev/null || true
NET="" REGION="" PUBKEY=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --net)    NET="${2:-}";    shift 2 || jerr "missing value for --net" ;;
        --region) REGION="${2:-}"; shift 2 || jerr "missing value for --region" ;;
        --pubkey) PUBKEY="${2:-}"; shift 2 || jerr "missing value for --pubkey" ;;
        *) jerr "unknown argument" ;;
    esac
done

# ── Validation (§13.2) — reject before touching anything ──────────────────────
case "$CMD" in add-peer|remove-peer|list|status) ;; *) jerr "unknown subcommand (add-peer|remove-peer|list|status)" ;; esac
[[ "$NET" == "mainnet" || "$NET" == "testnet" ]] || jerr "--net must be mainnet or testnet"
if [[ "$CMD" == "add-peer" || "$CMD" == "remove-peer" ]]; then
    [[ "$REGION" =~ ^[a-z0-9-]{2,12}$ ]] || jerr "--region must match ^[a-z0-9-]{2,12}\$"
fi
if [[ "$CMD" == "add-peer" ]]; then
    # wg public key wire format: 43 base64 chars + '='.
    [[ "$PUBKEY" =~ ^[A-Za-z0-9+/]{43}=$ ]] || jerr "--pubkey is not a WireGuard public key (44 chars, ends =)"
fi

# ── Per-network derivation — single source (mirrors 07_grin_mining_public_pool.sh) ──
if [[ "$NET" == "testnet" ]]; then
    WG_IFACE="wg-grinpool-tn"
    WG_DIR_CONF="/opt/grin/conf/wg-testnet"
    WG_TUNNEL_NET="10.66.67"
    WG_LISTEN_PORT=51821
    REGION_PORT_BASE=13391
    POOL_CONF="/opt/grin/conf/grin_pubpool_testnet.json"
else
    WG_IFACE="wg-grinpool"
    WG_DIR_CONF="/opt/grin/conf/wg"
    WG_TUNNEL_NET="10.66.66"
    WG_LISTEN_PORT=51820
    REGION_PORT_BASE=3391
    POOL_CONF="/opt/grin/conf/grin_pubpool.json"
fi
WG_CONF="/etc/wireguard/${WG_IFACE}.conf"
HUB_IP="${WG_TUNNEL_NET}.1"

# Public endpoint carried in pairing strings: wg_endpoint_host (pool.json, §13.10b —
# DNS name survives a provider/IP change) wins; else the ipify-resolved public IP.
hub_endpoint() {
    local host ip
    host=$(node -e 'try{const d=JSON.parse(require("fs").readFileSync(process.argv[1],"utf8"));process.stdout.write(String(d.wg_endpoint_host||""))}catch(e){}' "$POOL_CONF" 2>/dev/null || true)
    if [[ -n "$host" ]]; then echo "${host}:${WG_LISTEN_PORT}"; return; fi
    ip=$(curl -s --max-time 4 https://api.ipify.org 2>/dev/null || true)
    [[ "$ip" =~ ^[0-9a-fA-F.:]+$ ]] || ip="<server-public-ip>"
    echo "${ip}:${WG_LISTEN_PORT}"
}

wg_sync() { wg syncconf "$WG_IFACE" <(wg-quick strip "$WG_IFACE") 2>/dev/null; }

# ── status ────────────────────────────────────────────────────────────────────
if [[ "$CMD" == "status" ]]; then
    [[ -f "$WG_CONF" ]] || jerr "wireguard server not set up ($WG_CONF missing)"
    wg show "$WG_IFACE" dump 2>/dev/null | node -e '
const fs = require("fs");
const [conf] = process.argv.slice(1);
const txt = fs.readFileSync(conf, "utf8");
const pubToRegion = {};
let cur = null;
for (const line of txt.split("\n")) {
  const rm = line.match(/^\s*#\s*region:\s*(\S+)/);
  if (rm) { cur = rm[1]; continue; }
  const pm = line.match(/^\s*PublicKey\s*=\s*(\S+)/);
  if (pm && cur) { pubToRegion[pm[1]] = cur; cur = null; }
}
const now = Math.floor(Date.now() / 1000);
const gateways = [];
const dump = fs.readFileSync(0, "utf8").split("\n").slice(1); // line 0 = interface
for (const line of dump) {
  const f = line.trim().split("\t");
  if (f.length < 8) continue;
  const region = pubToRegion[f[0]];
  if (!region) continue;
  const hs = parseInt(f[4], 10) || 0;
  gateways.push({
    region,
    handshake: hs,
    handshake_age: hs ? now - hs : null,
    rx_bytes: parseInt(f[5], 10) || 0,
    tx_bytes: parseInt(f[6], 10) || 0
  });
}
console.log(JSON.stringify({ ok: true, gateways }));
' "$WG_CONF" || jerr "could not read wg status (tunnel down?)"
    exit 0
fi

# ── list ──────────────────────────────────────────────────────────────────────
if [[ "$CMD" == "list" ]]; then
    [[ -f "$WG_CONF" ]] || jerr "wireguard server not set up ($WG_CONF missing)"
    HUB_PUB=$(cat "$WG_DIR_CONF/server_public.key" 2>/dev/null || true)
    node -e '
const fs = require("fs");
const [wgConf, poolConf, hubPub, hubEp, hubIp] = process.argv.slice(1);
const txt = fs.readFileSync(wgConf, "utf8");
let d = {}; try { d = JSON.parse(fs.readFileSync(poolConf, "utf8")); } catch (e) {}
const ports = d.region_ports || {};
const gateways = [];
const re = /# region: (\S+)[^[]*?PublicKey\s*=\s*(\S+)[^[]*?AllowedIPs\s*=\s*(\S+)/g;
let m;
while ((m = re.exec(txt))) {
  const [, region, pubkey, ip] = m;
  const port = ports[region] || null;
  gateways.push({
    region, pubkey, peer_ip: ip, region_port: port,
    pairing: "GRINGW1|" + region + "|" + hubPub + "|" + hubEp + "|" + hubIp + "|" + ip + "|" + (port || "?")
  });
}
console.log(JSON.stringify({ ok: true, hub_pubkey: hubPub, hub_endpoint: hubEp, hub_tunnel_ip: hubIp, gateways }));
' "$WG_CONF" "$POOL_CONF" "$HUB_PUB" "$(hub_endpoint)" "$HUB_IP" || jerr "could not parse $WG_CONF"
    exit 0
fi

# ── remove-peer ───────────────────────────────────────────────────────────────
if [[ "$CMD" == "remove-peer" ]]; then
    [[ -f "$WG_CONF" ]] || jerr "wireguard server not set up ($WG_CONF missing)"
    grep -qE "^# region: ${REGION}\$" "$WG_CONF" || jerr "no gateway peer tagged region '${REGION}'"
    node -e '
const fs = require("fs");
const [conf, region] = process.argv.slice(1);
const txt = fs.readFileSync(conf, "utf8");
const kept = txt.split(/(?=^\[Peer\])/m).filter(p =>
  !(p.startsWith("[Peer]") && (p.match(/^# region: (\S+)/m) || [])[1] === region));
fs.writeFileSync(conf, kept.join("").replace(/\n{3,}/g, "\n\n").replace(/\n*$/, "\n"));
fs.chmodSync(conf, 0o600);
' "$WG_CONF" "$REGION" || jerr "failed to rewrite $WG_CONF — nothing removed"
    SYNCED=1; wg_sync || SYNCED=0
    node -e '
const fs = require("fs");
const [p, region] = process.argv.slice(1);
let d = {}; try { d = JSON.parse(fs.readFileSync(p, "utf8")); } catch (e) {}
if (d.region_ports) delete d.region_ports[region];
fs.writeFileSync(p, JSON.stringify(d, null, 2)); fs.chmodSync(p, 0o600);
' "$POOL_CONF" "$REGION" 2>/dev/null || true
    printf '{"ok":true,"removed":"%s","synced":%s}\n' "$REGION" "$([[ $SYNCED -eq 1 ]] && echo true || echo false)"
    exit 0
fi

# ── add-peer ──────────────────────────────────────────────────────────────────
[[ -f "$WG_CONF" ]] || jerr "wireguard server not set up — run pool menu W → 1 first"
HUB_PUB=$(cat "$WG_DIR_CONF/server_public.key" 2>/dev/null || true)
[[ -n "$HUB_PUB" ]] || jerr "hub wg public key missing ($WG_DIR_CONF/server_public.key)"
HUB_EP=$(hub_endpoint)

emit_pairing() {  # <existing 0|1> <replaced 0|1> <region> <peer_ip/32> <port> <synced 0|1>
    node -e '
const [existing, replaced, region, peerIp, port, synced, hubPub, hubEp, hubIp] = process.argv.slice(1);
console.log(JSON.stringify({
  ok: true, existing: existing === "1", replaced: replaced === "1",
  region, peer_ip: peerIp, region_port: parseInt(port, 10) || null,
  hub_pubkey: hubPub, hub_endpoint: hubEp, hub_tunnel_ip: hubIp,
  synced: synced === "1",
  pairing: "GRINGW1|" + region + "|" + hubPub + "|" + hubEp + "|" + hubIp + "|" + peerIp + "|" + port
}));' "$1" "$2" "$3" "$4" "$5" "$6" "$HUB_PUB" "$HUB_EP" "$HUB_IP"
}

# Dup-pubkey guard: wg keeps ONE entry per PublicKey — a second [Peer] block for
# the same key silently REPLACES the live AllowedIPs (cryptokey-routing mismatch,
# the 10.66.67.2-vs-.4 failure of 2026-07-05). Re-emit the existing pairing, write NOTHING.
if grep -qF "PublicKey = ${PUBKEY}" "$WG_CONF"; then
    EXISTING=$(node -e '
const fs = require("fs");
const [conf, poolConf, key] = process.argv.slice(1);
const txt = fs.readFileSync(conf, "utf8");
let d = {}; try { d = JSON.parse(fs.readFileSync(poolConf, "utf8")); } catch (e) {}
const ports = d.region_ports || {};
for (const p of txt.split(/(?=^\[Peer\])/m)) {
  if (!p.startsWith("[Peer]") || !p.includes("PublicKey = " + key)) continue;
  const region = (p.match(/^# region: (\S+)/m) || [])[1] || "";
  const ip = (p.match(/^AllowedIPs\s*=\s*(\S+)/m) || [])[1] || "";
  process.stdout.write(region + " " + ip + " " + (ports[region] || "?"));
  break;
}' "$WG_CONF" "$POOL_CONF" "$PUBKEY" 2>/dev/null || true)
    read -r EX_REGION EX_IP EX_PORT <<< "$EXISTING"
    [[ -n "${EX_REGION:-}" && -n "${EX_IP:-}" ]] || jerr "pubkey already a peer but its block could not be parsed"
    emit_pairing 1 0 "$EX_REGION" "$EX_IP" "${EX_PORT:-?}" 1
    exit 0
fi

# Region replace flow (§13.10d): the region is already wired but with a DIFFERENT
# key = the gateway box was rebuilt. Swap the key IN PLACE so the region keeps its
# tunnel IP + port — nothing else (gateway pastes its new GRINGW1, done).
if grep -qE "^# region: ${REGION}\$" "$WG_CONF"; then
    SWAP=$(node -e '
const fs = require("fs");
const [conf, poolConf, region, newKey] = process.argv.slice(1);
const txt = fs.readFileSync(conf, "utf8");
let d = {}; try { d = JSON.parse(fs.readFileSync(poolConf, "utf8")); } catch (e) {}
const ports = d.region_ports || {};
const parts = txt.split(/(?=^\[Peer\])/m);
let ip = "";
for (let i = 0; i < parts.length; i++) {
  const p = parts[i];
  if (!p.startsWith("[Peer]") || (p.match(/^# region: (\S+)/m) || [])[1] !== region) continue;
  ip = (p.match(/^AllowedIPs\s*=\s*(\S+)/m) || [])[1] || "";
  parts[i] = p.replace(/^PublicKey\s*=.*$/m, "PublicKey = " + newKey);
}
if (!ip) process.exit(1);
fs.writeFileSync(conf, parts.join(""));
fs.chmodSync(conf, 0o600);
process.stdout.write(ip + " " + (ports[region] || "?"));
' "$WG_CONF" "$POOL_CONF" "$REGION" "$PUBKEY" 2>/dev/null || true)
    read -r SW_IP SW_PORT <<< "$SWAP"
    [[ -n "${SW_IP:-}" ]] || jerr "region '${REGION}' exists but its peer block could not be rewritten"
    SYNCED=1; wg_sync || SYNCED=0
    emit_pairing 0 1 "$REGION" "$SW_IP" "${SW_PORT:-?}" "$SYNCED"
    exit 0
fi

# Fresh peer: next free /32 (max existing last-octet + 1; .1 = hub) and region port
# (an already-mapped region KEEPS its port; else max existing + 1, else the base).
ASSIGN=$(node -e '
const fs = require("fs");
const [wgConf, poolConf, net, base, region] = process.argv.slice(1);
let octs = [1];
try {
  const t = fs.readFileSync(wgConf, "utf8");
  const re = new RegExp("AllowedIPs\\s*=\\s*" + net.replace(/\./g, "\\.") + "\\.(\\d+)", "g");
  let m; while ((m = re.exec(t))) octs.push(parseInt(m[1], 10));
} catch (e) {}
let ports = [], keep = 0;
try {
  const d = JSON.parse(fs.readFileSync(poolConf, "utf8"));
  if (d.region_ports) {
    ports = Object.values(d.region_ports).map(Number).filter(Boolean);
    keep  = parseInt(d.region_ports[region], 10) || 0;
  }
} catch (e) {}
const nextIp = Math.max.apply(null, octs) + 1;
if (nextIp > 254) process.exit(1);
const nextPort = keep || (ports.length ? Math.max.apply(null, ports) + 1 : parseInt(base, 10));
process.stdout.write(nextIp + " " + nextPort);
' "$WG_CONF" "$POOL_CONF" "$WG_TUNNEL_NET" "$REGION_PORT_BASE" "$REGION" 2>/dev/null || true)
read -r NEXT_OCT NEXT_PORT <<< "$ASSIGN"
[[ -n "${NEXT_OCT:-}" && -n "${NEXT_PORT:-}" ]] || jerr "could not compute a free tunnel IP / region port"
PEER_IP="${WG_TUNNEL_NET}.${NEXT_OCT}"

cat >> "$WG_CONF" <<PEER

[Peer]
# region: ${REGION}
PublicKey = ${PUBKEY}
AllowedIPs = ${PEER_IP}/32
PEER
SYNCED=1; wg_sync || SYNCED=0

# Persist the region → internal port map + tunnel-only listen host in pool.json.
node -e '
const fs = require("fs");
const [p, region, port, host] = process.argv.slice(1);
let d = {}; try { d = JSON.parse(fs.readFileSync(p, "utf8")); } catch (e) {}
d.region_ports = d.region_ports || {};
d.region_ports[region] = parseInt(port, 10);
d.region_listen_host = host;
fs.writeFileSync(p, JSON.stringify(d, null, 2)); fs.chmodSync(p, 0o600);
' "$POOL_CONF" "$REGION" "$NEXT_PORT" "$HUB_IP" || jerr "peer added but pool config write failed ($POOL_CONF)"

emit_pairing 0 0 "$REGION" "${PEER_IP}/32" "$NEXT_PORT" "$SYNCED"
GWCTL
    chown root:root "$GWCTL_BIN" 2>/dev/null || true
    chmod 755 "$GWCTL_BIN"
    success "Installed $GWCTL_BIN (single WireGuard mutation path — CLI + admin panel)."
}
