# =============================================================================
# 07_lib_pool_backup.sh — Encrypted backup / restore / schedule for the PUBLIC POOL hub
# =============================================================================
# Design §13.10c: the hub was the only money-holding product without a backup.
# Same shared engine as solo/drop (lib/grin_backup_engine.sh gbe_* + offsite
# gbp_* push): /opt/grin/backups/grin_<product>_backup_<DDMMYYYY>.tar.gz.enc,
# password = <personal_key><DDMMYYYY>, AES-256-CBC/PBKDF2-600k, fd:3.
# Product name: `pubpool` (mainnet) / `pubpooltestnet` — one archive per net per day.
#
# Backup set — everything a fresh 07 install can NOT regenerate:
#   · pool.db            balances / shares / audit — snapshotted via the SQLite
#                        online-backup API (two-phase tar; never a live WAL copy)
#   · $POOL_CONF         pool.json incl. region_ports + jwt_secret
#   · wallet dir         seed + grin-wallet.toml + api secrets + tor send dirs
#                        (grin-wallet BINARY excluded — redeployable)
#   · app dir extras     .wallet_pass, custom_assets, uploads (code + node_modules
#                        excluded — 1) Install / 9) Deploy regenerate them)
#   · WG identity        $WG_DIR_CONF/server_*.key + /etc/wireguard/wg-grinpool*.conf
#                        → restoring these means gateways reconnect on their
#                        PersistentKeepalive with ZERO re-pairing
#   · nginx vhost        $POOL_NGINX_CONF (cert itself is NOT included — certbot
#                        re-issues once DNS points at the new box)
#
# Restore runbook (printed at the end of pbk_restore): fresh box → Script 01 node
# → 07 hub 1) Install → restore → grin-secret-sync → re-point DNS → gateways
# reconnect with no action on any gateway box.
#
# Sourced by 07_grin_mining_public_pool.sh AFTER the POOL_* constants are set;
# WG_*/pw_* are referenced at CALL time (they are defined later in the parent).
# Convention: sourced lib → NO shebang / NO `set -e`.
# =============================================================================

[[ -n "${_GRIN_POOL_BACKUP_SH_LOADED:-}" ]] && return 0
_GRIN_POOL_BACKUP_SH_LOADED=1

# shellcheck disable=SC1091
source "$(dirname "${BASH_SOURCE[0]}")/grin_backup_engine.sh"

# ─── Constants (POOL_NET/POOL_SERVICE are set by the parent before sourcing) ──
PBK_BACKUP_DIR="${PBK_BACKUP_DIR:-/opt/grin/backups}"
if [[ "${POOL_NET:-mainnet}" == "testnet" ]]; then
    PBK_PRODUCT="pubpooltestnet"
    PBK_CONF="${PBK_CONF:-/opt/grin/conf/grin_pubpool_backup_testnet.conf}"
else
    PBK_PRODUCT="pubpool"
    PBK_CONF="${PBK_CONF:-/opt/grin/conf/grin_pubpool_backup.conf}"
fi
PBK_PREFIX="grin_${PBK_PRODUCT}_backup_"
# Wrapper/cron paths deliberately REUSE the legacy plain-backup names, so the
# existing cleanup + cron-menu code keeps matching them.
PBK_WRAPPER="${PBK_WRAPPER:-/usr/local/bin/grin-pool-backup-${POOL_NET:-mainnet}}"
PBK_CRON="${PBK_CRON:-/etc/cron.d/${POOL_SERVICE:-grin-pool-manager}-backup}"
PBK_KEEP_DEFAULT=14
PBK_LOG="${PBK_LOG:-/opt/grin/logs/pubpool-backup-${POOL_NET:-mainnet}.log}"

if ! declare -F info    >/dev/null 2>&1; then info()    { echo "[INFO]  $*"; }; fi
if ! declare -F warn    >/dev/null 2>&1; then warn()    { echo "[WARN]  $*"; }; fi
if ! declare -F error   >/dev/null 2>&1; then error()   { echo "[ERROR] $*" >&2; }; fi
if ! declare -F success >/dev/null 2>&1; then success() { echo "[OK]    $*"; }; fi
if ! declare -F _pool_pause >/dev/null 2>&1; then _pool_pause() { echo ""; echo "Press Enter to continue..."; read -r || true; }; fi

PBK_KEEP="$PBK_KEEP_DEFAULT"
PBK_HOUR=2
PBK_MIN=0

pbk_load_conf() {
    PBK_KEEP="$PBK_KEEP_DEFAULT"; PBK_HOUR=2; PBK_MIN=0
    # shellcheck disable=SC1090
    [[ -f "$PBK_CONF" ]] && source "$PBK_CONF" 2>/dev/null
    [[ "$PBK_KEEP" =~ ^[0-9]+$ ]] || PBK_KEEP="$PBK_KEEP_DEFAULT"
    [[ "$PBK_HOUR" =~ ^[0-9]+$ ]] || PBK_HOUR=2
    [[ "$PBK_MIN"  =~ ^[0-9]+$ ]] || PBK_MIN=0
    gbe_load_key
}

pbk_save_conf() {
    mkdir -p "$(dirname "$PBK_CONF")"
    ( umask 077; cat > "$PBK_CONF" <<EOF
# Public pool hub backup config — generated by 07_grin_mining_public_pool.sh
# Schedule/retention only. The personal key lives in the SHARED conf
# (grin_backup.conf — one key for ALL product backups).
PBK_KEEP=$PBK_KEEP
PBK_HOUR=$PBK_HOUR
PBK_MIN=$PBK_MIN
EOF
    )
    chmod 600 "$PBK_CONF"
}

# ─── Sources (resolved at call time — wallet dir/WG paths live in the parent) ─
# Echoes absolute existing paths, one per line. The wallet dir + app dir get
# their excludes in _pbk_make_tar; everything here is tarred relative to /.
_pbk_sources() {
    local s wdir
    wdir=$(pw_wallet_dir 2>/dev/null || echo "${POOL_WALLET_DIR:-}")
    for s in "$POOL_APP_DIR" "$POOL_CONF" "$wdir" \
             "${WG_DIR_CONF:-}" "${WG_CONF:-}" "${POOL_NGINX_CONF:-}"; do
        [[ -n "$s" && -e "$s" ]] && echo "$s"
    done | sort -u
}

# ─── Two-phase tar (live pass excludes *.db*; pool.db appended from a snapshot) ─
# $1 = output .tar.gz. Same pattern as 059: a global *.db exclude on the live
# pass cannot strip the staged snapshot because it is appended in a second call.
_pbk_make_tar() {
    local outgz="$1"
    local work; work=$(mktemp /tmp/grin_pubpool_bakwork_XXXXXX.tar 2>/dev/null) || return 1

    local db="$POOL_APP_DIR/pool.db" stage="" dbrel=""
    if [[ -f "$db" ]]; then
        stage=$(mktemp -d /tmp/grin_pubpool_dbsnap_XXXXXX 2>/dev/null) || stage=""
        if [[ -n "$stage" ]]; then
            dbrel="${db#/}"
            mkdir -p "$stage/$(dirname "$dbrel")"
            gbe_snapshot_db "$db" "$stage/$dbrel"
        fi
    fi

    local -a live_rels=(); local s
    while IFS= read -r s; do live_rels+=("${s#/}"); done < <(_pbk_sources)

    local wdir; wdir=$(pw_wallet_dir 2>/dev/null || echo "${POOL_WALLET_DIR:-/nonexistent}")
    local -a ex=(
        --exclude="${wdir#/}/grin-wallet"
        --exclude="*/node_modules"
        --exclude="${POOL_APP_DIR#/}/lib"
        --exclude="${POOL_APP_DIR#/}/admin-panel"
        --exclude="${POOL_APP_DIR#/}/scripts"
        --exclude="*.log"
        --exclude="*.db"
        --exclude="*.db-wal"
        --exclude="*.db-shm"
        --exclude="*.db-journal"
    )

    local rc=0
    if [[ "${#live_rels[@]}" -gt 0 ]]; then
        tar -cf "$work" "${ex[@]}" -C / "${live_rels[@]}" 2>/dev/null
        rc=$?
    else
        rc=1
    fi
    if [[ -n "$stage" && -n "$dbrel" && -f "$work" ]]; then
        tar -rf "$work" -C "$stage" "$dbrel" 2>/dev/null || rc=$?
    fi
    [[ -n "$stage" ]] && rm -rf "$stage"

    if [[ ! -f "$work" ]]; then rm -f "$work"; return 1; fi
    if ! gzip -c "$work" > "$outgz" 2>/dev/null; then rm -f "$work"; return 1; fi
    rm -f "$work"
    return $rc
}

pbk_prune() { gbe_prune_count "$PBK_PRODUCT" "${1:-$PBK_KEEP}" "$PBK_BACKUP_DIR"; }

# ─── Backup now (interactive) ────────────────────────────────────────────────
pbk_backup_now() {
    echo -e "\n${BOLD}Pool hub backup — ${POOL_NET_LABEL:-$POOL_NET}${RESET}"
    command -v openssl >/dev/null 2>&1 || { error "openssl not found — cannot encrypt."; return 1; }
    pbk_load_conf

    local -a srcs=(); local s
    while IFS= read -r s; do srcs+=("$s"); done < <(_pbk_sources)
    if [[ "${#srcs[@]}" -eq 0 ]]; then
        warn "Nothing to back up yet — run 1) Install (and 5) Set up wallet) first."
        return 1
    fi
    echo -e "  ${DIM}Will archive (pool.db snapshot + config + wallet seed/secrets + WG identity;${RESET}"
    echo -e "  ${DIM}redeployable code/node_modules/binary excluded):${RESET}"
    for s in "${srcs[@]}"; do echo -e "    ${DIM}$s${RESET}"; done
    echo ""

    gbe_require_key || { info "Backup needs a personal key."; return 1; }

    local tmp_gz
    tmp_gz=$(mktemp "/tmp/grin_pubpool_bak_XXXXXX.tar.gz") || { error "mktemp failed."; return 1; }
    info "Creating archive..."
    if ! _pbk_make_tar "$tmp_gz"; then
        warn "tar reported issues (a file changed mid-read, or a missing optional path — usually harmless)."
    fi
    gbe_finalize_archive "$PBK_PRODUCT" "$tmp_gz" "$PBK_BACKUP_DIR" || return 1

    echo -e "  ${YELLOW}This archive contains the wallet seed AND the hub WireGuard private key —${RESET}"
    echo -e "  ${YELLOW}anyone with the file + your key can spend and impersonate the hub.${RESET}"
    mkdir -p "$(dirname "$PBK_LOG")"
    echo "[$(date -u '+%Y-%m-%d %H:%M:%S UTC')] backup created: $(basename "$GBE_ARCHIVE")" >> "$PBK_LOG" 2>/dev/null || true
    pbk_prune "$PBK_KEEP"
}

# ─── Restore (interactive) ───────────────────────────────────────────────────
pbk_restore() {
    echo -e "\n${BOLD}Pool hub restore — ${POOL_NET_LABEL:-$POOL_NET}${RESET}"
    command -v openssl >/dev/null 2>&1 || { error "openssl not found — cannot decrypt."; return 1; }
    mkdir -p "$PBK_BACKUP_DIR" 2>/dev/null || true

    echo -e "  ${DIM}Disaster-recovery order on a FRESH box (design §13.10c): Script 01 node →${RESET}"
    echo -e "  ${DIM}07 hub 1) Install → THIS restore → grin-secret-sync → re-point DNS →${RESET}"
    echo -e "  ${DIM}gateways reconnect on their keepalive with zero re-pairing.${RESET}"
    echo ""

    local -a baks=(); local f
    while IFS= read -r f; do [[ -n "$f" ]] && baks+=("$f"); done \
        < <(ls -t "$PBK_BACKUP_DIR/${PBK_PREFIX}"*.tar.gz.enc 2>/dev/null || true)
    if [[ "${#baks[@]}" -eq 0 ]]; then
        warn "No ${PBK_PREFIX}* backups in $PBK_BACKUP_DIR — copy one there first (scp/rsync)."
        return 1
    fi
    echo -e "  ${BOLD}Available backups (newest first):${RESET}"
    local i=1 sz
    for f in "${baks[@]}"; do
        sz=$(du -sh "$f" 2>/dev/null | cut -f1 || echo "?")
        echo -e "  ${GREEN}$i${RESET}) $(basename "$f")  ${DIM}($sz)${RESET}"
        (( i++ ))
    done
    echo -e "  ${DIM}0) Cancel${RESET}"
    echo -ne "${BOLD}Select backup [1-${#baks[@]}/0]: ${RESET}"
    local sel; read -r sel || true
    [[ "$sel" =~ ^[0-9]+$ && "$sel" -ge 1 && "$sel" -le "${#baks[@]}" ]] || { info "Cancelled."; return 1; }
    local chosen="${baks[$((sel-1))]}"

    local d; d=$(gbe_parse_date "$chosen") || { error "Cannot read date from filename."; return 1; }
    local key pass tmp_clear
    read -rs -p "  Personal key for this backup: " key; echo ""
    [[ -z "$key" ]] && { warn "No key entered."; return 1; }
    pass="${key}${d}"; unset key
    tmp_clear=$(mktemp "/tmp/grin_pubpool_restore_XXXXXX.tar.gz") || { unset pass; return 1; }
    if ! gbe_decrypt "$chosen" "$tmp_clear" "$pass"; then
        rm -f "$tmp_clear"; unset pass
        error "Wrong key or corrupt backup."; return 1
    fi
    unset pass
    tar -tzf "$tmp_clear" >/dev/null 2>&1 || { rm -f "$tmp_clear"; error "Decrypted file is not a valid archive."; return 1; }
    success "Decrypted and validated."

    echo ""
    echo -e "  ${RED}${BOLD}This OVERWRITES current files at their original paths:${RESET}"
    tar -tzf "$tmp_clear" 2>/dev/null | awk -F/ 'NF>=3{print "/"$1"/"$2"/"$3}' | sort -u | sed 's|^|    |'
    echo ""
    echo -ne "  Type ${BOLD}RESTORE${RESET} to confirm (pool service + wallet listener will be stopped): "
    local go; read -r go || true
    [[ "$go" == "RESTORE" ]] || { rm -f "$tmp_clear"; info "Restore cancelled."; return 1; }

    systemctl stop "$POOL_SERVICE" 2>/dev/null || true
    if declare -F pw_listener_stop >/dev/null 2>&1; then pw_listener_stop 2>/dev/null || true; fi

    if ! tar -xzf "$tmp_clear" -C / --preserve-permissions 2>/dev/null; then
        rm -f "$tmp_clear"; error "Extraction failed."; return 1
    fi
    rm -f "$tmp_clear"

    # Perms: tar extracts as root — re-assert the de-rooted ownership (§13.9) and
    # the secret modes. pool_deroot is the canonical sweep when available.
    if declare -F pool_deroot >/dev/null 2>&1; then
        pool_deroot || true
    fi
    chmod 600 "$POOL_CONF" 2>/dev/null || true
    chmod 600 /etc/wireguard/wg-grinpool*.conf 2>/dev/null || true

    success "Restore complete — pool.db, config, wallet, WG identity are back in place."
    echo ""
    echo -e "  ${BOLD}To finish (order matters):${RESET}"
    echo -e "    1) ${BOLD}grin-secret-sync${RESET} — re-points the wallet at THIS box's node secrets."
    echo -e "    2) ${BOLD}wg-quick down/up ${WG_IFACE:-wg-grinpool}${RESET} (or W → 1) — brings the restored tunnel up;"
    echo -e "       gateways reconnect on their PersistentKeepalive, no re-pairing."
    echo -e "       ${DIM}New box IP? Update the hub's DNS A record (W → 5 wg_endpoint_host), or each${RESET}"
    echo -e "       ${DIM}gateway edits wg_hub_endpoint once. Gateway boxes themselves need nothing else.${RESET}"
    echo -e "    3) ${BOLD}5) Set up wallet → 2) Start listener${RESET} — restored .wallet_pass unlocks it."
    echo -e "    4) ${BOLD}4) Setup nginx${RESET} if this is a fresh box (cert is NOT in the backup)."
    echo -e "    5) ${BOLD}6) Service control → Start${RESET}, then check admin → health."
    mkdir -p "$(dirname "$PBK_LOG")"
    echo "[$(date -u '+%Y-%m-%d %H:%M:%S UTC')] restore from: $(basename "$chosen")" >> "$PBK_LOG" 2>/dev/null || true
}

# ─── Daily schedule (self-contained cron wrapper, same flags as pbk_backup_now) ─
_pbk_write_wrapper() {
    local wdir; wdir=$(pw_wallet_dir 2>/dev/null || echo "${POOL_WALLET_DIR:-}")
    cat > "$PBK_WRAPPER" <<WRAP
#!/bin/bash
# Grin public pool hub daily backup — generated by 07_grin_mining_public_pool.sh. Do not edit.
set -uo pipefail
export PATH=/usr/local/bin:/usr/bin:/bin
CONF="$PBK_CONF"
KEYCONF="$GBE_CONF"
BACKUP_DIR="$PBK_BACKUP_DIR"
PREFIX="$PBK_PREFIX"
LOG="$PBK_LOG"
APP_DIR="$POOL_APP_DIR"
POOL_CONF="$POOL_CONF"
WALLET_DIR="$wdir"
WG_DIR="${WG_DIR_CONF:-}"
WG_FILE="${WG_CONF:-}"
NGINX_VHOST="${POOL_NGINX_CONF:-}"

TS=\$(date -u '+%Y-%m-%d %H:%M:%S UTC')
PBK_KEEP=$PBK_KEEP_DEFAULT
# shellcheck disable=SC1090
[[ -f "\$CONF" ]] && source "\$CONF"
GBE_PERSONAL_KEY_B64=""
# shellcheck disable=SC1090
[[ -f "\$KEYCONF" ]] && source "\$KEYCONF"
KEY=\$(printf '%s' "\$GBE_PERSONAL_KEY_B64" | base64 -d 2>/dev/null || true)
[[ -n "\$KEY" ]] || { echo "[\$TS] ERROR: no personal key set" >> "\$LOG"; exit 1; }
[[ "\$PBK_KEEP" =~ ^[0-9]+\$ ]] || PBK_KEEP=$PBK_KEEP_DEFAULT

D=\$(date +%d%m%Y)
PASS="\${KEY}\${D}"
ARCHIVE="\$BACKUP_DIR/\${PREFIX}\${D}.tar.gz.enc"
mkdir -p "\$BACKUP_DIR"; chmod 700 "\$BACKUP_DIR" 2>/dev/null || true

LIVE=(); for s in "\$APP_DIR" "\$POOL_CONF" "\$WALLET_DIR" "\$WG_DIR" "\$WG_FILE" "\$NGINX_VHOST"; do
    [[ -n "\$s" && -e "\$s" ]] && LIVE+=( "\${s#/}" )
done
[[ "\${#LIVE[@]}" -gt 0 ]] || { echo "[\$TS] ERROR: nothing to back up" >> "\$LOG"; exit 1; }

WORK=\$(mktemp /tmp/grin_pubpool_cronwork_XXXXXX.tar) || exit 1
STAGE=""; DBREL=""
DB="\$APP_DIR/pool.db"
if [[ -f "\$DB" ]]; then
    STAGE=\$(mktemp -d /tmp/grin_pubpool_cronsnap_XXXXXX 2>/dev/null) || STAGE=""
    if [[ -n "\$STAGE" ]]; then
        DBREL="\${DB#/}"
        mkdir -p "\$STAGE/\$(dirname "\$DBREL")"
        python3 -c 'import sqlite3,sys; s=sqlite3.connect(sys.argv[1]); d=sqlite3.connect(sys.argv[2]); s.backup(d); d.close(); s.close()' \
            "\$DB" "\$STAGE/\$DBREL" 2>/dev/null || cp -p "\$DB" "\$STAGE/\$DBREL"
    fi
fi
EX=( --exclude="\${WALLET_DIR#/}/grin-wallet" --exclude="*/node_modules" \
     --exclude="\${APP_DIR#/}/lib" --exclude="\${APP_DIR#/}/admin-panel" --exclude="\${APP_DIR#/}/scripts" \
     --exclude="*.log" --exclude="*.db" --exclude="*.db-wal" --exclude="*.db-shm" --exclude="*.db-journal" )
tar -cf "\$WORK" "\${EX[@]}" -C / "\${LIVE[@]}" 2>/dev/null || true
if [[ -n "\$STAGE" && -n "\$DBREL" && -f "\$WORK" ]]; then
    tar -rf "\$WORK" -C "\$STAGE" "\$DBREL" 2>/dev/null || true
fi
[[ -n "\$STAGE" ]] && rm -rf "\$STAGE"
TMP=\$(mktemp /tmp/grin_pubpool_cronbak_XXXXXX.tar.gz) || { rm -f "\$WORK"; exit 1; }
gzip -c "\$WORK" > "\$TMP" 2>/dev/null || { rm -f "\$WORK" "\$TMP"; echo "[\$TS] ERROR: gzip failed" >> "\$LOG"; exit 1; }
rm -f "\$WORK"
[[ -s "\$TMP" ]] || { rm -f "\$TMP"; echo "[\$TS] ERROR: empty archive (disk full?)" >> "\$LOG"; exit 1; }
if openssl enc -aes-256-cbc -pbkdf2 -iter 600000 -salt -pass fd:3 \
        -in "\$TMP" -out "\$ARCHIVE" 3<<<"\$PASS" 2>/dev/null; then
    chmod 600 "\$ARCHIVE"; chown root:root "\$ARCHIVE" 2>/dev/null || true
    SZ=\$(du -sh "\$ARCHIVE" 2>/dev/null | cut -f1 || echo "?")
    echo "[\$TS] backup created: \$(basename "\$ARCHIVE") (\$SZ)" >> "\$LOG"
else
    rm -f "\$TMP" "\$ARCHIVE"; echo "[\$TS] ERROR: openssl failed" >> "\$LOG"; exit 1
fi
rm -f "\$TMP"; unset PASS KEY

# Offsite push (scp) — silent no-op unless configured via the toolkit menus
if [[ -x "${GBP_BIN:-/usr/local/bin/grin-backup-push}" ]]; then
    "${GBP_BIN:-/usr/local/bin/grin-backup-push}" "\$ARCHIVE" \
        || echo "[\$TS] WARN: offsite push failed — see ${GBP_LOG:-/opt/grin/logs/backup-push.log}" >> "\$LOG"
fi

N=\$(ls -1 "\$BACKUP_DIR/\${PREFIX}"*.tar.gz.enc 2>/dev/null | wc -l)
if [[ "\$N" -gt "\$PBK_KEEP" ]]; then
    ls -t "\$BACKUP_DIR/\${PREFIX}"*.tar.gz.enc 2>/dev/null \
        | tail -n +\$((PBK_KEEP + 1)) | xargs rm -f 2>/dev/null || true
    echo "[\$TS] pruned (kept newest \$PBK_KEEP)" >> "\$LOG"
fi
WRAP
    chmod 750 "$PBK_WRAPPER"
}

# Toggle: enabled → offer disable; disabled → require key, write wrapper + cron.
pbk_schedule() {
    pbk_load_conf
    echo -e "\n${BOLD}Daily hub backup schedule — ${POOL_NET_LABEL:-$POOL_NET}${RESET}"
    if [[ -f "$PBK_CRON" ]]; then
        echo -e "  Status: ${GREEN}enabled${RESET}  ${DIM}(daily $(printf '%02d:%02d' "$PBK_HOUR" "$PBK_MIN") UTC, keep $PBK_KEEP · log: $PBK_LOG)${RESET}"
        echo -ne "  Disable it? [y/N]: "
        local c; read -r c || true
        if [[ "${c,,}" == "y" ]]; then
            rm -f "$PBK_CRON" "$PBK_WRAPPER"
            success "Daily backup disabled."
        fi
        return 0
    fi
    echo -e "  ${DIM}Runs once a day (encrypted archive + offsite push if configured), keeps${RESET}"
    echo -e "  ${DIM}the newest $PBK_KEEP archives. Uses the saved personal key — no prompt at run time.${RESET}"
    gbe_require_key || { info "Scheduling needs a personal key."; return 1; }
    pbk_save_conf
    _pbk_write_wrapper
    cat > "$PBK_CRON" <<EOF
# Grin public pool hub daily backup — generated by 07_grin_mining_public_pool.sh
$PBK_MIN $PBK_HOUR * * * root $PBK_WRAPPER
EOF
    success "Daily backup enabled → $PBK_CRON  (daily $(printf '%02d:%02d' "$PBK_HOUR" "$PBK_MIN") UTC)"
}

pbk_list_backups() {
    echo ""
    echo -e "  ${BOLD}Backups in $PBK_BACKUP_DIR:${RESET}"
    local any=0 f sz
    while IFS= read -r f; do
        [[ -n "$f" ]] || continue
        any=1; sz=$(du -sh "$f" 2>/dev/null | cut -f1 || echo "?")
        echo -e "    $(basename "$f")  ${DIM}($sz)${RESET}"
    done < <(ls -t "$PBK_BACKUP_DIR/${PBK_PREFIX}"*.tar.gz.enc 2>/dev/null || true)
    # if-form: a trailing `[[ ]] && echo` would make this return 1 whenever
    # backups exist — the bare caller under set -e would die (CLAUDE.md trap).
    if [[ "$any" -eq 0 ]]; then echo -e "    ${DIM}(none yet)${RESET}"; fi
}

pbk_settings() {
    local c
    while true; do
        clear
        pbk_load_conf
        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo -e "${BOLD}${CYAN}  Pool hub — Backup settings (${POOL_NET_LABEL:-$POOL_NET})${RESET}"
        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo ""
        local key_state="${RED}not set${RESET}"; [[ -n "$GBE_PERSONAL_KEY" ]] && key_state="${GREEN}set${RESET}"
        echo -e "  Personal key : $key_state   ${DIM}($GBE_CONF · shared by all products)${RESET}"
        echo -e "  Retention    : ${BOLD}$PBK_KEEP${RESET} archives"
        echo -e "  Schedule time: $(printf '%02d:%02d' "$PBK_HOUR" "$PBK_MIN") UTC"
        pbk_list_backups
        echo ""
        echo -e "  ${GREEN}1${RESET}) Set / change personal key"
        echo -e "  ${GREEN}2${RESET}) Set retention (number of archives to keep)"
        echo -e "  ${RED}0${RESET}) Back"
        echo ""
        echo -ne "${BOLD}Select [1-2/0]: ${RESET}"
        read -r c || c=0
        case "$c" in
            "") continue ;;
            1) gbe_set_key || true; _pool_pause ;;
            2) echo -ne "  Keep how many archives [current $PBK_KEEP]: "
               local n; read -r n || true
               if [[ "$n" =~ ^[0-9]+$ && "$n" -ge 1 ]]; then
                   PBK_KEEP="$n"; pbk_save_conf; success "Retention set to $n."
                   [[ -f "$PBK_CRON" ]] && _pbk_write_wrapper
               else
                   warn "Unchanged (enter a positive number)."
               fi
               _pool_pause ;;
            0) return 0 ;;
            *) warn "Invalid option."; sleep 1 ;;
        esac
    done
}

# ─── Backup & Restore menu (pool main menu option B) ─────────────────────────
pool_backup_menu() {
    local choice
    while true; do
        clear
        pbk_load_conf
        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo -e "${BOLD}${CYAN}  Pool hub — Backup & Restore (${POOL_NET_LABEL:-$POOL_NET})${RESET}"
        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo ""
        local sched="${RED}off${RESET}"; [[ -f "$PBK_CRON" ]] && sched="${GREEN}daily $(printf '%02d:%02d' "$PBK_HOUR" "$PBK_MIN") UTC${RESET}"
        local key_state="${RED}not set${RESET}"; [[ -n "$GBE_PERSONAL_KEY" ]] && key_state="${GREEN}set${RESET}"
        local push_state="${DIM}off${RESET}"; gbp_configured && push_state="${GREEN}on${RESET}"
        echo -e "  ${DIM}Dir: $PBK_BACKUP_DIR · key: ${RESET}$key_state${DIM} · schedule: ${RESET}$sched${DIM} · offsite: ${RESET}$push_state"
        echo -e "  ${DIM}Covers: pool.db (balances) · pool.json · wallet seed · WG identity (gateways${RESET}"
        echo -e "  ${DIM}reconnect after restore with zero re-pairing) · nginx vhost.${RESET}"
        echo ""
        echo -e "  ${GREEN}1${RESET}) Backup now            ${DIM}(encrypted archive)${RESET}"
        echo -e "  ${GREEN}2${RESET}) Restore from backup   ${DIM}(one-shot extract to original paths + runbook)${RESET}"
        echo -e "  ${GREEN}3${RESET}) Schedule daily backup ${DIM}(cron · ${PBK_KEEP}-archive retention)${RESET}"
        echo -e "  ${GREEN}4${RESET}) Settings              ${DIM}(personal key · retention · list)${RESET}"
        echo -e "  ${GREEN}5${RESET}) Offsite push (scp)    ${DIM}(auto-copy each archive to a remote server)${RESET}"
        echo ""
        echo -e "  ${RED}0${RESET}) Back"
        echo ""
        echo -ne "${BOLD}Select [1-5/0]: ${RESET}"
        read -r choice || choice=0
        case "$choice" in
            "") continue ;;
            1) pbk_backup_now || true; _pool_pause ;;
            2) pbk_restore    || true; _pool_pause ;;
            3) pbk_schedule   || true; _pool_pause ;;
            4) pbk_settings   || true ;;
            5) gbp_setup      || true ;;
            0) return 0 ;;
            *) warn "Invalid option."; sleep 1 ;;
        esac
    done
}
