# =============================================================================
# lib/07_solo_backup.sh — Encrypted backup / restore / schedule for solo mining
# =============================================================================
# One-shot encrypted archive of everything a solo miner can't recreate:
#   /opt/grin/solowallet/        ALL wallets (binary INCLUDED → run immediately
#                                after restore, no re-download) + seed + saved
#                                passphrase + api secrets + grin-wallet.toml
#   /opt/grin/solo-stats/        rolling stats history (found blocks, hashrate)
#   /opt/grin/conf/grin_solo_payment.json   payout-split prefixes
#
# NOT backed up: the node dir / grin-server.toml (you re-publish stratum after
# restore) and the backup key file itself (must never travel inside an archive).
#
# Archive: /opt/grin/backups/grin_solo_backup_<DDMMYYYY>.tar.gz.enc  (mode 600)
#   · dir + crypto mirror 052 Grin Drop for repo consistency
#   · AES-256-CBC, PBKDF2 600k iters; password NEVER on the process list (fd:3)
#
# Password model (operator's design):
#   <personal_key><DDMMYYYY>     e.g.  123abc03062026
#   · personal_key — secret you choose; stored b64 in grin_solo_backup.conf
#     (mode 600) so the daily cron can run unattended. Typed by HAND on restore.
#   · DDMMYYYY     — parsed from the filename → per-file salt, not a secret.
#   Lose the personal key AND the box → archives are unrecoverable (the date
#   alone won't open them). The setup flow says so loudly.
#
# Restore: pick a file → type the personal key ONCE → decrypt + validate →
# single extract to the EXACT original paths (tar -C / -p). Then start the node,
# publish stratum, redeploy the web page and you're mining.
#
# Convention: sourced lib → NO shebang / NO `set -e`.
# =============================================================================

[[ -n "${_GRIN_SOLO_BACKUP_SH_LOADED:-}" ]] && return 0
_GRIN_SOLO_BACKUP_SH_LOADED=1

# ─── Paths / constants (env-overridable for testing) ────────────────────────
SB_BACKUP_DIR="${SB_BACKUP_DIR:-/opt/grin/backups}"          # matches 052 Grin Drop
SB_CONF="${SB_CONF:-/opt/grin/conf/grin_solo_backup.conf}"   # key + schedule (mode 600)
SB_WRAPPER="${SB_WRAPPER:-/usr/local/bin/grin-solo-backup}"
SB_CRON="${SB_CRON:-/etc/cron.d/grin-solo-backup}"
SB_PREFIX="grin_solo_backup_"
SB_KEEP_DEFAULT=30
SB_LOG="${SB_LOG:-/opt/grin/logs/solo-backup.log}"

# Source set — absolute paths so a restore lands them back exactly. Reference the
# wallet/main constants when present, else the standard defaults.
_sb_sources() {
    local s
    for s in \
        "${SW_BASE:-/opt/grin/solowallet}" \
        "${SW_STATE_DIR:-/opt/grin/solo-stats}" \
        "${PAYMENT_CONFIG:-/opt/grin/conf/grin_solo_payment.json}"; do
        [[ -e "$s" ]] && echo "$s"
    done
}

# logging fallbacks (mirror 07_solo_wallet.sh so the lib survives standalone use)
if ! declare -F info    >/dev/null 2>&1; then info()    { echo "[INFO]  $*"; }; fi
if ! declare -F warn    >/dev/null 2>&1; then warn()    { echo "[WARN]  $*"; }; fi
if ! declare -F error   >/dev/null 2>&1; then error()   { echo "[ERROR] $*" >&2; }; fi
if ! declare -F success >/dev/null 2>&1; then success() { echo "[OK]    $*"; }; fi
if ! declare -F _solo_pause >/dev/null 2>&1; then _solo_pause() { echo ""; echo "Press Enter to continue..."; read -r || true; }; fi

# ─── Config (personal key stored base64 to dodge all quoting issues) ─────────
SB_PERSONAL_KEY=""
SB_KEEP="$SB_KEEP_DEFAULT"
SB_HOUR=3
SB_MIN=30

sb_load_conf() {
    SB_PERSONAL_KEY=""; SB_KEEP="$SB_KEEP_DEFAULT"; SB_HOUR=3; SB_MIN=30
    local SB_PERSONAL_KEY_B64=""
    [[ -f "$SB_CONF" ]] || return 0
    # shellcheck disable=SC1090
    source "$SB_CONF" 2>/dev/null || true
    [[ -n "$SB_PERSONAL_KEY_B64" ]] && SB_PERSONAL_KEY=$(printf '%s' "$SB_PERSONAL_KEY_B64" | base64 -d 2>/dev/null || true)
    [[ "$SB_KEEP" =~ ^[0-9]+$ ]] || SB_KEEP="$SB_KEEP_DEFAULT"
    [[ "$SB_HOUR" =~ ^[0-9]+$ ]] || SB_HOUR=3
    [[ "$SB_MIN"  =~ ^[0-9]+$ ]] || SB_MIN=30
}

sb_save_conf() {
    mkdir -p "$(dirname "$SB_CONF")"
    local b64; b64=$(printf '%s' "$SB_PERSONAL_KEY" | base64 | tr -d '\n')
    ( umask 077; cat > "$SB_CONF" <<EOF
# Grin solo-mining backup config — generated by 07_grin_mining_solo.sh
# Personal key is base64-encoded (NOT encryption — just safe storage).
# This file is mode 600 and is NEVER included in a backup archive.
SB_PERSONAL_KEY_B64='$b64'
SB_KEEP=$SB_KEEP
SB_HOUR=$SB_HOUR
SB_MIN=$SB_MIN
EOF
    )
    chmod 600 "$SB_CONF"
    chown root:root "$SB_CONF" 2>/dev/null || true
}

sb_date() { date +%d%m%Y; }

# Parse the DDMMYYYY out of a backup filename → echo it, rc 1 if it doesn't match.
sb_parse_date() {
    local base; base=$(basename "$1")
    local d="${base#"$SB_PREFIX"}"; d="${d%.tar.gz.enc}"
    [[ "$d" =~ ^[0-9]{8}$ ]] && { echo "$d"; return 0; }
    return 1
}

# ─── Set / change the personal key ──────────────────────────────────────────
sb_set_key() {
    sb_load_conf
    echo ""
    echo -e "  ${BOLD}Backup personal key${RESET}"
    echo -e "  ${DIM}Combined with the date (DDMMYYYY) to form each archive's password.${RESET}"
    echo -e "  ${RED}${BOLD}⚠  WRITE THIS DOWN. If you forget it AND lose this server, every backup${RESET}"
    echo -e "  ${RED}${BOLD}   is permanently unrecoverable — the date alone cannot open them.${RESET}"
    [[ -n "$SB_PERSONAL_KEY" ]] && echo -e "  ${DIM}(a key is already set — entering a new one replaces it)${RESET}"
    echo ""
    local k1 k2
    read -rs -p "  New personal key (min 4 chars, 0 to cancel): " k1; echo ""
    [[ "$k1" == "0" || -z "$k1" ]] && { info "Cancelled."; return 1; }
    if [[ "${#k1}" -lt 4 ]]; then warn "Too short (min 4 chars)."; return 1; fi
    read -rs -p "  Confirm key: " k2; echo ""
    if [[ "$k1" != "$k2" ]]; then error "Keys do not match."; unset k1 k2; return 1; fi
    SB_PERSONAL_KEY="$k1"; unset k1 k2
    sb_save_conf
    success "Personal key saved → $SB_CONF (mode 600). Keep a copy somewhere safe."
}

# Ensure a key exists (prompt to set one if not). rc 1 if still unset.
_sb_require_key() {
    sb_load_conf
    if [[ -z "$SB_PERSONAL_KEY" ]]; then
        warn "No backup personal key set yet — set one now."
        sb_set_key || return 1
    fi
    [[ -n "$SB_PERSONAL_KEY" ]]
}

# ─── Prune to the newest SB_KEEP archives ───────────────────────────────────
sb_prune() {
    local keep="${1:-$SB_KEEP}" n
    n=$(ls -1 "$SB_BACKUP_DIR/${SB_PREFIX}"*.tar.gz.enc 2>/dev/null | wc -l)
    [[ "$n" -gt "$keep" ]] || return 0
    ls -t "$SB_BACKUP_DIR/${SB_PREFIX}"*.tar.gz.enc 2>/dev/null \
        | tail -n +"$((keep + 1))" | xargs rm -f 2>/dev/null || true
    info "Pruned old backups (kept newest $keep)."
}

# ─── Backup now (interactive) ───────────────────────────────────────────────
sb_backup_now() {
    clear
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${CYAN}  Backup now${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""

    command -v openssl >/dev/null 2>&1 || { error "openssl not found — cannot encrypt."; return 1; }

    local -a srcs=(); local s rels=()
    while IFS= read -r s; do srcs+=("$s"); rels+=("${s#/}"); done < <(_sb_sources)
    if [[ "${#srcs[@]}" -eq 0 ]]; then
        warn "Nothing to back up yet — set up a wallet (1/2 ▸ Wallet) first."
        return 1
    fi

    echo -e "  ${DIM}Will archive (binary included for instant restore):${RESET}"
    for s in "${srcs[@]}"; do echo -e "    ${DIM}$s${RESET}"; done
    echo ""

    _sb_require_key || { info "Backup needs a personal key."; return 1; }

    local d pass archive tmp_tar
    d=$(sb_date)
    pass="${SB_PERSONAL_KEY}${d}"
    archive="$SB_BACKUP_DIR/${SB_PREFIX}${d}.tar.gz.enc"
    tmp_tar=$(mktemp "/tmp/grin_solo_bak_XXXXXX.tar.gz") || { error "mktemp failed."; return 1; }

    mkdir -p "$SB_BACKUP_DIR"; chmod 700 "$SB_BACKUP_DIR" 2>/dev/null || true

    info "Creating archive..."
    # Relative-to-/ paths → restore with `-C /` lands them back exactly.
    # tar may exit non-zero for a benign "file changed as we read it" (the live
    # listener touching a file) — that's a warning, not fatal. But an EMPTY tmp
    # means a real failure (disk full / nothing readable): never encrypt that.
    if ! tar -czf "$tmp_tar" -C / "${rels[@]}" 2>/dev/null; then
        warn "tar reported issues (a file changed mid-read, or a missing optional path — usually harmless)."
    fi
    if [[ ! -s "$tmp_tar" ]]; then
        rm -f "$tmp_tar"
        error "Archive came out empty — aborting (disk full, or nothing readable)."
        return 1
    fi

    # fd:3 here-string keeps the password out of `ps aux`.
    if ! openssl enc -aes-256-cbc -pbkdf2 -iter 600000 -salt \
            -pass fd:3 -in "$tmp_tar" -out "$archive" 3<<<"$pass" 2>/dev/null; then
        rm -f "$tmp_tar" "$archive"; unset pass
        error "openssl encryption failed."; return 1
    fi
    rm -f "$tmp_tar"; unset pass
    chmod 600 "$archive"; chown root:root "$archive" 2>/dev/null || true

    local sz; sz=$(du -sh "$archive" 2>/dev/null | cut -f1 || echo "?")
    success "Backup created: $archive  ($sz, mode 600)"
    echo -e "  ${DIM}Password = your personal key + ${d} (date in the filename).${RESET}"
    echo -e "  ${YELLOW}Store offsite copies only if you trust them with the seed — the key${RESET}"
    echo -e "  ${YELLOW}protects them, but anyone with both the file and your key can spend.${RESET}"
    mkdir -p "$(dirname "$SB_LOG")"
    echo "[$(date -u '+%Y-%m-%d %H:%M:%S UTC')] backup created: $(basename "$archive") ($sz)" >> "$SB_LOG" 2>/dev/null || true

    sb_prune "$SB_KEEP"
}

# ─── Restore (interactive) ──────────────────────────────────────────────────
sb_restore() {
    clear
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${CYAN}  Restore from backup${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""

    command -v openssl >/dev/null 2>&1 || { error "openssl not found — cannot decrypt."; return 1; }

    local -a baks=()
    while IFS= read -r f; do [[ -n "$f" ]] && baks+=("$f"); done \
        < <(ls -t "$SB_BACKUP_DIR/${SB_PREFIX}"*.tar.gz.enc 2>/dev/null || true)
    if [[ "${#baks[@]}" -eq 0 ]]; then
        warn "No backups found in $SB_BACKUP_DIR."
        echo -e "  ${DIM}On a fresh machine, copy your grin_solo_backup_*.tar.gz.enc there first.${RESET}"
        return 1
    fi

    echo -e "  ${BOLD}Available backups (newest first):${RESET}"
    local i=1 f sz
    for f in "${baks[@]}"; do
        sz=$(du -sh "$f" 2>/dev/null | cut -f1 || echo "?")
        echo -e "  ${GREEN}$i${RESET}) $(basename "$f")  ${DIM}($sz)${RESET}"
        (( i++ ))
    done
    echo -e "  ${DIM}0) Cancel${RESET}"
    echo ""
    echo -ne "${BOLD}Select backup [1-${#baks[@]}/0]: ${RESET}"
    local sel; read -r sel || true
    [[ "$sel" == "0" || -z "$sel" ]] && return 1
    if ! [[ "$sel" =~ ^[0-9]+$ ]] || [[ "$sel" -lt 1 || "$sel" -gt "${#baks[@]}" ]]; then
        warn "Invalid selection."; return 1
    fi
    local chosen="${baks[$((sel-1))]}"
    local d; d=$(sb_parse_date "$chosen") || { error "Cannot read date from filename: $(basename "$chosen")"; return 1; }
    echo ""
    info "Selected: $(basename "$chosen")  (date $d)"

    # Personal key ONCE → password = key + date-from-filename.
    local key pass tmp_clear
    read -rs -p "  Personal key for this backup: " key; echo ""
    [[ -z "$key" ]] && { warn "No key entered."; return 1; }
    pass="${key}${d}"; unset key
    tmp_clear=$(mktemp "/tmp/grin_solo_restore_XXXXXX.tar.gz") || { error "mktemp failed."; unset pass; return 1; }

    if ! openssl enc -d -aes-256-cbc -pbkdf2 -iter 600000 \
            -pass fd:3 -in "$chosen" -out "$tmp_clear" 3<<<"$pass" 2>/dev/null; then
        rm -f "$tmp_clear"; unset pass
        error "Wrong key or corrupt backup."; return 1
    fi
    unset pass
    if ! tar -tzf "$tmp_clear" >/dev/null 2>&1; then
        rm -f "$tmp_clear"; error "Decrypted file is not a valid archive."; return 1
    fi
    success "Decrypted and validated."

    echo ""
    echo -e "  ${RED}${BOLD}This OVERWRITES current files at their original paths:${RESET}"
    # tar entries are relative (leading / stripped); show the distinct top dirs.
    tar -tzf "$tmp_clear" 2>/dev/null | awk -F/ 'NF>=3{print "/"$1"/"$2"/"$3}' | sort -u | sed 's|^|    |'
    echo -e "  ${YELLOW}Stop any running wallet listener first (Wallet ▸ Stop) if restoring${RESET}"
    echo -e "  ${YELLOW}over a live install, so open files aren't replaced underneath it.${RESET}"
    echo ""
    echo -ne "  Proceed with restore? [y/N]: "
    local go; read -r go || true
    if [[ "${go,,}" != "y" ]]; then rm -f "$tmp_clear"; info "Restore cancelled."; return 1; fi

    if ! tar -xzf "$tmp_clear" -C / --preserve-permissions 2>/dev/null; then
        rm -f "$tmp_clear"; error "Extraction failed."; return 1
    fi
    rm -f "$tmp_clear"
    # Re-assert tight perms on restored secrets, in case the archive (or the
    # machine it was made on) carried loose modes. Cheap insurance for real GRIN.
    find "${SW_BASE:-/opt/grin/solowallet}" -type f \
        \( -name '.passphrase' -o -name '.owner_api_secret' -o -name '.foreign_api_secret' \) \
        -exec chmod 600 {} \; 2>/dev/null || true
    success "Restore complete — wallets, stats history, and config are back in place."
    echo ""
    echo -e "  ${BOLD}To resume mining (order matters — restore does NOT start anything):${RESET}"
    echo -e "    1) Build / start the node (Script 01), let it sync"
    echo -e "    2) Wallet ▸ Start listener — the restored .passphrase opens it with"
    echo -e "       ${BOLD}no password prompt${RESET}. Must be UP before mining: the node calls it"
    echo -e "       to build your coinbase reward when a block is found."
    echo -e "       ${DIM}(Re-enable Wallet ▸ Auto-restart to survive reboots — the boot cron${RESET}"
    echo -e "       ${DIM} / watchdog are NOT in the backup and must be re-created.)${RESET}"
    echo -e "    3) Stratum ▸ Setup + Publish   (re-open the stratum port to miners)"
    echo -e "    4) Stats web page              (redeploy the nginx page — optional)"
    echo -e "    ${DIM}Then point your miners at the stratum.${RESET}"
    mkdir -p "$(dirname "$SB_LOG")"
    echo "[$(date -u '+%Y-%m-%d %H:%M:%S UTC')] restore from: $(basename "$chosen")" >> "$SB_LOG" 2>/dev/null || true
}

# ─── Daily schedule (cron) ──────────────────────────────────────────────────
# The wrapper is self-contained (cron can't source the toolkit): it reads the
# key from SB_CONF, builds key+date, and runs the same tar|openssl|prune. Flags
# MUST stay byte-identical to sb_backup_now so cron archives restore cleanly.
_sb_write_wrapper() {
    cat > "$SB_WRAPPER" <<WRAP
#!/bin/bash
# Grin solo-mining daily backup — generated by 07_grin_mining_solo.sh. Do not edit.
set -uo pipefail
export PATH=/usr/local/bin:/usr/bin:/bin   # cron has a minimal PATH; be explicit
CONF="$SB_CONF"
BACKUP_DIR="$SB_BACKUP_DIR"
PREFIX="$SB_PREFIX"
LOG="$SB_LOG"
SOURCES=( "${SW_BASE:-/opt/grin/solowallet}" "${SW_STATE_DIR:-/opt/grin/solo-stats}" "${PAYMENT_CONFIG:-/opt/grin/conf/grin_solo_payment.json}" )

TS=\$(date -u '+%Y-%m-%d %H:%M:%S UTC')
[[ -f "\$CONF" ]] || { echo "[\$TS] ERROR: no config \$CONF" >> "\$LOG"; exit 1; }
SB_PERSONAL_KEY_B64=""; SB_KEEP=$SB_KEEP_DEFAULT
# shellcheck disable=SC1090
source "\$CONF"
KEY=\$(printf '%s' "\$SB_PERSONAL_KEY_B64" | base64 -d 2>/dev/null || true)
[[ -n "\$KEY" ]] || { echo "[\$TS] ERROR: no personal key set" >> "\$LOG"; exit 1; }
[[ "\$SB_KEEP" =~ ^[0-9]+\$ ]] || SB_KEEP=$SB_KEEP_DEFAULT

D=\$(date +%d%m%Y)
PASS="\${KEY}\${D}"
ARCHIVE="\$BACKUP_DIR/\${PREFIX}\${D}.tar.gz.enc"
mkdir -p "\$BACKUP_DIR"; chmod 700 "\$BACKUP_DIR" 2>/dev/null || true

RELS=(); for s in "\${SOURCES[@]}"; do [[ -e "\$s" ]] && RELS+=( "\${s#/}" ); done
[[ "\${#RELS[@]}" -gt 0 ]] || { echo "[\$TS] ERROR: nothing to back up" >> "\$LOG"; exit 1; }

TMP=\$(mktemp /tmp/grin_solo_cronbak_XXXXXX.tar.gz) || exit 1
tar -czf "\$TMP" -C / "\${RELS[@]}" 2>/dev/null || true
[[ -s "\$TMP" ]] || { rm -f "\$TMP"; echo "[\$TS] ERROR: empty archive (disk full?)" >> "\$LOG"; exit 1; }
if openssl enc -aes-256-cbc -pbkdf2 -iter 600000 -salt -pass fd:3 \
        -in "\$TMP" -out "\$ARCHIVE" 3<<<"\$PASS" 2>/dev/null; then
    chmod 600 "\$ARCHIVE"; chown root:root "\$ARCHIVE" 2>/dev/null || true
    SZ=\$(du -sh "\$ARCHIVE" 2>/dev/null | cut -f1 || echo "?")
    echo "[\$TS] backup created: \$(basename "\$ARCHIVE") (\$SZ)" >> "\$LOG"
else
    rm -f "\$TMP" "\$ARCHIVE"; echo "[\$TS] ERROR: openssl failed" >> "\$LOG"; exit 1
fi
rm -f "\$TMP"; unset PASS KEY

# Prune to newest \$SB_KEEP
N=\$(ls -1 "\$BACKUP_DIR/\${PREFIX}"*.tar.gz.enc 2>/dev/null | wc -l)
if [[ "\$N" -gt "\$SB_KEEP" ]]; then
    ls -t "\$BACKUP_DIR/\${PREFIX}"*.tar.gz.enc 2>/dev/null \
        | tail -n +\$((SB_KEEP + 1)) | xargs rm -f 2>/dev/null || true
    echo "[\$TS] pruned (kept newest \$SB_KEEP)" >> "\$LOG"
fi
WRAP
    chmod 750 "$SB_WRAPPER"
}

sb_schedule() {
    clear
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${CYAN}  Schedule daily backup${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
    sb_load_conf

    if [[ -f "$SB_CRON" ]]; then
        echo -e "  Status: ${GREEN}enabled${RESET}  ${DIM}(daily $(printf '%02d:%02d' "$SB_HOUR" "$SB_MIN"), keep $SB_KEEP)${RESET}"
        echo -e "  ${DIM}cron: $SB_CRON · log: $SB_LOG${RESET}"
        echo ""
        echo -e "  ${RED}1${RESET}) Disable daily backup"
        echo -e "  ${DIM}0) Back${RESET}"
        echo -ne "Choice: "
        local c; read -r c || true
        if [[ "$c" == "1" ]]; then
            rm -f "$SB_CRON" "$SB_WRAPPER"
            success "Daily backup disabled."
        fi
        return 0
    fi

    echo -e "  ${DIM}Runs once a day, keeps the newest $SB_KEEP archives.${RESET}"
    echo -e "  ${DIM}Uses the saved personal key — no prompt at run time.${RESET}"
    echo ""
    _sb_require_key || { info "Scheduling needs a personal key."; return 1; }

    _sb_write_wrapper
    cat > "$SB_CRON" <<EOF
# Grin solo-mining daily backup — generated by 07_grin_mining_solo.sh
$SB_MIN $SB_HOUR * * * root $SB_WRAPPER
EOF
    success "Daily backup enabled → $SB_CRON  (daily $(printf '%02d:%02d' "$SB_HOUR" "$SB_MIN"))"
    echo -e "  ${DIM}Wrapper: $SB_WRAPPER · log: $SB_LOG${RESET}"
}

# ─── Settings (key · retention · list) ──────────────────────────────────────
sb_list_backups() {
    echo ""
    echo -e "  ${BOLD}Backups in $SB_BACKUP_DIR:${RESET}"
    local any=0 f sz
    while IFS= read -r f; do
        [[ -n "$f" ]] || continue
        any=1; sz=$(du -sh "$f" 2>/dev/null | cut -f1 || echo "?")
        echo -e "    $(basename "$f")  ${DIM}($sz)${RESET}"
    done < <(ls -t "$SB_BACKUP_DIR/${SB_PREFIX}"*.tar.gz.enc 2>/dev/null || true)
    [[ "$any" -eq 0 ]] && echo -e "    ${DIM}(none yet)${RESET}"
}

sb_settings() {
    local c
    while true; do
        clear
        sb_load_conf
        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo -e "${BOLD}${CYAN}  Backup settings${RESET}"
        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo ""
        local key_state="${RED}not set${RESET}"; [[ -n "$SB_PERSONAL_KEY" ]] && key_state="${GREEN}set${RESET}"
        echo -e "  Personal key : $key_state   ${DIM}($SB_CONF)${RESET}"
        echo -e "  Retention    : ${BOLD}$SB_KEEP${RESET} archives"
        echo -e "  Schedule time: $(printf '%02d:%02d' "$SB_HOUR" "$SB_MIN")"
        sb_list_backups
        echo ""
        echo -e "  ${GREEN}1${RESET}) Set / change personal key"
        echo -e "  ${GREEN}2${RESET}) Set retention (number of archives to keep)"
        echo -e "  ${RED}0${RESET}) Back"
        echo ""
        echo -ne "${BOLD}Select [1-2/0]: ${RESET}"
        read -r c || c=0
        case "$c" in
            "") continue ;;
            1) sb_set_key || true; _solo_pause ;;
            2) echo -ne "  Keep how many archives [current $SB_KEEP]: "
               local n; read -r n || true
               if [[ "$n" =~ ^[0-9]+$ ]] && [[ "$n" -ge 1 ]]; then
                   SB_KEEP="$n"; sb_save_conf; success "Retention set to $n."
               else
                   warn "Unchanged (enter a positive number)."
               fi
               _solo_pause ;;
            0) return ;;
            *) warn "Invalid option."; sleep 1 ;;
        esac
    done
}

# ─── Show recovery seed (per net) ───────────────────────────────────────────
# The ultimate backup: the 24-word phrase regenerates the wallet anywhere.
# Runs grin-wallet's own `recover`, which prompts for the wallet password — no
# -p, so the password never hits the process list for this one-shot view.
sb_show_seed() {
    local net="${1:-mainnet}" dir bin flag toml
    dir=$(sw_dir "$net"); bin=$(sw_wallet_bin "$net"); flag=$(sw_net_flag "$net"); toml=$(sw_toml "$net")
    clear
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${CYAN}  Recovery seed — $net${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
    if [[ ! -f "$toml" || ! -x "$bin" ]]; then
        warn "No initialized wallet for $net at $dir."
        echo -e "  ${DIM}Set one up via Wallet ▸ Setup / Recover first.${RESET}"
        return 1
    fi
    echo -e "  ${RED}${BOLD}⚠  Anyone who sees these words can spend this wallet.${RESET}"
    echo -e "  ${YELLOW}Make sure no one is watching / no screen recording is running.${RESET}"
    echo -ne "  Show the recovery phrase now? [y/N]: "
    local go; read -r go || true
    [[ "${go,,}" == "y" ]] || { info "Cancelled."; return 1; }
    echo ""
    ( cd "$dir" && "$bin" $flag recover ) || warn "grin-wallet recover exited non-zero (wrong password?)."
}

# ─── Maintenance menu (top-level option 6) ──────────────────────────────────
maintenance_menu() {
    local choice net
    while true; do
        clear
        sb_load_conf
        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo -e "${BOLD}${CYAN}  Maintenance — Backup & Restore${RESET}"
        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo ""
        local sched="${RED}off${RESET}"; [[ -f "$SB_CRON" ]] && sched="${GREEN}daily $(printf '%02d:%02d' "$SB_HOUR" "$SB_MIN")${RESET}"
        local key_state="${RED}not set${RESET}"; [[ -n "$SB_PERSONAL_KEY" ]] && key_state="${GREEN}set${RESET}"
        echo -e "  ${DIM}Dir: $SB_BACKUP_DIR · key: ${RESET}$key_state${DIM} · schedule: ${RESET}$sched"
        echo ""
        echo -e "  ${GREEN}1${RESET}) Backup now            ${DIM}(encrypted archive of wallets + stats + config)${RESET}"
        echo -e "  ${GREEN}2${RESET}) Restore from backup   ${DIM}(one-shot extract to original paths)${RESET}"
        echo -e "  ${GREEN}3${RESET}) Schedule daily backup ${DIM}(cron · ${SB_KEEP}-archive retention)${RESET}"
        echo -e "  ${GREEN}4${RESET}) Settings              ${DIM}(personal key · retention · list)${RESET}"
        echo -e "  ${GREEN}5${RESET}) Show recovery seed    ${DIM}(per net — the ultimate wallet backup)${RESET}"
        echo ""
        echo -e "  ${DIM}↩  Press Enter to refresh${RESET}"
        echo -e "  ${RED}0${RESET}) Back"
        echo ""
        echo -ne "${BOLD}Select [1-5/0]: ${RESET}"
        read -r choice || choice=0
        case "$choice" in
            "") continue ;;
            1) sb_backup_now || true; _solo_pause ;;
            2) sb_restore    || true; _solo_pause ;;
            3) sb_schedule   || true; _solo_pause ;;
            4) sb_settings   || true ;;
            5) net=$(_solo_pick_net "show recovery seed") && { sb_show_seed "$net" || true; }; _solo_pause ;;
            0) return ;;
            *) warn "Invalid option."; sleep 1 ;;
        esac
    done
}
