# =============================================================================
# lib/07_solo_quiet.sh — Quiet hours (energy saver) for solo mining
# =============================================================================
# Auto-pause the stratum server during a daily window so miners stop hashing
# and save electricity (e.g. through peak-price hours). "Pause" gates the
# miner-facing stratum port at the firewall — it does NOT restart the grin node
# (grin's v5.5 boot is heavy) and does NOT touch grin-server.toml. The node
# keeps running/syncing; only the port miners connect to is dropped, so rigs
# lose their job feed and idle down. "Resume" reopens it and rigs reconnect.
#
# Mechanism (why firewall, not the toml toggle):
#   - A DROP inserted at INPUT position 1 is evaluated BEFORE any
#     ESTABLISHED-accept or ufw/firewalld jump, so it blocks NEW *and* already
#     connected miners — a plain `ufw deny` would leave live rigs mining.
#   - `ss -K` / `conntrack -D` then sever the live sockets so hashing stops
#     immediately instead of after the miner's TCP keepalive times out.
#   - No node restart, no config rewrite → the toggle is cheap enough to run
#     twice a day from cron.
#
# Times are the SERVER's local wall-clock (cron's timezone) — that is what
# electricity tariffs are keyed to. The menu prints the server timezone so the
# operator is never guessing.
#
# Files (target VPS):
#   /opt/grin/conf/grin_solo_quiet.conf   schedule config (mode 600)
#   /usr/local/bin/grin-solo-quiet        self-contained pause/resume/enforce wrapper
#   /etc/cron.d/grin-solo-quiet           pause + resume + @reboot enforce lines
#   /opt/grin/logs/solo-quiet.log         action log
#   /var/www/<stats>/data/quiet.json      schedule + live-state feed for the stats
#                                         page banner — written by the wrapper on
#                                         every action (skipped when no stats page)
#
# Sourced by 07_grin_mining_solo.sh (needs its colors/logging + the
# STRATUM_PORT_* constants + _solo_pause). No shebang — this is a sourced lib.
# =============================================================================

SQ_CONF="${SQ_CONF:-/opt/grin/conf/grin_solo_quiet.conf}"
SQ_WRAPPER="${SQ_WRAPPER:-/usr/local/bin/grin-solo-quiet}"
SQ_CRON="${SQ_CRON:-/etc/cron.d/grin-solo-quiet}"
SQ_LOG="${SQ_LOG:-/opt/grin/logs/solo-quiet.log}"

# ─── Config load / save ─────────────────────────────────────────────────────
# SQ_ENABLED 0|1 · SQ_PAUSE / SQ_RESUME "HH:MM" · SQ_NETS mainnet|testnet|both
sq_load_conf() {
    SQ_ENABLED=0
    SQ_PAUSE="08:00"
    SQ_RESUME="20:00"
    SQ_NETS="both"
    if [[ -f "$SQ_CONF" ]]; then
        # shellcheck disable=SC1090
        source "$SQ_CONF" 2>/dev/null || true
    fi
    [[ "$SQ_ENABLED" =~ ^[01]$ ]]              || SQ_ENABLED=0
    [[ "$SQ_PAUSE"  =~ ^[0-2][0-9]:[0-5][0-9]$ ]] || SQ_PAUSE="08:00"
    [[ "$SQ_RESUME" =~ ^[0-2][0-9]:[0-5][0-9]$ ]] || SQ_RESUME="20:00"
    case "$SQ_NETS" in mainnet|testnet|both) : ;; *) SQ_NETS="both" ;; esac
}

sq_save_conf() {
    mkdir -p "$(dirname "$SQ_CONF")"
    ( umask 077; cat > "$SQ_CONF" <<EOF
# Grin solo-mining quiet-hours config — generated by 07_grin_mining_solo.sh
# Times are the server's LOCAL wall-clock (cron timezone). SQ_NETS: mainnet|testnet|both
SQ_ENABLED=$SQ_ENABLED
SQ_PAUSE="$SQ_PAUSE"
SQ_RESUME="$SQ_RESUME"
SQ_NETS="$SQ_NETS"
EOF
    )
    chmod 600 "$SQ_CONF"
    chown root:root "$SQ_CONF" 2>/dev/null || true
}

# ─── Self-contained wrapper (cron can't source the toolkit) ─────────────────
# Bakes in the stratum ports + conf/log paths; reads the schedule from SQ_CONF
# at run time so a re-scheduled window takes effect without a wrapper rewrite.
_sq_write_wrapper() {
    cat > "$SQ_WRAPPER" <<WRAP
#!/bin/bash
# Grin solo-mining quiet hours — generated by 07_grin_mining_solo.sh. Do not edit.
# Usage: grin-solo-quiet {pause|resume|enforce}
#   pause    block the stratum port(s) → miners idle
#   resume   reopen the stratum port(s) → miners reconnect
#   enforce  re-derive from the schedule (used at @reboot): pause if now is
#            inside the quiet window and the schedule is enabled, else resume.
set -uo pipefail
export PATH=/usr/local/bin:/usr/sbin:/sbin:/usr/bin:/bin

CONF="$SQ_CONF"
LOG="$SQ_LOG"
PORT_MAINNET=$STRATUM_PORT_MAINNET
PORT_TESTNET=$STRATUM_PORT_TESTNET
WEB_DATA="/var/www/${STATS_BASENAME:-grin-solo-mining-stat}/data"

SQ_ENABLED=0; SQ_PAUSE=""; SQ_RESUME=""; SQ_NETS="both"
# shellcheck disable=SC1090
[[ -f "\$CONF" ]] && source "\$CONF" 2>/dev/null || true

_ts()  { date -u '+%Y-%m-%d %H:%M:%S UTC'; }
_log() { mkdir -p "\$(dirname "\$LOG")" 2>/dev/null || true; echo "[\$(_ts)] \$*" >> "\$LOG" 2>/dev/null || true; }

# Ports covered by the current SQ_NETS setting.
_ports() {
    case "\$SQ_NETS" in
        mainnet) echo "\$PORT_MAINNET" ;;
        testnet) echo "\$PORT_TESTNET" ;;
        *)       echo "\$PORT_MAINNET \$PORT_TESTNET" ;;
    esac
}

# Block one stratum port: DROP at INPUT position 1 (beats ESTABLISHED-accept and
# any ufw/firewalld jump so live rigs are cut too), then sever live sockets.
_block() {
    local p="\$1"
    if command -v iptables >/dev/null 2>&1; then
        iptables -C INPUT -p tcp --dport "\$p" -j DROP 2>/dev/null \
            || iptables -I INPUT 1 -p tcp --dport "\$p" -j DROP 2>/dev/null || true
    fi
    # Immediate disconnect of already-connected miners (best-effort — the DROP
    # rule alone still kills the connection once its TCP keepalive times out).
    # 'state established' is REQUIRED: a bare sport match would also target the
    # node's LISTEN socket on this port, and destroying that would kill the
    # stratum server itself (needing a node restart) — the exact thing we avoid.
    ss -K state established "( sport = :\$p )" >/dev/null 2>&1 || true
    command -v conntrack >/dev/null 2>&1 && conntrack -D -p tcp --dport "\$p" >/dev/null 2>&1 || true
}

# Reopen one stratum port: drain every DROP we may have stacked.
_unblock() {
    local p="\$1"
    if command -v iptables >/dev/null 2>&1; then
        while iptables -D INPUT -p tcp --dport "\$p" -j DROP 2>/dev/null; do :; done
    fi
}

# Publish the schedule + live state for the stats page banner (data/quiet.json).
# Written on EVERY action so the page tracks pause/resume within one poll cycle
# and the UTC offset self-corrects across DST changes (cron re-runs at each window
# edge). No stats page deployed → silently skipped. \$1 = live state: true|false.
_status() {
    [[ -d "\$WEB_DATA" ]] || return 0
    local off sign oh om mins en
    off=\$(date +%z)                       # e.g. +0700
    sign=\${off:0:1}; oh=\${off:1:2}; om=\${off:3:2}
    mins=\$(( 10#\$oh * 60 + 10#\$om )); [[ "\$sign" == "-" ]] && mins=\$(( -mins ))
    en=false; [[ "\${SQ_ENABLED:-0}" == "1" ]] && en=true
    printf '{"enabled":%s,"pause":"%s","resume":"%s","nets":"%s","tz":"%s","utc_offset_min":%s,"paused":%s,"updated":"%s"}\n' \
        "\$en" "\${SQ_PAUSE:-}" "\${SQ_RESUME:-}" "\${SQ_NETS:-both}" "\$(date +%Z)" "\$mins" "\$1" "\$(_ts)" \
        > "\$WEB_DATA/.quiet.json.tmp" 2>/dev/null || return 0
    chmod 644 "\$WEB_DATA/.quiet.json.tmp" 2>/dev/null || true
    mv -f "\$WEB_DATA/.quiet.json.tmp" "\$WEB_DATA/quiet.json" 2>/dev/null || true
}

_pause()  { local p; for p in \$(_ports); do _block "\$p"; done; _log "PAUSE  nets=\$SQ_NETS — stratum blocked (miners idle)"; _status true; }
_resume() { local p; for p in \$(_ports); do _unblock "\$p"; done; _log "RESUME nets=\$SQ_NETS — stratum open"; _status false; }

# Is 'now' inside [PAUSE,RESUME)?  HHMM compared as base-10 (leading zeros
# stripped so 08:00 is not read as octal). Handles windows crossing midnight.
_in_window() {
    [[ -n "\$SQ_PAUSE" && -n "\$SQ_RESUME" ]] || return 1
    local now p r
    now=\$(date +%H%M); now=\$((10#\$now))
    p=\$(echo "\$SQ_PAUSE"  | tr -d ':'); p=\$((10#\$p))
    r=\$(echo "\$SQ_RESUME" | tr -d ':'); r=\$((10#\$r))
    if (( p < r )); then
        (( now >= p && now < r ))
    else
        (( now >= p || now < r ))
    fi
}

case "\${1:-enforce}" in
    pause)  _pause ;;
    resume) _resume ;;
    enforce)
        if [[ "\${SQ_ENABLED:-0}" == "1" ]] && _in_window; then _pause; else _resume; fi ;;
    *) echo "usage: grin-solo-quiet {pause|resume|enforce}" >&2; exit 1 ;;
esac
WRAP
    chmod 750 "$SQ_WRAPPER"
    chown root:root "$SQ_WRAPPER" 2>/dev/null || true
}

# ─── Cron install / remove ──────────────────────────────────────────────────
_sq_write_cron() {
    local phour pmin rhour rmin
    phour=${SQ_PAUSE%%:*};  pmin=${SQ_PAUSE##*:}
    rhour=${SQ_RESUME%%:*};  rmin=${SQ_RESUME##*:}
    # 10#-force strips leading zeros so cron gets 8 not 08 (and never reads 08 as
    # octal). Times are already validated HH:MM by _sq_read_hhmm.
    cat > "$SQ_CRON" <<EOF
# Grin solo-mining quiet hours (energy saver) — generated by 07_grin_mining_solo.sh
# Times are this server's LOCAL timezone. nets=$SQ_NETS
$((10#$pmin)) $((10#$phour)) * * * root $SQ_WRAPPER pause
$((10#$rmin)) $((10#$rhour)) * * * root $SQ_WRAPPER resume
@reboot root sleep 30 && $SQ_WRAPPER enforce
EOF
    chmod 644 "$SQ_CRON"
    chown root:root "$SQ_CRON" 2>/dev/null || true
}

sq_disable() {
    rm -f "$SQ_CRON"
    SQ_ENABLED=0
    sq_save_conf
    # Clear any block left in place so miners are not stuck idle after disabling.
    # Conf is saved FIRST so the wrapper's stats-page publish (quiet.json) reports
    # the schedule as off, not the pre-disable state.
    [[ -x "$SQ_WRAPPER" ]] && "$SQ_WRAPPER" resume >/dev/null 2>&1 || true
    success "Quiet hours disabled — stratum reopened, schedule removed."
}

# ─── HH:MM prompt helper ────────────────────────────────────────────────────
# Echoes a validated HH:MM on stdout; rc 1 on cancel/invalid. $1=label $2=default
_sq_read_hhmm() {
    local label="$1" def="$2" raw
    echo -ne "  ${BOLD}$label${RESET} [HH:MM, default $def]: " >&2
    read -r raw || return 1
    [[ -z "$raw" ]] && { echo "$def"; return 0; }
    # Accept H:MM / HH:MM; normalise to zero-padded HH:MM.
    if [[ "$raw" =~ ^([0-9]{1,2}):([0-9]{2})$ ]]; then
        local h="${BASH_REMATCH[1]}" m="${BASH_REMATCH[2]}"
        if (( 10#$h <= 23 && 10#$m <= 59 )); then
            printf '%02d:%02d' "$((10#$h))" "$((10#$m))"
            return 0
        fi
    fi
    warn "Not a valid 24-hour time (00:00–23:59)." >&2
    return 1
}

# ─── Menu ───────────────────────────────────────────────────────────────────
# Cross-network shared tool (top menu ▸ 8). Handles both nets via SQ_NETS.
quiet_hours_menu() {
    local c
    while true; do
        clear
        sq_load_conf
        local tz; tz=$(date '+%Z' 2>/dev/null || echo "local")
        # Live state: is a DROP currently in place for either stratum port?
        local live="off" pm pt
        pm=$(iptables -C INPUT -p tcp --dport "$STRATUM_PORT_MAINNET" -j DROP 2>/dev/null && echo y || echo n)
        pt=$(iptables -C INPUT -p tcp --dport "$STRATUM_PORT_TESTNET" -j DROP 2>/dev/null && echo y || echo n)
        [[ "$pm" == "y" || "$pt" == "y" ]] && live="on"

        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo -e "${BOLD}${CYAN}  07) Solo Private Pool · Quiet Hours (energy saver)${RESET}"
        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo ""
        echo -e "  Auto-pause the stratum during set hours so your miners stop"
        echo -e "  hashing and save power. The grin node keeps running — only the"
        echo -e "  miner-facing port is gated (no node restart, no config change)."
        echo ""
        local sched_state="${RED}disabled${RESET}"
        [[ "$SQ_ENABLED" == "1" ]] && sched_state="${GREEN}enabled${RESET}"
        local paused_state="${GREEN}mining (open)${RESET}"
        [[ "$live" == "on" ]] && paused_state="${YELLOW}paused (blocked)${RESET}"
        echo -e "  Schedule : $sched_state   ${DIM}(pause ${BOLD}$SQ_PAUSE${RESET}${DIM} → resume ${BOLD}$SQ_RESUME${RESET}${DIM}, $tz · nets: $SQ_NETS)${RESET}"
        echo -e "  Stratum  : $paused_state"
        echo -e "  ${DIM}cron: $SQ_CRON · log: $SQ_LOG${RESET}"
        echo ""
        echo -e "  ${GREEN}1${RESET}) Set / update schedule   ${DIM}(pause time · resume time · which nets)${RESET}"
        echo -e "  ${GREEN}2${RESET}) Pause now                ${DIM}(block stratum immediately)${RESET}"
        echo -e "  ${GREEN}3${RESET}) Resume now               ${DIM}(reopen stratum immediately)${RESET}"
        echo -e "  ${RED}4${RESET}) Disable schedule         ${DIM}(remove cron · reopen stratum)${RESET}"
        echo -e "  ${DIM}0) Back${RESET}"
        echo ""
        echo -ne "${BOLD}Select [1-4/0]: ${RESET}"
        read -r c || c=0
        case "$c" in
            "") continue ;;
            1) sq_set_schedule || true; _solo_pause ;;
            2) _sq_write_wrapper   # always regenerate: cheap, and picks up new wrapper features on old installs
               "$SQ_WRAPPER" pause || true
               success "Stratum paused now — miners will idle. (Schedule re-asserts at the next window edge.)"
               _solo_pause ;;
            3) _sq_write_wrapper
               "$SQ_WRAPPER" resume || true
               success "Stratum reopened — miners will reconnect."
               _solo_pause ;;
            4) sq_disable || true; _solo_pause ;;
            0) return ;;
            *) warn "Invalid option."; sleep 1 ;;
        esac
    done
}

sq_set_schedule() {
    clear
    sq_load_conf
    local tz; tz=$(date '+%Z' 2>/dev/null || echo "local")
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${CYAN}  Quiet hours — set schedule${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
    echo -e "  Enter the quiet window in ${BOLD}$tz${RESET} ${DIM}(this server's local time — match your${RESET}"
    echo -e "  ${DIM}electricity peak-price hours). A window may cross midnight${RESET}"
    echo -e "  ${DIM}(e.g. pause 23:00 → resume 07:00).${RESET}"
    echo ""

    local newp newr
    newp=$(_sq_read_hhmm "Pause mining at " "$SQ_PAUSE")  || { info "Cancelled — schedule unchanged."; return 0; }
    newr=$(_sq_read_hhmm "Resume mining at" "$SQ_RESUME") || { info "Cancelled — schedule unchanged."; return 0; }
    if [[ "$newp" == "$newr" ]]; then
        warn "Pause and resume times must differ — schedule unchanged."
        return 0
    fi

    echo ""
    echo -e "  Apply to which network(s)?"
    echo -e "    ${GREEN}1${RESET}) Both  ${GREEN}2${RESET}) Mainnet only  ${GREEN}3${RESET}) Testnet only   ${DIM}(current: $SQ_NETS)${RESET}"
    echo -ne "  Select [1/2/3, Enter=keep]: "
    local nn; read -r nn || nn=""
    case "$nn" in
        1) SQ_NETS="both" ;;
        2) SQ_NETS="mainnet" ;;
        3) SQ_NETS="testnet" ;;
        "") : ;;
        *) warn "Unrecognised — keeping $SQ_NETS." ;;
    esac

    SQ_PAUSE="$newp"; SQ_RESUME="$newr"; SQ_ENABLED=1
    sq_save_conf
    _sq_write_wrapper
    _sq_write_cron
    # Bring live state in line with the new schedule right away.
    "$SQ_WRAPPER" enforce >/dev/null 2>&1 || true

    echo ""
    success "Quiet hours enabled → pause $SQ_PAUSE, resume $SQ_RESUME ($tz), nets: $SQ_NETS"
    echo -e "  ${DIM}cron: $SQ_CRON · wrapper: $SQ_WRAPPER · log: $SQ_LOG${RESET}"
    echo -e "  ${DIM}Miners lose their job feed while paused and idle down; they reconnect on resume.${RESET}"
}
