# =============================================================================
# lib/grin_backup_push.sh — shared offsite push (scp) for backup archives
# =============================================================================
# ONE remote target + ONE dedicated ssh key + ONE cron-safe CLI, shared by
# every product that produces encrypted backup archives:
#   · Script 08 ▸ 9  toolkit backup   (089_backup_restore.sh, temp_dir_*.enc)
#   · Script 07 solo Maintenance      (lib/07_solo_backup.sh, grin_solo_backup_*)
#   · Script 059 Grin Drop            (lib/059_lib_backup.sh, grin_drop_backup_*)
#
# Right after an archive is written, the product calls gbp_push_file (the
# interactive path) or the self-contained CLI /usr/local/bin/grin-backup-push
# (cron wrappers — cron can't source the toolkit). Not configured or disabled
# → silent no-op: a backup NEVER fails because the offsite hop is down; a
# failed push is logged and the local archive stays untouched.
#
# Config : /opt/grin/conf/grin_backup_remote.conf   (mode 600)
# Key    : /root/.ssh/grin_backup_push_ed25519      (dedicated, passphrase-less
#          — cron must run unattended; protect the REMOTE side instead: use a
#          low-privilege remote user that only owns the backup directory)
# CLI    : /usr/local/bin/grin-backup-push <file>   (written by gbp_setup)
# Log    : /opt/grin/logs/backup-push.log
#
# ⚠ SECURITY — what is safe to push offsite:
#   All CURRENT archives (grin_*_backup_*) are <personal_key><DDMMYYYY>-
#   encrypted → safe offsite. Only LEGACY Script-08 archives (temp_dir_*)
#   derived their password FROM THE FILENAME — treat those old files as
#   readable by anyone who obtains them.
#
# Convention: sourced lib → NO shebang / NO `set -e`.
# =============================================================================

[[ -n "${_GRIN_BACKUP_PUSH_SH_LOADED:-}" ]] && return 0
_GRIN_BACKUP_PUSH_SH_LOADED=1

# ─── Paths / constants (env-overridable for testing) ────────────────────────
GBP_CONF="${GBP_CONF:-/opt/grin/conf/grin_backup_remote.conf}"
GBP_KEY="${GBP_KEY:-/root/.ssh/grin_backup_push_ed25519}"
GBP_BIN="${GBP_BIN:-/usr/local/bin/grin-backup-push}"
GBP_LOG="${GBP_LOG:-/opt/grin/logs/backup-push.log}"
GBP_RETRY_BIN="${GBP_RETRY_BIN:-/usr/local/bin/grin-backup-push-latest}"
GBP_RETRY_TAG="# GRIN_BACKUP_PUSH_RETRY"

# Color fallbacks — parents define these; ${VAR:-…} keeps the parent's values.
RED="${RED:-\033[0;31m}"; GREEN="${GREEN:-\033[0;32m}"; YELLOW="${YELLOW:-\033[1;33m}"
CYAN="${CYAN:-\033[0;36m}"; BOLD="${BOLD:-\033[1m}"; DIM="${DIM:-\033[2m}"; RESET="${RESET:-\033[0m}"

# Logging fallbacks (survive standalone use)
if ! declare -F info    >/dev/null 2>&1; then info()    { echo "[INFO]  $*"; }; fi
if ! declare -F warn    >/dev/null 2>&1; then warn()    { echo "[WARN]  $*"; }; fi
if ! declare -F error   >/dev/null 2>&1; then error()   { echo "[ERROR] $*" >&2; }; fi
if ! declare -F success >/dev/null 2>&1; then success() { echo "[OK]    $*"; }; fi

_gbp_pause() { echo ""; echo -ne "${DIM}Press Enter to continue...${RESET}"; read -r _ || true; }

# ─── Config ──────────────────────────────────────────────────────────────────
GBP_ENABLED=0; GBP_HOST=""; GBP_PORT=22; GBP_USER=""; GBP_DIR=""; GBP_KEEP_DAYS=0

gbp_load_conf() {
    GBP_ENABLED=0; GBP_HOST=""; GBP_PORT=22; GBP_USER=""; GBP_DIR=""; GBP_KEEP_DAYS=0
    [[ -f "$GBP_CONF" ]] || return 0
    # shellcheck disable=SC1090
    source "$GBP_CONF" 2>/dev/null || true
    [[ "$GBP_PORT" =~ ^[0-9]+$ ]] || GBP_PORT=22
    [[ "$GBP_KEEP_DAYS" =~ ^[0-9]+$ ]] || GBP_KEEP_DAYS=0
    return 0
}

gbp_save_conf() {
    mkdir -p "$(dirname "$GBP_CONF")"
    ( umask 077; cat > "$GBP_CONF" <<EOF
# Offsite backup push target — generated by the Grin Node Toolkit
# (lib/grin_backup_push.sh). Consumed at run time by $GBP_BIN.
# This file is mode 600 and is NEVER included in a backup archive.
GBP_ENABLED=$GBP_ENABLED
GBP_HOST='$GBP_HOST'
GBP_PORT=$GBP_PORT
GBP_USER='$GBP_USER'
GBP_DIR='$GBP_DIR'
GBP_KEEP_DAYS=$GBP_KEEP_DAYS
EOF
    )
    chmod 600 "$GBP_CONF"
    chown root:root "$GBP_CONF" 2>/dev/null || true
}

# True when a target is saved AND the push is switched on.
gbp_configured() {
    gbp_load_conf
    [[ "$GBP_ENABLED" == "1" && -n "$GBP_HOST" && -n "$GBP_USER" && -n "$GBP_DIR" ]]
}

# ─── Dedicated ssh key ───────────────────────────────────────────────────────
gbp_ensure_key() {
    [[ -f "$GBP_KEY" ]] && return 0
    command -v ssh-keygen >/dev/null 2>&1 || { error "ssh-keygen not found — cannot create a push key."; return 1; }
    mkdir -p "$(dirname "$GBP_KEY")"
    chmod 700 "$(dirname "$GBP_KEY")" 2>/dev/null || true
    if ! ssh-keygen -q -t ed25519 -N "" -C "grin-backup-push@$(hostname)" -f "$GBP_KEY"; then
        error "ssh-keygen failed."
        return 1
    fi
    chmod 600 "$GBP_KEY"
    success "Generated dedicated push key: $GBP_KEY"
    return 0
}

# ─── The cron-safe CLI — the single push implementation ─────────────────────
# Reads the conf at RUN time (so settings changes don't need a rewrite); paths
# are baked at install time. rc 0 on success OR when not configured (silent
# no-op, so callers never fail on the hop); rc 1 on a real push failure.
_gbp_write_cli() {
    cat > "$GBP_BIN" <<WRAP
#!/bin/bash
# grin-backup-push — scp one backup archive to the configured offsite target.
# Generated by lib/grin_backup_push.sh — do not edit. Config: $GBP_CONF
set -uo pipefail
export PATH=/usr/local/bin:/usr/bin:/bin
CONF="$GBP_CONF"
KEY="$GBP_KEY"
LOG="$GBP_LOG"
ts() { date -u '+%Y-%m-%d %H:%M:%S UTC'; }
FILE="\${1:-}"
[[ -n "\$FILE" && -f "\$FILE" ]] || { echo "usage: grin-backup-push <archive-file>" >&2; exit 2; }
GBP_ENABLED=0; GBP_HOST=""; GBP_PORT=22; GBP_USER=""; GBP_DIR=""; GBP_KEEP_DAYS=0
# shellcheck disable=SC1090
[[ -f "\$CONF" ]] && source "\$CONF"
# Not configured / disabled → silent success so backups never fail on the hop.
[[ "\$GBP_ENABLED" == "1" && -n "\$GBP_HOST" && -n "\$GBP_USER" && -n "\$GBP_DIR" ]] || exit 0
[[ "\$GBP_PORT" =~ ^[0-9]+\$ ]] || GBP_PORT=22
mkdir -p "\$(dirname "\$LOG")"
[[ -f "\$KEY" ]] || { echo "[\$(ts)] ERROR: ssh key missing: \$KEY" >> "\$LOG"; exit 1; }
OPTS=( -i "\$KEY" -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=accept-new )
if scp -q "\${OPTS[@]}" -P "\$GBP_PORT" "\$FILE" "\$GBP_USER@\$GBP_HOST:\$GBP_DIR/" >> "\$LOG" 2>&1; then
    echo "[\$(ts)] pushed: \$(basename "\$FILE") -> \$GBP_USER@\$GBP_HOST:\$GBP_DIR/" >> "\$LOG"
else
    echo "[\$(ts)] ERROR: scp failed: \$(basename "\$FILE") -> \$GBP_USER@\$GBP_HOST:\$GBP_DIR/" >> "\$LOG"
    exit 1
fi
# Optional remote retention — prunes ONLY this toolkit's archive name patterns
# on the remote, so a shared remote dir holding other files is never touched.
if [[ "\$GBP_KEEP_DAYS" =~ ^[0-9]+\$ && "\$GBP_KEEP_DAYS" -gt 0 ]]; then
    ssh "\${OPTS[@]}" -p "\$GBP_PORT" "\$GBP_USER@\$GBP_HOST" \
        "find '\$GBP_DIR' -maxdepth 1 -type f \\( -name 'grin_*_backup_*.tar.gz.enc' -o -name 'temp_dir_*.tar.gz.enc' \\) -mtime +\$GBP_KEEP_DAYS -delete" \
        >> "\$LOG" 2>&1 \
        || echo "[\$(ts)] WARN: remote prune failed" >> "\$LOG"
fi
exit 0
WRAP
    chmod 750 "$GBP_BIN"
}

# ─── Catch-up retry pusher (cron) ────────────────────────────────────────────
# Standalone wrapper that pushes the NEWEST archive of each product ONLY when
# it is not already on the remote (one cheap `ssh test -f` per product first).
# Covers archives that were created while the remote was down — a re-scp of an
# already-synced big archive is avoided. No-op when push is disabled.
_gbp_write_retry_cli() {
    cat > "$GBP_RETRY_BIN" <<WRAP
#!/bin/bash
# grin-backup-push-latest — offsite catch-up pusher (cron-safe, idempotent).
# Pushes the newest archive of each product only if it isn't offsite yet.
# Generated by lib/grin_backup_push.sh — do not edit. Config: $GBP_CONF
set -uo pipefail
export PATH=/usr/local/bin:/usr/bin:/bin
CONF="$GBP_CONF"; KEY="$GBP_KEY"; CLI="$GBP_BIN"; LOG="$GBP_LOG"
[[ -x "\$CLI" ]] || exit 0
GBP_ENABLED=0; GBP_HOST=""; GBP_PORT=22; GBP_USER=""; GBP_DIR=""; GBP_KEEP_DAYS=0
# shellcheck disable=SC1090
[[ -f "\$CONF" ]] && source "\$CONF"
[[ "\$GBP_ENABLED" == "1" && -n "\$GBP_HOST" && -n "\$GBP_USER" && -n "\$GBP_DIR" ]] || exit 0
[[ "\$GBP_PORT" =~ ^[0-9]+\$ ]] || GBP_PORT=22
[[ -f "\$KEY" ]] || exit 0
OPTS=( -i "\$KEY" -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=accept-new )
for f in \\
    "\$(ls -t /opt/grin/backups/grin_toolkit_backup_*.tar.gz.enc /opt/grin/temp/temp_dir_*.tar.gz.enc 2>/dev/null | head -1)" \\
    "\$(ls -t /opt/grin/backups/grin_solo_backup_*.tar.gz.enc 2>/dev/null | head -1)" \\
    "\$(ls -t /opt/grin/backups/grin_drop_backup_*.tar.gz.enc 2>/dev/null | head -1)"; do
    [[ -n "\$f" && -f "\$f" ]] || continue
    base="\$(basename "\$f")"
    # Already offsite → skip; else delegate to the CLI (it logs success/failure).
    if ssh "\${OPTS[@]}" -p "\$GBP_PORT" "\$GBP_USER@\$GBP_HOST" "test -f '\$GBP_DIR/\$base'" 2>/dev/null; then
        continue
    fi
    "\$CLI" "\$f" || true
done
exit 0
WRAP
    chmod 750 "$GBP_RETRY_BIN"
}

_gbp_retry_installed() {
    command -v crontab >/dev/null 2>&1 || return 1
    crontab -l 2>/dev/null | grep -qF "$GBP_RETRY_TAG"
}

# Current cron schedule expression (first 5 fields) or empty when disabled.
_gbp_retry_sched() {
    crontab -l 2>/dev/null | grep -F "$GBP_RETRY_TAG" | head -1 \
        | awk '{print $1" "$2" "$3" "$4" "$5}'
}

# $1 = interval hours; 0 (or invalid) disables. Rewrites the tagged cron line.
_gbp_retry_set() {
    command -v crontab >/dev/null 2>&1 || { warn "crontab not available — cannot schedule."; return 1; }
    local hours="${1:-0}"
    if ! [[ "$hours" =~ ^[0-9]+$ ]] || [[ "$hours" -lt 1 ]]; then
        ( crontab -l 2>/dev/null | grep -vF "$GBP_RETRY_TAG" ) | crontab - 2>/dev/null || true
        return 0
    fi
    _gbp_write_retry_cli
    local sched
    if [[ "$hours" -ge 24 ]]; then sched="0 3 * * *"; else sched="0 */$hours * * *"; fi
    ( crontab -l 2>/dev/null | grep -vF "$GBP_RETRY_TAG"; echo "$sched $GBP_RETRY_BIN $GBP_RETRY_TAG" ) \
        | crontab - 2>/dev/null
}

_gbp_retry_menu() {
    if ! command -v crontab >/dev/null 2>&1; then
        warn "crontab not available on this host — cannot schedule a retry cron."
        return 1
    fi
    echo ""
    echo -e "  ${DIM}A catch-up cron re-pushes the NEWEST archive of each product, but only${RESET}"
    echo -e "  ${DIM}if it isn't on the remote yet — covers backups made while the remote${RESET}"
    echo -e "  ${DIM}was down. Harmless when everything is already synced (one ssh check).${RESET}"
    echo ""
    if _gbp_retry_installed; then
        echo -e "  Current: ${GREEN}enabled${RESET}  ${DIM}($(_gbp_retry_sched) → $GBP_RETRY_BIN)${RESET}"
    else
        echo -e "  Current: ${DIM}disabled${RESET}"
    fi
    if ! gbp_configured; then
        echo -e "  ${YELLOW}Note:${RESET} offsite push isn't enabled yet — the cron will no-op until it is."
    fi
    echo ""
    echo -ne "  Run every how many hours? (1-24, 0 = turn off, blank = keep): "
    local n; read -r n || true
    [[ -z "$n" ]] && { info "Unchanged."; return 0; }
    if ! [[ "$n" =~ ^[0-9]+$ ]]; then warn "Not a number — unchanged."; return 1; fi
    if [[ "$n" -eq 0 ]]; then
        _gbp_retry_set 0 && success "Catch-up retry cron disabled." || true
        return 0
    fi
    if [[ "$n" -gt 24 ]]; then warn "Max 24 hours — unchanged."; return 1; fi
    if _gbp_retry_set "$n"; then
        success "Catch-up retry cron enabled (every ${n}h) → $GBP_RETRY_BIN"
    fi
    return 0
}

# ─── Push one archive (product hook) ─────────────────────────────────────────
# rc 0 when not configured (no-op) or pushed OK; rc 1 on real failure. Callers
# should gate their success/fail message on gbp_configured, e.g.:
#   if gbp_configured; then gbp_push_file "$archive" && success … || warn …; fi
gbp_push_file() {
    local f="${1:-}"
    [[ -n "$f" && -f "$f" ]] || return 0
    gbp_configured || return 0
    [[ -x "$GBP_BIN" ]] || _gbp_write_cli
    "$GBP_BIN" "$f"
}

# ─── Connection test ─────────────────────────────────────────────────────────
gbp_test() {
    gbp_load_conf
    if [[ -z "$GBP_HOST" || -z "$GBP_USER" || -z "$GBP_DIR" ]]; then
        warn "No target configured yet — run Configure first."
        return 1
    fi
    [[ -f "$GBP_KEY" ]] || { error "SSH key missing: $GBP_KEY — run Configure."; return 1; }
    info "Testing ssh → ${GBP_USER}@${GBP_HOST}:${GBP_PORT} (write test in ${GBP_DIR}) ..."
    if ssh -i "$GBP_KEY" -p "$GBP_PORT" -o BatchMode=yes -o ConnectTimeout=15 \
           -o StrictHostKeyChecking=accept-new "${GBP_USER}@${GBP_HOST}" \
           "mkdir -p '$GBP_DIR' && touch '$GBP_DIR/.grin_push_test' && rm -f '$GBP_DIR/.grin_push_test'" 2>/dev/null; then
        success "Remote target OK — ${GBP_DIR} is writable."
        return 0
    fi
    error "Cannot write to ${GBP_USER}@${GBP_HOST}:${GBP_DIR} (key not authorized? wrong port/user/dir?)"
    echo -e "  ${DIM}Authorize the public key on the remote first (setup options 2/3).${RESET}"
    return 1
}

# ─── Setup sub-steps ─────────────────────────────────────────────────────────
_gbp_configure() {
    gbp_load_conf
    echo ""
    local h p u dd
    echo -ne "  Remote host / IP        [${GBP_HOST:-required}]: "
    read -r h || true; h="${h:-$GBP_HOST}"
    [[ -z "$h" ]] && { warn "Host is required."; return 1; }
    echo -ne "  SSH port                [${GBP_PORT}]: "
    read -r p || true; p="${p:-$GBP_PORT}"
    [[ "$p" =~ ^[0-9]+$ ]] || { warn "Port must be numeric."; return 1; }
    echo -ne "  Remote user             [${GBP_USER:-root}]: "
    read -r u || true; u="${u:-${GBP_USER:-root}}"
    local ddef="${GBP_DIR:-/opt/grin-offsite-backups}"
    echo -ne "  Remote directory        [$ddef]: "
    read -r dd || true; dd="${dd:-$ddef}"

    GBP_HOST="$h"; GBP_PORT="$p"; GBP_USER="$u"; GBP_DIR="$dd"; GBP_ENABLED=1
    gbp_save_conf
    gbp_ensure_key || return 1
    _gbp_write_cli
    success "Saved → $GBP_CONF   ·   CLI installed → $GBP_BIN"
    echo ""
    echo -e "  ${DIM}Note: the remote host key is trusted on first contact${RESET}"
    echo -e "  ${DIM}(StrictHostKeyChecking=accept-new) — a MITM at that first push is${RESET}"
    echo -e "  ${DIM}not detected. On an untrusted network, pre-seed ~/.ssh/known_hosts.${RESET}"
    echo ""
    # Authorize the key on the remote NOW so Configure ends handshaken, not just
    # "saved". ssh-copy-id prompts for the remote password once; if it isn't
    # available / fails, fall back to the paste-ready command (option 2).
    echo -e "  ${BOLD}Authorize this key on the remote now?${RESET}"
    echo -e "  ${DIM}Installs it via ssh-copy-id — you'll enter ${GBP_USER}@${GBP_HOST}'s password once.${RESET}"
    echo -ne "  Install now? [Y/n]: "
    local a; read -r a || true
    if [[ "${a,,}" != "n" ]]; then
        if ! _gbp_copy_id; then
            echo ""
            warn "Automatic install didn't complete — run this on the remote instead:"
            _gbp_show_key || true
        fi
    else
        echo -e "  ${DIM}Skipped — later use option 3 (ssh-copy-id) or option 2 (paste command).${RESET}"
    fi
    echo ""
    echo -ne "  Test the connection now? [Y/n]: "
    local t; read -r t || true
    if [[ "${t,,}" != "n" ]]; then gbp_test || true; fi
    echo ""
    echo -e "  ${YELLOW}Note:${RESET} if a solo / Grin Drop ${BOLD}daily backup schedule${RESET} was enabled BEFORE"
    echo -e "  this feature existed, disable & re-enable it once — that regenerates its"
    echo -e "  cron wrapper with the push step. (Script 08 ▸ 9 schedules need nothing.)"
    return 0
}

_gbp_show_key() {
    gbp_ensure_key || return 1
    gbp_load_conf
    local keyline dir user host
    keyline="$(cat "${GBP_KEY}.pub" 2>/dev/null)"
    [[ -n "$keyline" ]] || { error "Public key unreadable: ${GBP_KEY}.pub"; return 1; }
    dir="${GBP_DIR:-/opt/grin-offsite-backups}"
    user="${GBP_USER:-<user>}"; host="${GBP_HOST:-<host>}"
    echo ""
    echo -e "  ${BOLD}Authorize this node on the remote backup box${RESET}"
    echo -e "  ${DIM}Paste the whole block below into ONE terminal on the remote,${RESET}"
    echo -e "  ${DIM}logged in as the user you configured (${BOLD}${user}${RESET}${DIM}@${host}). Safe to re-run.${RESET}"
    echo ""
    echo -e "  ${CYAN}────────────────────────────────────────────────────────────${RESET}"
    # Printed plain (no color) so the operator can copy it cleanly. The key and
    # dir are substituted in; \$K stays literal so the block runs on the remote.
    cat <<EOF
install -d -m 700 ~/.ssh
K='${keyline}'
grep -qxF "\$K" ~/.ssh/authorized_keys 2>/dev/null || echo "\$K" >> ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
mkdir -p '${dir}'
EOF
    echo -e "  ${CYAN}────────────────────────────────────────────────────────────${RESET}"
    echo ""
    echo -e "  ${DIM}It fixes ~/.ssh perms, appends the key only once, and creates the${RESET}"
    echo -e "  ${DIM}backup dir. Then verify from here with option 4 (Test connection).${RESET}"
    echo ""
    echo -e "  ${DIM}Bare key line only (if you manage authorized_keys yourself):${RESET}"
    echo -e "  ${DIM}${keyline}${RESET}"
    return 0
}

_gbp_copy_id() {
    gbp_load_conf
    [[ -n "$GBP_HOST" && -n "$GBP_USER" ]] || { warn "Configure the target first (option 1)."; return 1; }
    gbp_ensure_key || return 1
    command -v ssh-copy-id >/dev/null 2>&1 || { warn "ssh-copy-id not found — paste the key manually (option 2)."; return 1; }
    info "You will be asked for ${GBP_USER}@${GBP_HOST}'s password once."
    if ! ssh-copy-id -i "${GBP_KEY}.pub" -p "$GBP_PORT" -o StrictHostKeyChecking=accept-new "${GBP_USER}@${GBP_HOST}"; then
        error "ssh-copy-id failed."
        return 1
    fi
    success "Key installed on the remote."
    return 0
}

_gbp_set_retention() {
    gbp_load_conf
    echo ""
    echo -e "  ${DIM}After each successful push, archives older than N days are deleted on the${RESET}"
    echo -e "  ${DIM}REMOTE (only this toolkit's archive name patterns are ever touched).${RESET}"
    echo -ne "  Keep how many days on the remote (0 = keep all) [current: ${GBP_KEEP_DAYS}]: "
    local n; read -r n || true
    [[ -z "$n" ]] && return 0
    if [[ "$n" =~ ^[0-9]+$ ]]; then
        GBP_KEEP_DAYS="$n"; gbp_save_conf
        success "Remote retention set to ${n} day(s)."
    else
        warn "Not a number — unchanged."
    fi
    return 0
}

# Convenience: push the newest local archive of each product right now.
_gbp_push_now() {
    gbp_configured || { warn "Offsite push is not configured/enabled."; return 1; }
    [[ -x "$GBP_BIN" ]] || _gbp_write_cli
    local -a cands=()
    local f
    for f in \
        "$(ls -t /opt/grin/backups/grin_toolkit_backup_*.tar.gz.enc /opt/grin/temp/temp_dir_*.tar.gz.enc 2>/dev/null | head -1)" \
        "$(ls -t /opt/grin/backups/grin_solo_backup_*.tar.gz.enc 2>/dev/null | head -1)" \
        "$(ls -t /opt/grin/backups/grin_drop_backup_*.tar.gz.enc 2>/dev/null | head -1)"; do
        [[ -n "$f" && -f "$f" ]] && cands+=("$f")
    done
    if [[ "${#cands[@]}" -eq 0 ]]; then
        warn "No local archives found (run a Backup now first)."
        return 1
    fi
    local ok=0 fail=0
    for f in "${cands[@]}"; do
        info "Pushing $(basename "$f") ..."
        if "$GBP_BIN" "$f"; then
            success "  pushed."
            ok=$((ok + 1))
        else
            error "  failed — see $GBP_LOG"
            fail=$((fail + 1))
        fi
    done
    info "Done: $ok pushed, $fail failed."
    return 0
}

# ─── Setup menu (called from 089 / solo / drop menus) ────────────────────────
gbp_setup() {
    local c
    while true; do
        clear
        gbp_load_conf
        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo -e "${BOLD}${CYAN}  Offsite backup push (scp to a remote server)${RESET}"
        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo ""
        local st="${RED}not configured${RESET}"
        if [[ -n "$GBP_HOST" ]]; then
            if [[ "$GBP_ENABLED" == "1" ]]; then
                st="${GREEN}enabled${RESET} ${DIM}→ ${GBP_USER}@${GBP_HOST}:${GBP_DIR} (port ${GBP_PORT})${RESET}"
            else
                st="${YELLOW}disabled${RESET} ${DIM}(target saved: ${GBP_USER}@${GBP_HOST}:${GBP_DIR})${RESET}"
            fi
        fi
        local ks="${RED}missing${RESET}"; [[ -f "$GBP_KEY" ]] && ks="${GREEN}present${RESET}"
        local rl="keep all"; [[ "$GBP_KEEP_DAYS" -gt 0 ]] && rl="keep ${GBP_KEEP_DAYS} days"
        local rc="${DIM}off${RESET}"; _gbp_retry_installed && rc="${GREEN}on${RESET} ${DIM}($(_gbp_retry_sched))${RESET}"
        echo -e "  Status        : $st"
        echo -e "  SSH key       : $ks   ${DIM}($GBP_KEY)${RESET}"
        echo -e "  Remote prune  : ${BOLD}$rl${RESET}"
        echo -e "  Retry cron    : $rc"
        echo -e "  Log           : ${DIM}$GBP_LOG${RESET}"
        [[ -f "$GBP_LOG" ]] && echo -e "  Last activity : ${DIM}$(tail -1 "$GBP_LOG" 2>/dev/null)${RESET}"
        echo ""
        echo -e "  ${DIM}Every finished backup archive (toolkit 08▸9, solo 07, Grin Drop 059)${RESET}"
        echo -e "  ${DIM}is scp'd to this ONE target right after creation. Push failures never${RESET}"
        echo -e "  ${DIM}break the backup — the local archive always stays.${RESET}"
        echo ""
        echo -e "  ${YELLOW}⚠  All current archives (grin_*_backup_*) are personal-key encrypted${RESET}"
        echo -e "  ${YELLOW}   → safe offsite. Only LEGACY Script-08 archives (temp_dir_*) used a${RESET}"
        echo -e "  ${YELLOW}   filename-derived password — treat those old files as readable by${RESET}"
        echo -e "  ${YELLOW}   anyone who obtains them.${RESET}"
        echo ""
        echo -e "  ${GREEN}1${RESET}) Configure target        ${DIM}(host / port / user / dir · generates the key)${RESET}"
        echo -e "  ${GREEN}2${RESET}) Show target-host command  ${DIM}(paste on the remote to authorize)${RESET}"
        echo -e "  ${GREEN}3${RESET}) Send key with ssh-copy-id ${DIM}(asks the remote password once)${RESET}"
        echo -e "  ${GREEN}4${RESET}) Test connection"
        echo -e "  ${GREEN}5${RESET}) Remote retention days"
        echo -e "  ${GREEN}6${RESET}) Push newest archives now ${DIM}(seed the remote with current backups)${RESET}"
        echo -e "  ${GREEN}7${RESET}) Catch-up retry cron      ${DIM}(re-push newest if it missed the remote)${RESET}"
        echo -e "  ${BOLD}E${RESET}) Enable    ${BOLD}D${RESET}) Disable ${DIM}(target kept)${RESET}"
        echo -e "  ${RED}0${RESET}) Back"
        echo ""
        echo -ne "${BOLD}Select [1-7/E/D/0]: ${RESET}"
        read -r c || c=0
        case "${c,,}" in
            "") continue ;;
            1) _gbp_configure     || true; _gbp_pause ;;
            2) _gbp_show_key      || true; _gbp_pause ;;
            3) _gbp_copy_id       || true; _gbp_pause ;;
            4) gbp_test           || true; _gbp_pause ;;
            5) _gbp_set_retention || true; _gbp_pause ;;
            6) _gbp_push_now      || true; _gbp_pause ;;
            7) _gbp_retry_menu    || true; _gbp_pause ;;
            e)
                if [[ -n "$GBP_HOST" ]]; then
                    GBP_ENABLED=1; gbp_save_conf; success "Offsite push enabled."
                else
                    warn "Configure a target first (option 1)."
                fi
                _gbp_pause ;;
            d)
                GBP_ENABLED=0; gbp_save_conf
                success "Offsite push disabled (target and key kept)."
                _gbp_pause ;;
            0) return 0 ;;
            *) warn "Invalid option."; sleep 1 ;;
        esac
    done
}
