# =============================================================================
# lib/grin_backup_engine.sh — shared backup engine (naming · key · crypto · prune)
# =============================================================================
# ONE standard for every product backup, so the implementations cannot drift:
#   Location : /opt/grin/backups/
#   Filename : grin_<product>_backup_<DDMMYYYY>.tar.gz.enc
#              product ∈ solo · drop · toolkit … — product and date are always
#              readable from the name; ONE archive per product per day
#              (a same-day backup overwrites that day's file).
#   Password : <personal_key><DDMMYYYY> — ONE personal key shared by ALL
#              products, stored base64 in /opt/grin/conf/grin_backup.conf
#              (mode 600) so unattended cron runs work; typed BY HAND on
#              restore. The date half is parsed from the filename (per-file
#              salt, not a secret).
#   Crypto   : AES-256-CBC · PBKDF2 600k iters · password via fd:3 here-string
#              (never on the process list).
#
# Products keep what is genuinely theirs: the SOURCE LIST (what to tar) and
# the RESTORE steps (stop services, fix perms, restart). Everything mechanical
# — key handling, naming, encrypt/decrypt, SQLite snapshots, prune, offsite
# push — lives here.
#
# Key migration: on first load, if the shared conf has no key yet, an existing
# personal key is adopted from the legacy per-product confs (solo first, then
# drop) so current operators keep their key. Old archives ALWAYS stay
# restorable — restore asks you to TYPE the key that was in force when the
# archive was created.
#
# Offsite: gbe_finalize_archive pushes the finished archive via
# lib/grin_backup_push.sh (silent no-op unless the operator configured it).
#
# Convention: sourced lib → NO shebang / NO `set -e`.
# =============================================================================

[[ -n "${_GRIN_BACKUP_ENGINE_SH_LOADED:-}" ]] && return 0
_GRIN_BACKUP_ENGINE_SH_LOADED=1

# Offsite push (scp) helpers — provides gbp_* plus the color/logging fallbacks.
# shellcheck disable=SC1091
source "$(dirname "${BASH_SOURCE[0]}")/grin_backup_push.sh"

# ─── Paths / constants (env-overridable for testing) ────────────────────────
GBE_BACKUP_DIR="${GBE_BACKUP_DIR:-/opt/grin/backups}"
GBE_CONF="${GBE_CONF:-/opt/grin/conf/grin_backup.conf}"

# Legacy per-product confs (pre-engine) — a key found here is adopted once.
GBE_LEGACY_SOLO_CONF="${GBE_LEGACY_SOLO_CONF:-/opt/grin/conf/grin_solo_backup.conf}"
GBE_LEGACY_DROP_CONF="${GBE_LEGACY_DROP_CONF:-/opt/grin/conf/grin_drop_backup.conf}"

GBE_PERSONAL_KEY=""
GBE_ARCHIVE=""

# ─── Shared personal key ─────────────────────────────────────────────────────
gbe_save_key() {
    mkdir -p "$(dirname "$GBE_CONF")"
    local b64; b64=$(printf '%s' "$GBE_PERSONAL_KEY" | base64 | tr -d '\n')
    ( umask 077; cat > "$GBE_CONF" <<EOF
# Shared backup personal key — generated by lib/grin_backup_engine.sh.
# ONE key for ALL product backups (solo · drop · toolkit). Base64 is safe
# storage, NOT encryption. Mode 600 — NEVER included in any backup archive.
GBE_PERSONAL_KEY_B64='$b64'
EOF
    )
    chmod 600 "$GBE_CONF"
    chown root:root "$GBE_CONF" 2>/dev/null || true
}

# Load the shared key; on first use adopt one from a legacy per-product conf.
gbe_load_key() {
    GBE_PERSONAL_KEY=""
    local GBE_PERSONAL_KEY_B64=""
    if [[ -f "$GBE_CONF" ]]; then
        # shellcheck disable=SC1090
        source "$GBE_CONF" 2>/dev/null || true
        [[ -n "$GBE_PERSONAL_KEY_B64" ]] && \
            GBE_PERSONAL_KEY=$(printf '%s' "$GBE_PERSONAL_KEY_B64" | base64 -d 2>/dev/null || true)
        [[ -n "$GBE_PERSONAL_KEY" ]] && return 0
    fi
    # Migration — sed (not source) so legacy schedule vars can't leak in here.
    local lc b64
    for lc in "$GBE_LEGACY_SOLO_CONF" "$GBE_LEGACY_DROP_CONF"; do
        [[ -f "$lc" ]] || continue
        b64=$(sed -n "s/^[A-Za-z_]*_PERSONAL_KEY_B64='\([^']*\)'.*/\1/p" "$lc" 2>/dev/null | head -1 || true)
        [[ -n "$b64" ]] || continue
        GBE_PERSONAL_KEY=$(printf '%s' "$b64" | base64 -d 2>/dev/null || true)
        if [[ -n "$GBE_PERSONAL_KEY" ]]; then
            gbe_save_key
            info "Adopted the backup personal key from $(basename "$lc") → $GBE_CONF (now shared by ALL products)."
            return 0
        fi
    done
    return 0
}

gbe_set_key() {
    gbe_load_key
    echo ""
    echo -e "  ${BOLD}Backup personal key — shared by ALL product backups${RESET}"
    echo -e "  ${DIM}Combined with the date (DDMMYYYY) to form each archive's password:${RESET}"
    echo -e "  ${DIM}<personal_key><DDMMYYYY>, e.g. 123abc$(date +%d%m%Y).${RESET}"
    echo -e "  ${RED}${BOLD}⚠  WRITE THIS DOWN. If you forget it AND lose this server, every backup${RESET}"
    echo -e "  ${RED}${BOLD}   is permanently unrecoverable — the date alone cannot open them, and${RESET}"
    echo -e "  ${RED}${BOLD}   wallet seed words live INSIDE these archives.${RESET}"
    [[ -n "$GBE_PERSONAL_KEY" ]] && echo -e "  ${DIM}(a key is already set — entering a new one replaces it for FUTURE archives;${RESET}" \
        && echo -e "  ${DIM} old archives keep needing the key they were created with)${RESET}"
    echo ""
    local k1 k2
    read -rs -p "  New personal key (min 4 chars, 0 to cancel): " k1; echo ""
    [[ "$k1" == "0" || -z "$k1" ]] && { info "Cancelled."; return 1; }
    if [[ "${#k1}" -lt 4 ]]; then warn "Too short (min 4 chars)."; return 1; fi
    read -rs -p "  Confirm key: " k2; echo ""
    if [[ "$k1" != "$k2" ]]; then error "Keys do not match."; unset k1 k2; return 1; fi
    GBE_PERSONAL_KEY="$k1"; unset k1 k2
    gbe_save_key
    success "Personal key saved → $GBE_CONF (mode 600, shared by all products). Keep a copy somewhere safe."
    return 0
}

# Ensure a key exists (prompt to set one if not). rc 1 if still unset.
gbe_require_key() {
    gbe_load_key
    if [[ -z "$GBE_PERSONAL_KEY" ]]; then
        warn "No backup personal key set yet — set one now (shared by all products)."
        gbe_set_key || return 1
    fi
    [[ -n "$GBE_PERSONAL_KEY" ]]
}

# ─── Naming ──────────────────────────────────────────────────────────────────
gbe_date() { date +%d%m%Y; }

# gbe_archive_path <product> [DDMMYYYY] → standard archive path
gbe_archive_path() {
    echo "$GBE_BACKUP_DIR/grin_${1}_backup_${2:-$(gbe_date)}.tar.gz.enc"
}

# Parse the DDMMYYYY out of grin_<product>_backup_DDMMYYYY.tar.gz.enc → echo,
# rc 1 if the name doesn't match the standard.
gbe_parse_date() {
    local base; base=$(basename "$1")
    local d="${base##*_}"; d="${d%.tar.gz.enc}"
    [[ "$d" =~ ^[0-9]{8}$ ]] && { echo "$d"; return 0; }
    return 1
}

# ─── Crypto (single definition of the openssl flags) ─────────────────────────
# fd:3 here-string keeps the password out of `ps aux`.
gbe_encrypt() {  # <in> <out> <pass>
    openssl enc -aes-256-cbc -pbkdf2 -iter 600000 -salt \
        -pass fd:3 -in "$1" -out "$2" 3<<<"$3" 2>/dev/null
}

gbe_decrypt() {  # <in> <out> <pass>
    openssl enc -d -aes-256-cbc -pbkdf2 -iter 600000 \
        -pass fd:3 -in "$1" -out "$2" 3<<<"$3" 2>/dev/null
}

# ─── Consistent SQLite snapshot (online-backup API, cp -p fallback) ──────────
gbe_snapshot_db() {  # <src.db> <dst>
    mkdir -p "$(dirname "$2")"
    python3 -c 'import sqlite3,sys; s=sqlite3.connect(sys.argv[1]); d=sqlite3.connect(sys.argv[2]); s.backup(d); d.close(); s.close()' \
        "$1" "$2" 2>/dev/null || cp -p "$1" "$2"
}

# ─── Finalize: verify → encrypt → perms → offsite push ───────────────────────
# gbe_finalize_archive <product> <tmp_tar_gz> [dest_dir]
# Verifies the tar is non-empty, encrypts it with <personal_key><DDMMYYYY> to
# the standard name in dest_dir (default $GBE_BACKUP_DIR), sets 600 root:root,
# then pushes offsite (no-op unless configured). Consumes the tmp file either
# way. Sets $GBE_ARCHIVE to the final path. Caller must have run
# gbe_require_key (or gbe_load_key + checked, for unattended runs).
gbe_finalize_archive() {
    local product="$1" tmp="$2" dest="${3:-$GBE_BACKUP_DIR}"
    GBE_ARCHIVE=""
    # Zero-byte guard — catches a truncated/failed write (disk full mid-tar). A
    # valid gzip of an empty tar still has a ~20-byte header, so this does NOT
    # detect "tar ran but captured nothing"; callers pass a non-empty source set.
    if [[ ! -s "$tmp" ]]; then
        rm -f "$tmp"
        error "Archive came out empty (zero bytes) — aborting (disk full?)."
        return 1
    fi
    if [[ -z "$GBE_PERSONAL_KEY" ]]; then
        rm -f "$tmp"
        error "No backup personal key loaded — cannot encrypt."
        return 1
    fi
    local d pass out
    d=$(gbe_date)
    pass="${GBE_PERSONAL_KEY}${d}"
    mkdir -p "$dest"; chmod 700 "$dest" 2>/dev/null || true
    out="$dest/grin_${product}_backup_${d}.tar.gz.enc"
    if ! gbe_encrypt "$tmp" "$out" "$pass"; then
        rm -f "$tmp" "$out"; unset pass
        error "openssl encryption failed."
        return 1
    fi
    rm -f "$tmp"; unset pass
    chmod 600 "$out"; chown root:root "$out" 2>/dev/null || true
    GBE_ARCHIVE="$out"
    local sz; sz=$(du -sh "$out" 2>/dev/null | cut -f1 || echo "?")
    success "Backup created: $out  ($sz, mode 600)"
    echo -e "  ${DIM}Password = your personal key + ${d} (the date in the filename).${RESET}"
    if gbp_configured; then
        if gbp_push_file "$out"; then
            success "Offsite copy pushed → ${GBP_USER}@${GBP_HOST}:${GBP_DIR}"
        else
            warn "Offsite push FAILED — local archive is safe. See ${GBP_LOG}."
        fi
    fi
    return 0
}

# ─── Prune to the newest N archives of one product ───────────────────────────
gbe_prune_count() {  # <product> <keep_n> [dir]
    local product="$1" keep="$2" dir="${3:-$GBE_BACKUP_DIR}" n
    [[ "$keep" =~ ^[0-9]+$ && "$keep" -ge 1 ]] || return 0
    n=$(ls -1 "$dir/grin_${product}_backup_"*.tar.gz.enc 2>/dev/null | wc -l)
    [[ "$n" -gt "$keep" ]] || return 0
    ls -t "$dir/grin_${product}_backup_"*.tar.gz.enc 2>/dev/null \
        | tail -n +"$((keep + 1))" | xargs rm -f 2>/dev/null || true
    info "Pruned old $product backups (kept newest $keep)."
}
