#!/bin/bash
# =============================================================================
# 085_ssh_hardening.sh - SSH Key Hardening (root login by key, not password)
# =============================================================================
# Gets a working SSH public key onto the server, verifies key login, then
# optionally disables password authentication so the box is reachable by key
# only — with a guaranteed rollback / break-glass path so you can never lock
# yourself out.
#
# Scope: root, plus an optional non-root admin account created by the guided
# setup (W) for the "key ▸ user ▸ sudo ▸ root" model. The toolkit itself
# still needs root, reached with `sudo -i` once that model is in place.
#
# Key handling (3 alternative methods — pick one, not a sequence):
#   1) Paste manually          — paste the public key from your laptop
#   2) Generate on server      — ssh-keygen here; private key shown ONCE to save
#   3) Fetch from URL          — github username, or any raw URL serving a
#                                PUBLIC key (e.g. github.com/<user>.keys, or a
#                                self-hosted pubkey directory). Private keys are
#                                NEVER generated by or fetched from a website.
#
# Hardening is staged safely:
#   · changes go to a drop-in (/etc/ssh/sshd_config.d/99-grin-hardening.conf)
#     when the distro supports Include, else a marked block in sshd_config
#   · every change is validated with `sshd -t` BEFORE it is applied
#   · sshd is RELOADED, never restarted (your current session survives)
#   · disabling passwords is gated behind an authorized_keys check + an
#     optional dead-man safety timer that auto-restores passwords unless you
#     explicitly commit
#   · "Re-enable password login" is always available as break-glass
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ─── Paths ────────────────────────────────────────────────────────────────────
LOG_DIR="/opt/grin/logs"
LOG_FILE="$LOG_DIR/grin_ssh_hardening_$(date +%Y%m%d_%H%M%S).log"
CONF_DIR="/opt/grin/conf"
BACKUP_DIR="$CONF_DIR/ssh_backups"
SSHD_CONFIG="/etc/ssh/sshd_config"
DROPIN_DIR="/etc/ssh/sshd_config.d"
# ⚠ The NUMBER matters, and it is the opposite of the usual convention.
# sshd uses the FIRST value it obtains for a keyword, and Include expands its
# glob in LEXICAL order — so a drop-in must sort EARLY to win, not late. The
# original 99- name lost to Ubuntu's own /etc/ssh/sshd_config.d/50-cloud-init.conf
# (`PasswordAuthentication yes`), which is read first: the file was written, the
# directive was ignored, and `sshd -t` was perfectly happy about it.
HARDENING_DROPIN="$DROPIN_DIR/00-grin-hardening.conf"
LEGACY_DROPIN="$DROPIN_DIR/99-grin-hardening.conf"
# Prefix used to park a conflicting directive in someone else's file so it can be
# put back verbatim on revert. Break-glass MUST undo these too.
DISABLED_MARK="#GRIN-DISABLED# "
AUTH_KEYS="/root/.ssh/authorized_keys"
POLICY_CONF="$CONF_DIR/ssh_hardening_policy.conf"
AUTOREVERT_PID="$CONF_DIR/ssh_autorevert.pid"
AUTOREVERT_SH="$CONF_DIR/ssh_autorevert.sh"
MARK_BEGIN="# >>> grin-toolkit ssh hardening >>>"
MARK_END="# <<< grin-toolkit ssh hardening <<<"
mkdir -p "$LOG_DIR" "$CONF_DIR" "$BACKUP_DIR"

# ─── Colors ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; DIM='\033[2m'; RESET='\033[0m'

# ─── Logging ──────────────────────────────────────────────────────────────────
log()     { echo "[$(date -u '+%Y-%m-%d %H:%M:%S UTC')] $*" >> "$LOG_FILE" 2>/dev/null || true; }
info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; log "[INFO]  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; log "[OK]    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; log "[WARN]  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*"; log "[ERROR] $*"; }

pause() { echo ""; echo "Press Enter to return to menu..."; read -r; }

confirm() {
    local prompt="$1"
    echo ""
    echo -ne "${BOLD}${YELLOW}▶ $prompt [y/N]: ${RESET}"
    local ans; read -r ans
    [[ "${ans,,}" == "y" ]]
}

# ─── Root guard ────────────────────────────────────────────────────────────────
if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
    error "This tool must run as root (it edits /etc/ssh and /root/.ssh)."
    exit 1
fi

if ! command -v ssh-keygen &>/dev/null; then
    error "ssh-keygen not found — install the openssh client/server first."
    exit 1
fi

# =============================================================================
# SSH service helpers
# =============================================================================
_ssh_service_reload() {
    systemctl reload ssh   2>/dev/null && return 0
    systemctl reload sshd  2>/dev/null && return 0
    service ssh reload     2>/dev/null && return 0
    service sshd reload    2>/dev/null && return 0
    return 1
}

# Effective config value via `sshd -T` (lower-cased keyword), with a grep fallback.
_ssh_effective() {
    local key="$1"
    sshd -T 2>/dev/null | awk -v k="${key,,}" 'tolower($1)==k {print $2; exit}'
}

# Same, but for list-valued keywords (AllowUsers, AllowGroups): every field.
_ssh_effective_all() {
    local key="$1"
    sshd -T 2>/dev/null | awk -v k="${key,,}"         'tolower($1)==k {for(i=2;i<=NF;i++) printf "%s%s", $i, (i<NF?" ":""); print ""; exit}'
}

_ssh_port() {
    local p; p="$(_ssh_effective port)"
    echo "${p:-22}"
}

_ssh_dropin_supported() {
    [[ -d "$DROPIN_DIR" ]] && \
    grep -Eq '^[[:space:]]*Include[[:space:]]+/etc/ssh/sshd_config\.d/\*\.conf' "$SSHD_CONFIG"
}

_ssh_backup_config() {
    local ts dest
    ts="$(date +%Y%m%d_%H%M%S)"
    dest="$BACKUP_DIR/sshd_config.$ts.bak"
    cp -a "$SSHD_CONFIG" "$dest" 2>/dev/null && log "Backed up $SSHD_CONFIG -> $dest"
    echo "$dest"
}

_ssh_remove_managed_block() {
    [[ -f "$SSHD_CONFIG" ]] || return 0
    sed -i "/$MARK_BEGIN/,/$MARK_END/d" "$SSHD_CONFIG" 2>/dev/null || true
}

_ssh_remove_hardening() {
    rm -f "$HARDENING_DROPIN" 2>/dev/null || true
    # Pre-2026-09-30 installs used a 99- name that lost the precedence fight.
    rm -f "$LEGACY_DROPIN" 2>/dev/null || true
    _ssh_remove_managed_block
    # Anything we commented out in someone else's file is part of the change and
    # must come back, or a rollback would leave passwords off.
    _ssh_restore_disabled_lines || true
}

# =============================================================================
# Which account are we installing keys FOR?
# Defaults to root, so every existing caller is unchanged; the admin-user wizard
# points these at the new account for the duration of one call.
# =============================================================================
_ssh_user_home() {
    local u="$1" h
    h="$(getent passwd "$u" 2>/dev/null | cut -d: -f6)"
    [[ -n "$h" ]] && { echo "$h"; return 0; }
    return 1
}
_ssh_keys_owner() { echo "${SSH_KEYS_OWNER:-root}"; }
_ssh_keys_file()  {
    if [[ -n "${SSH_KEYS_TARGET:-}" ]]; then echo "$SSH_KEYS_TARGET"; else echo "$AUTH_KEYS"; fi
}

# The sudo-capable group differs by distro family: Debian/Ubuntu `sudo`,
# Rocky/Alma `wheel`. Echo whichever exists (preferring one the box really has).
_ssh_sudo_group() {
    local g
    for g in sudo wheel; do
        getent group "$g" >/dev/null 2>&1 && { echo "$g"; return 0; }
    done
    return 1
}

# Read one key out of the policy file (ADMIN_USER / ROOT_LOGIN).
_ssh_policy_get() {
    [[ -r "$POLICY_CONF" ]] || return 1
    local v
    v="$(awk -F= -v k="$1" '$1==k{sub(/^[^=]*=/,""); gsub(/^"|"$/,""); print; exit}' "$POLICY_CONF" 2>/dev/null)"
    [[ -n "$v" ]] && { echo "$v"; return 0; }
    return 1
}
_ssh_policy_set() {
    local user="$1" rootlogin="$2"
    cat > "$POLICY_CONF" <<EOF
# Managed by Grin Node Toolkit (085_ssh_hardening.sh).
# Consumed by _ssh_apply_hardening to build the sshd drop-in. Editing this file
# changes nothing until hardening is re-applied.
ADMIN_USER=$user
ROOT_LOGIN=$rootlogin
EOF
    chmod 600 "$POLICY_CONF"
    log "Policy set: ADMIN_USER=$user ROOT_LOGIN=$rootlogin"
}

# =============================================================================
# Why did this line fail validation?  Echoes a human explanation + the fix.
# A bare "not a valid public key" leaves the operator with nowhere to go — and
# the single most common paste is the FINGERPRINT that ssh-keygen prints at the
# end of key generation, which looks key-shaped but is a hash, not a key.
# Sets _SSH_REJECT_SAFE=0 when the line must NOT be echoed back (private key).
# =============================================================================
_ssh_pubkey_reject_reason() {
    local line="$1"
    _SSH_REJECT_SAFE=1
    case "$line" in
        SHA256:*|MD5:*|[0-9]*" SHA256:"*|[0-9]*" MD5:"*)
            echo "that is the key FINGERPRINT (a hash), not the key. ssh-keygen prints it after generating — the key itself is in the .pub FILE." ;;
        *-----BEGIN*PRIVATE*KEY*|*"PuTTY-User-Key-File"*)
            _SSH_REJECT_SAFE=0
            echo "that is a PRIVATE key — never paste it anywhere. The public half is the matching .pub file (PuTTY: PuTTYgen ▸ 'Public key for pasting')." ;;
        *-----BEGIN*|*"BEGIN SSH2 PUBLIC KEY"*|*"Comment:"*)
            echo "that is a multi-line/RFC4716 key block. Convert it first: ssh-keygen -i -f key.pub" ;;
        ssh-*|ecdsa-*|sk-ssh-*|sk-ecdsa-*)
            echo "the type prefix is right but the body is malformed — the paste was probably truncated or line-wrapped. A public key is ONE single line." ;;
        AAAA*)
            echo "the base64 body is there but the leading type word is missing — the line must start with 'ssh-ed25519 ' (or 'ssh-rsa ')." ;;
        *)
            echo "no recognised key type at the start of the line. It must begin with ssh-ed25519, ssh-rsa, ecdsa-sha2-* or sk-*." ;;
    esac
}

# =============================================================================
# Key installation (shared by all 3 add methods)
# Reads candidate public-key lines from stdin; validates + dedupes into
# /root/.ssh/authorized_keys.
# =============================================================================
_ssh_install_keys() {
    local owner keyfile sshdir home
    owner="$(_ssh_keys_owner)"
    keyfile="$(_ssh_keys_file)"
    sshdir="$(dirname "$keyfile")"

    # StrictModes (sshd default) REFUSES a key when the home dir or ~/.ssh is
    # group/other-writable — a silent "key rejected" that looks like a bad key.
    if home="$(_ssh_user_home "$owner")"; then
        chmod go-w "$home" 2>/dev/null || true
    fi
    mkdir -p "$sshdir"   || { error "Cannot create $sshdir"; return 1; }
    touch "$keyfile"     || { error "Cannot write $keyfile"; return 1; }
    # Only reassign ownership for a NON-root target: /root/.ssh is already
    # root-owned, and a blanket -R there could touch a file we did not create.
    if [[ "$owner" != "root" ]]; then
        chown -R "$owner:$(id -gn "$owner" 2>/dev/null || echo "$owner")" "$sshdir"             || { error "Could not chown $sshdir to $owner"; return 1; }
    fi
    chmod 700 "$sshdir"
    chmod 600 "$keyfile"
    # SELinux (Rocky/Alma): a hand-made ~/.ssh has the wrong label and sshd
    # cannot read it. Relabel if the tooling is present.
    command -v restorecon &>/dev/null && restorecon -R "$sshdir" 2>/dev/null || true

    local installed=0 skipped=0 invalid=0 line tmp fp why
    while IFS= read -r line; do
        line="$(printf '%s' "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
        [[ -z "$line" || "$line" == \#* ]] && continue

        tmp="$(mktemp)"
        printf '%s\n' "$line" > "$tmp"
        if fp="$(ssh-keygen -l -f "$tmp" 2>/dev/null)"; then
            if grep -qxF "$line" "$keyfile"; then
                skipped=$((skipped + 1))
                info "Already present: $fp"
            else
                printf '%s\n' "$line" >> "$keyfile"
                installed=$((installed + 1))
                success "Installed: $fp"
            fi
        else
            invalid=$((invalid + 1))
            why="$(_ssh_pubkey_reject_reason "$line")"
            if [[ "${_SSH_REJECT_SAFE:-1}" -eq 1 ]]; then
                warn "Skipped — ${line:0:28}… : $why"
            else
                warn "Skipped one line (not echoed) — $why"
            fi
        fi
        rm -f "$tmp"
    done

    echo ""
    info "Summary for ${owner} — installed: $installed, already-present: $skipped, invalid: $invalid"
    if [[ $invalid -gt 0 && $installed -eq 0 && $skipped -eq 0 ]]; then
        echo ""
        echo -e "${BOLD}A valid line looks exactly like this${RESET} ${DIM}(one line, 3 fields, ~80 chars):${RESET}"
        echo -e "  ${DIM}ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO8k…q2Zr user@laptop${RESET}"
        echo -e "Print yours on the laptop and copy the ${BOLD}whole line${RESET}:"
        echo -e "  ${DIM}PowerShell : cat \$env:USERPROFILE\\.ssh\\id_ed25519.pub${RESET}"
        echo -e "  ${DIM}Linux/macOS: cat ~/.ssh/id_ed25519.pub${RESET}"
    fi
    [[ $installed -gt 0 || $skipped -gt 0 ]]
}

# =============================================================================
# 1) Add key — paste manually
# =============================================================================
add_key_paste() {
    clear
    echo -e "${BOLD}${CYAN}  Add public key — paste manually${RESET}  ${DIM}(account: $(_ssh_keys_owner))${RESET}"
    echo ""
    echo -e "${BOLD}Step 1 — on your laptop, PRINT the public key${RESET} ${DIM}(it is a file; ssh-keygen${RESET}"
    echo -e "${DIM}does not show it when it generates the pair):${RESET}"
    echo -e "  ${BOLD}Windows PowerShell:${RESET} ${DIM}cat \$env:USERPROFILE\\.ssh\\id_ed25519.pub${RESET}"
    echo -e "  ${BOLD}Windows CMD:${RESET}        ${DIM}type %USERPROFILE%\\.ssh\\id_ed25519.pub${RESET}"
    echo -e "  ${BOLD}Linux / macOS:${RESET}      ${DIM}cat ~/.ssh/id_ed25519.pub${RESET}"
    echo -e "  ${DIM}No key yet? Run ${RESET}${DIM}ssh-keygen -t ed25519${RESET}${DIM} first (Enter at every prompt;${RESET}"
    echo -e "  ${DIM}a passphrase is optional), then print the .pub file as above.${RESET}"
    echo ""
    echo -e "${BOLD}Step 2 — copy the WHOLE single line.${RESET} It looks like this:"
    echo -e "  ${DIM}ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO8k…q2Zr user@laptop${RESET}"
    echo -e "  ${YELLOW}NOT${RESET} the fingerprint ${DIM}SHA256:zrWgcir+…${RESET} that ssh-keygen printed — that is a"
    echo -e "  hash, not a key. ${YELLOW}NOT${RESET} the private key (the file with ${BOLD}no${RESET} .pub)."
    echo ""
    echo -e "Paste one or more PUBLIC key lines below. Finish with an ${BOLD}empty line${RESET}:"
    echo ""

    local lines="" l
    while IFS= read -r l; do
        [[ -z "$l" ]] && break
        lines+="$l"$'\n'
    done

    if [[ -z "${lines//[$'\n\t ']/}" ]]; then
        warn "Nothing pasted — no changes made."
        pause; return 0
    fi
    printf '%s' "$lines" | _ssh_install_keys || true
    pause
}

# =============================================================================
# 2) Add key — generate on server
# =============================================================================
add_key_generate() {
    clear
    echo -e "${BOLD}${CYAN}  Add public key — generate on server${RESET}"
    echo ""
    echo -e "${YELLOW}Note:${RESET} the safest keys are generated on YOUR OWN machine and"
    echo -e "imported. Generate-on-server is a convenience — the private key is"
    echo -e "shown here ${BOLD}once${RESET}; you must copy it to your laptop now."
    echo ""
    if ! confirm "Generate a new ed25519 key pair on this server?"; then
        info "Cancelled."; pause; return 0
    fi

    local ts kf owner ohome
    ts="$(date +%Y%m%d_%H%M%S)"
    owner="$(_ssh_keys_owner)"
    ohome="$(_ssh_user_home "$owner")" || ohome="/root"
    kf="$ohome/.ssh/grin_ed25519_$ts"
    mkdir -p "$ohome/.ssh"; chmod 700 "$ohome/.ssh"
    if ! ssh-keygen -t ed25519 -N "" -C "grin-toolkit-$ts" -f "$kf" >/dev/null 2>&1; then
        error "ssh-keygen failed."; pause; return 0
    fi
    success "Key pair generated: $kf{,.pub}"

    # Install the public half into authorized_keys.
    _ssh_install_keys < "$kf.pub" || true

    echo ""
    echo -e "${BOLD}${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${RED}  PRIVATE KEY — shown ONCE. Save it to your laptop NOW.${RESET}"
    echo -e "${BOLD}${RED}  Store it at ~/.ssh/grin_ed25519 and: chmod 600 ~/.ssh/grin_ed25519${RESET}"
    echo -e "${BOLD}${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
    cat "$kf"
    echo ""
    echo -e "${BOLD}Connect with:${RESET} ${DIM}ssh -i ~/.ssh/grin_ed25519 ${owner}@<server-ip> -p $(_ssh_port)${RESET}"
    echo ""

    if confirm "Have you saved the private key? Delete the server's private-key copy now (recommended)?"; then
        shred -u "$kf" 2>/dev/null || rm -f "$kf"
        success "Server private-key copy deleted ($kf). Public key stays in authorized_keys."
    else
        warn "Private key left on server at $kf — delete it once you've copied it."
    fi
    pause
}

# =============================================================================
# 3) Add key — fetch from URL (github username or raw URL)
# =============================================================================
add_key_url() {
    clear
    echo -e "${BOLD}${CYAN}  Add public key — fetch from URL${RESET}"
    echo ""
    echo -e "Enter a ${BOLD}GitHub username${RESET} (keys pulled from github.com/<user>.keys),"
    echo -e "or any ${BOLD}raw URL${RESET} that serves PUBLIC key lines"
    echo -e "(GitLab, or a self-hosted pubkey directory)."
    echo ""
    if ! command -v curl &>/dev/null; then
        error "curl not found — install curl or use paste instead."; pause; return 0
    fi
    echo -ne "${BOLD}GitHub username or URL: ${RESET}"
    local src url; read -r src
    src="$(printf '%s' "$src" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    if [[ -z "$src" ]]; then
        warn "Nothing entered."; pause; return 0
    fi
    if [[ "$src" == *"://"* ]]; then
        url="$src"
    else
        url="https://github.com/${src}.keys"
    fi
    info "Fetching $url ..."
    local body
    if ! body="$(curl -fsSL --max-time 20 "$url" 2>/dev/null)" || [[ -z "$body" ]]; then
        error "Could not fetch any key from $url"
        pause; return 0
    fi
    printf '%s\n' "$body" | _ssh_install_keys || true
    pause
}

# =============================================================================
# Add-key submenu
# =============================================================================
menu_add_key() {
    while true; do
        clear
        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo -e "${BOLD}${CYAN}  Add a public key to $(_ssh_keys_owner)${RESET}"
        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo ""
        echo -e "  ${DIM}Three independent ways to do the same thing — pick ONE, in any order.${RESET}"
        echo -e "  ${DIM}They are alternatives, not steps.${RESET}"
        echo ""
        echo -e "  ${GREEN}1${RESET})  Paste manually        ${DIM}paste your laptop's *.pub line${RESET}"
        echo -e "      ${DIM}Pick this if you already ran ssh-keygen on your laptop. ← usual choice${RESET}"
        echo -e "  ${GREEN}2${RESET})  Generate on server    ${DIM}ssh-keygen here, private key shown once${RESET}"
        echo -e "      ${DIM}Pick this only if you cannot run ssh-keygen locally; you must copy${RESET}"
        echo -e "      ${DIM}the private key off this box immediately (shown once, then deleted).${RESET}"
        echo -e "  ${GREEN}3${RESET})  Fetch from URL        ${DIM}github username or raw pubkey URL${RESET}"
        echo -e "      ${DIM}Pick this if your public key is already published (github.com/<user>.keys).${RESET}"
        echo ""
        echo -e "  ${DIM}0${RESET})  Back"
        echo ""
        echo -ne "${BOLD}Select [0-3]: ${RESET}"
        local c; read -r c
        case "$c" in
            1) add_key_paste    || true ;;
            2) add_key_generate || true ;;
            3) add_key_url      || true ;;
            0) break ;;
            *) warn "Invalid option."; sleep 1 ;;
        esac
    done
}

# =============================================================================
# List installed keys
# =============================================================================
list_keys() {
    clear
    echo -e "${BOLD}${CYAN}  Installed authorized keys (root)${RESET}"
    echo ""
    if [[ ! -s "$AUTH_KEYS" ]]; then
        warn "No keys installed yet ($AUTH_KEYS is empty or missing)."
        pause; return 0
    fi
    local n=0 line tmp
    while IFS= read -r line; do
        [[ -z "$line" || "$line" == \#* ]] && continue
        n=$((n + 1))
        tmp="$(mktemp)"; printf '%s\n' "$line" > "$tmp"
        printf "  ${BOLD}%2d)${RESET} %s\n" "$n" "$(ssh-keygen -l -f "$tmp" 2>/dev/null || echo '(unparseable line)')"
        rm -f "$tmp"
    done < "$AUTH_KEYS"
    echo ""
    info "$n key(s) in $AUTH_KEYS"
    pause
}

# =============================================================================
# Anti-lockout self-test — verify key login BEFORE disabling passwords
# =============================================================================

# How did THIS session authenticate? (publickey|password|keyboard-interactive|unknown)
# The strongest proof key auth works: if you're reading this over a key session,
# disabling passwords can't lock you out.
_ssh_current_session_auth() {
    if [[ -z "${SSH_CONNECTION:-}" ]]; then echo "unknown"; return 0; fi
    local cip cport line=""
    cip="$(awk '{print $1}' <<<"$SSH_CONNECTION")"
    cport="$(awk '{print $2}' <<<"$SSH_CONNECTION")"
    if command -v journalctl &>/dev/null; then
        line="$(journalctl _COMM=sshd -n 3000 --no-pager 2>/dev/null \
                | grep -E "Accepted .* from ${cip} port ${cport}( |$)" | tail -1 || true)"
    fi
    if [[ -z "$line" ]]; then
        local f
        for f in /var/log/auth.log /var/log/secure; do
            [[ -r "$f" ]] || continue
            line="$(grep -E "Accepted .* from ${cip} port ${cport}( |$)" "$f" 2>/dev/null | tail -1 || true)"
            [[ -n "$line" ]] && break
        done
    fi
    case "$line" in
        *"Accepted publickey"*)            echo "publickey" ;;
        *"Accepted password"*)             echo "password" ;;
        *"Accepted keyboard-interactive"*) echo "keyboard-interactive" ;;
        *)                                 echo "unknown" ;;
    esac
}

# Real end-to-end key-auth probe: SSH to ourselves using a PRIVATE key, with
# passwords forced off. Returns 0 only if the key alone authenticates.
# Needs the private key on disk (generate-on-server case, or a path the operator
# supplies for a one-off test). $1 = private key path, $2 = user (default root).
_ssh_loopback_test() {
    local key="$1" user="${2:-root}" port host
    [[ -r "$key" ]] || return 2
    command -v ssh &>/dev/null || return 2
    port="$(_ssh_port)"
    for host in 127.0.0.1 "$(awk '{print $3}' <<<"${SSH_CONNECTION:-}")"; do
        [[ -n "$host" ]] || continue
        if ssh -i "$key" -p "$port" \
                -o BatchMode=yes -o StrictHostKeyChecking=no \
                -o UserKnownHostsFile=/dev/null \
                -o PreferredAuthentications=publickey \
                -o PasswordAuthentication=no \
                -o ConnectTimeout=8 \
                "${user}@${host}" true 2>/dev/null; then
            return 0
        fi
    done
    return 1
}

# Pre-flight readiness check. Returns 0 if key login is CONFIRMED safe, else 1.
# When $1 == "quiet" it prints a one-line verdict only (used inside the disable
# flow); otherwise it prints the full report.
verify_key_login() {
    local quiet="${1:-}"
    [[ "$quiet" != "quiet" ]] && { clear; echo -e "${BOLD}${CYAN}  Verify key login (anti-lockout self-test)${RESET}"; echo ""; }

    local keys_ok=0 config_ok=0 pubkey_ok=0 confirmed=0
    local kcount=0
    [[ -s "$AUTH_KEYS" ]] && kcount="$(grep -cvE '^[[:space:]]*($|#)' "$AUTH_KEYS" 2>/dev/null || echo 0)"
    [[ "$kcount" -gt 0 ]] && keys_ok=1

    local meth; meth="$(_ssh_current_session_auth)"

    if [[ "$quiet" != "quiet" ]]; then
        # 1) keys present
        if [[ $keys_ok -eq 1 ]]; then success "authorized_keys: $kcount key(s) installed for root"
        else error "authorized_keys: empty — add a key first (option 1)"; fi

        # 2) perms / ownership
        local dperm fperm downer
        dperm="$(stat -c '%a' /root/.ssh 2>/dev/null || echo '?')"
        fperm="$(stat -c '%a' "$AUTH_KEYS" 2>/dev/null || echo '?')"
        downer="$(stat -c '%U' "$AUTH_KEYS" 2>/dev/null || echo '?')"
        if [[ "$dperm" == "700" && ( "$fperm" == "600" || "$fperm" == "644" ) && "$downer" == "root" ]]; then
            success "Permissions: ~/.ssh=$dperm authorized_keys=$fperm owner=$downer"
        else
            warn "Permissions look off: ~/.ssh=$dperm authorized_keys=$fperm owner=$downer (want 700/600 root)"
        fi
    fi

    # 3) sshd config valid
    if sshd -t 2>/tmp/grin_sshd_err; then
        config_ok=1
        [[ "$quiet" != "quiet" ]] && success "sshd config: valid (sshd -t)"
    else
        [[ "$quiet" != "quiet" ]] && { error "sshd config: INVALID — fix before hardening:"; sed 's/^/      /' /tmp/grin_sshd_err; }
    fi

    # 4) pubkey auth effective for root (honours Match blocks)
    local epub
    epub="$(sshd -T -C user=root 2>/dev/null | awk 'tolower($1)=="pubkeyauthentication"{print $2; exit}')"
    [[ -z "$epub" ]] && epub="$(_ssh_effective pubkeyauthentication)"
    [[ "$epub" == "yes" ]] && pubkey_ok=1
    if [[ "$quiet" != "quiet" ]]; then
        if [[ $pubkey_ok -eq 1 ]]; then success "PubkeyAuthentication: yes (effective for root)"
        else error "PubkeyAuthentication: ${epub:-unknown} — keys won't be accepted"; fi
    fi

    # 5) how the CURRENT session got in
    if [[ "$quiet" != "quiet" ]]; then
        case "$meth" in
            publickey) success "This session authenticated by: ${BOLD}publickey${RESET} ← key login already works" ;;
            password)  warn "This session authenticated by: ${BOLD}password${RESET} — not proof your key works yet" ;;
            keyboard-interactive) warn "This session authenticated by: keyboard-interactive (not pubkey)" ;;
            *)         warn "Could not determine how this session authenticated (no log match)" ;;
        esac
    fi

    # 6) optional real loopback probe with a private key we hold
    local loop_ok=0 priv=""
    priv="$(ls -1t /root/.ssh/grin_ed25519_* 2>/dev/null | grep -v '\.pub$' | head -1 || true)"
    if [[ "$quiet" != "quiet" ]]; then
        if [[ -n "$priv" ]]; then
            info "Loopback key-auth probe using $priv ..."
            if _ssh_loopback_test "$priv"; then loop_ok=1; success "Loopback login with key: SUCCESS"
            else warn "Loopback login with key: failed (server may not accept SSH on localhost — not conclusive)"; fi
        else
            echo -ne "${DIM}  Optional: path to a private key to test now (Enter to skip): ${RESET}"
            local p; read -r p
            if [[ -n "$p" ]]; then
                if _ssh_loopback_test "$p"; then loop_ok=1; success "Loopback login with key: SUCCESS"
                else warn "Loopback login with key: failed or key unreadable"; fi
            fi
        fi
    fi

    # Verdict: confirmed if you're already on a key session, OR a loopback key
    # login succeeded — and the static prerequisites hold.
    if [[ ( "$meth" == "publickey" || $loop_ok -eq 1 ) && $keys_ok -eq 1 && $config_ok -eq 1 && $pubkey_ok -eq 1 ]]; then
        confirmed=1
    fi

    if [[ "$quiet" != "quiet" ]]; then
        echo ""
        local port; port="$(_ssh_port)"
        local sip; sip="$(awk '{print $3}' <<<"${SSH_CONNECTION:-}")"
        if [[ $confirmed -eq 1 ]]; then
            echo -e "${BOLD}${GREEN}  VERDICT: READY — key login is confirmed working.${RESET}"
            echo -e "  Disabling passwords (option 4) is safe; you will not be locked out."
        else
            echo -e "${BOLD}${YELLOW}  VERDICT: NOT CONFIRMED — do NOT disable passwords yet.${RESET}"
            echo ""
            echo -e "  Make it green:"
            [[ $keys_ok -eq 0 ]]   && echo -e "   • add your public key (option 1)"
            [[ $pubkey_ok -eq 0 ]] && echo -e "   • enable PubkeyAuthentication / fix sshd config"
            if [[ "$meth" != "publickey" ]]; then
                echo -e "   • open a NEW terminal and log in with your key:"
                echo -e "       ${DIM}ssh root@${sip:-<server-ip>} -p $port${RESET}"
                echo -e "     then re-run this check — it should turn green."
            fi
            echo -e "  ${DIM}If unsure, use option 4's safety timer: it auto-restores passwords${RESET}"
            echo -e "  ${DIM}unless you confirm you can still get in.${RESET}"
        fi
        pause
    fi

    [[ $confirmed -eq 1 ]]
}

# =============================================================================
# Conflicting-directive detection and (reversible) resolution
# =============================================================================
# sshd keeps the FIRST value it obtains for a keyword. Include expands in
# lexical order, so /etc/ssh/sshd_config.d/50-cloud-init.conf beats a 99- file
# — and `sshd -t` passes, `systemctl reload` returns 0, and the directive is
# simply ignored. Writing the file is not applying the setting.
#
# Rather than model sshd's precedence, these helpers LIST every place a keyword
# is set, let the operator park the ones that are not ours, and then re-ask
# `sshd -T` — which is the only authority on what actually took effect.
#
# Parking is reversible by design: the line keeps its text behind
# $DISABLED_MARK, and _ssh_restore_disabled_lines puts it back verbatim. The
# dead-man timer and break-glass both call that, because a password directive
# left commented out in someone else's file would defeat the rollback.
# =============================================================================

# Every file sshd reads, in the order it reads them (main config first: the
# Include line is at the top on Debian/Ubuntu/Rocky, which is the case that
# matters here).
_ssh_config_files() {
    echo "$SSHD_CONFIG"
    [[ -d "$DROPIN_DIR" ]] || return 0
    local f
    while IFS= read -r f; do
        [[ -n "$f" ]] && echo "$f"
    done < <(find "$DROPIN_DIR" -maxdepth 1 -name '*.conf' -type f 2>/dev/null | LC_ALL=C sort)
}

# Active (uncommented) settings of a keyword: "file:line:text" per match.
# Lines inside a Match block are skipped — they are conditional, not the global
# value, and treating one as the culprit would send the operator after the wrong
# line entirely.
_ssh_keyword_sites() {
    local kw="$1" f
    while IFS= read -r f; do
        [[ -r "$f" ]] || continue
        awk -v kw="$(tr '[:upper:]' '[:lower:]' <<<"$kw")" -v file="$f" '
            { line=$0 }
            tolower($1)=="match" { inmatch=1; next }
            inmatch { next }
            tolower($1)==kw { printf "%s:%d:%s\n", file, NR, line }
        ' "$f" 2>/dev/null
    done < <(_ssh_config_files)
}

# Park one line (by number) behind the marker. The text is preserved exactly.
_ssh_disable_line() {
    local f="$1" n="$2"
    [[ -w "$f" ]] || { error "Not writable: $f"; return 1; }
    cp -a "$f" "$BACKUP_DIR/$(basename "$f").$(date +%Y%m%d_%H%M%S).bak" \
        || { error "Could not back up $f — refusing to edit it"; return 1; }
    sed -i "${n}s|^|${DISABLED_MARK}|" "$f" \
        || { error "Could not edit $f:$n"; return 1; }
    log "Parked $f:$n behind $DISABLED_MARK"
    return 0
}

# Put every parked line back, everywhere. Safe to call when there are none.
_ssh_restore_disabled_lines() {
    local f n=0
    while IFS= read -r f; do
        [[ -w "$f" ]] || continue
        if grep -q "^${DISABLED_MARK}" "$f" 2>/dev/null; then
            sed -i "s|^${DISABLED_MARK}||" "$f" || { error "Could not un-park lines in $f"; return 1; }
            n=$((n + 1))
            log "Restored parked lines in $f"
        fi
    done < <(_ssh_config_files)
    [[ $n -gt 0 ]] && info "Restored original directives in $n file(s)."
    return 0
}

# Show every setting of $1 and offer to park the ones that are not ours.
# Returns 0 if something was changed (worth re-verifying), 1 if not.
_ssh_resolve_conflicts() {
    local kw="$1" sites site f n txt changed=1
    sites="$(_ssh_keyword_sites "$kw")"
    if [[ -z "$sites" ]]; then
        info "No file sets $kw at all — nothing to resolve."
        return 1
    fi

    echo ""
    echo -e "${BOLD}Every active '$kw' setting sshd can see, in read order:${RESET}"
    echo ""
    while IFS= read -r site; do
        [[ -z "$site" ]] && continue
        f="${site%%:*}"; n="${site#*:}"; n="${n%%:*}"; txt="${site#*:*:}"
        if [[ "$f" == "$HARDENING_DROPIN" ]]; then
            echo -e "   ${GREEN}OURS${RESET}  $f:$n"
            echo -e "         ${DIM}$txt${RESET}"
        else
            echo -e "   ${YELLOW}OTHER${RESET} $f:$n"
            echo -e "         ${DIM}$txt${RESET}"
        fi
    done <<<"$sites"
    echo ""
    echo -e "${DIM}sshd uses the FIRST of these it reads — the main config first, then${RESET}"
    echo -e "${DIM}$DROPIN_DIR/*.conf in filename order. Ours is named${RESET}"
    echo -e "${DIM}$(basename "$HARDENING_DROPIN") so it sorts early, but a file in the main${RESET}"
    echo -e "${DIM}config above the Include line still wins.${RESET}"
    echo ""
    echo -e "The fix is to comment the OTHER lines out. The toolkit does it"
    echo -e "reversibly: the text is kept behind ${BOLD}${DISABLED_MARK}${RESET} and put back"
    echo -e "whenever hardening is rolled back (timer, break-glass, or option 6)."
    echo ""
    if ! confirm "Comment out the OTHER '$kw' line(s) and re-check?"; then
        info "Left them alone — nothing changed."
        return 1
    fi

    while IFS= read -r site; do
        [[ -z "$site" ]] && continue
        f="${site%%:*}"; n="${site#*:}"; n="${n%%:*}"
        [[ "$f" == "$HARDENING_DROPIN" ]] && continue
        if _ssh_disable_line "$f" "$n"; then
            success "Commented out $f:$n"
            changed=0
        fi
    done <<<"$sites"

    if [[ $changed -ne 0 ]]; then
        error "Nothing could be changed."
        return 1
    fi
    if ! sshd -t 2>/tmp/grin_sshd_err; then
        error "sshd config is now INVALID — undoing those edits:"
        sed 's/^/    /' /tmp/grin_sshd_err
        _ssh_restore_disabled_lines
        return 1
    fi
    _ssh_service_reload || { error "ssh reload failed after the edit."; return 1; }
    return 0
}

# =============================================================================
# Apply / revert the password-off hardening
# =============================================================================
# Build the directive list ONCE, from the policy file, so the drop-in, the
# in-place block, the dead-man revert and break-glass all agree. With no policy
# file the output is byte-identical to the pre-wizard behaviour (root by key).
_ssh_hardening_directives() {
    local rl admin
    rl="$(_ssh_policy_get ROOT_LOGIN || echo prohibit-password)"
    admin="$(_ssh_policy_get ADMIN_USER || true)"
    echo "PubkeyAuthentication yes"
    echo "PasswordAuthentication no"
    echo "KbdInteractiveAuthentication no"
    echo "PermitRootLogin $rl"
    # AllowUsers is only written when an admin user exists AND root is shut out;
    # otherwise an allow-list would be the one thing standing between the
    # operator and their own root session.
    if [[ -n "$admin" && "$rl" == "no" ]]; then
        echo "AllowUsers $admin"
    fi
}

_ssh_apply_hardening() {
    _ssh_backup_config >/dev/null
    # A leftover 99- file from an older toolkit would sit AFTER ours and shadow
    # nothing, but it is still a second managed file saying the same thing.
    rm -f "$LEGACY_DROPIN" 2>/dev/null || true
    if _ssh_dropin_supported; then
        {
            echo "# Managed by Grin Node Toolkit (085_ssh_hardening.sh) — do not edit by hand."
            _ssh_hardening_directives
        } > "$HARDENING_DROPIN" || { error "Cannot write $HARDENING_DROPIN"; return 1; }
        chmod 644 "$HARDENING_DROPIN"
        log "Wrote drop-in $HARDENING_DROPIN"
    else
        _ssh_remove_managed_block
        {
            echo ""
            echo "$MARK_BEGIN"
            _ssh_hardening_directives
            echo "$MARK_END"
        } >> "$SSHD_CONFIG"
        log "Appended managed block to $SSHD_CONFIG"
    fi

    if ! sshd -t 2>/tmp/grin_sshd_err; then
        error "sshd config validation FAILED — reverting, nothing applied:"
        sed 's/^/    /' /tmp/grin_sshd_err
        _ssh_remove_hardening
        return 1
    fi
    if ! _ssh_service_reload; then
        error "Could not reload the ssh service — reverting to be safe."
        _ssh_remove_hardening
        return 1
    fi
    return 0
}

# Did the drop-in actually TAKE?  sshd uses the FIRST value it obtains for most
# keywords, and some distros place `Include sshd_config.d/*.conf` at the BOTTOM
# of sshd_config — a drop-in there loses to anything set above it. `sshd -t`
# passes either way and `systemctl reload` returns 0, so the only honest check is
# to ask the running config what it resolved to. $1 = expected PermitRootLogin,
# $2 = admin user ("" to skip the allow-list check).
_SSH_FAILED_KEYS=()

_ssh_verify_effective() {
    local want_rl="$1" admin="${2:-}" ok=0
    local pw rl
    _SSH_FAILED_KEYS=()
    pw="$(_ssh_effective passwordauthentication)"
    rl="$(_ssh_effective permitrootlogin)"

    if [[ "$pw" == "no" ]]; then success "Effective PasswordAuthentication: no"
    else
        error "Effective PasswordAuthentication: ${pw:-unknown} — the setting did NOT take"
        _SSH_FAILED_KEYS+=("PasswordAuthentication"); ok=1
    fi

    if [[ "$rl" == "$want_rl" ]]; then success "Effective PermitRootLogin: $rl"
    else
        error "Effective PermitRootLogin: ${rl:-unknown} (wanted $want_rl) — did NOT take"
        _SSH_FAILED_KEYS+=("PermitRootLogin"); ok=1
    fi

    if [[ -n "$admin" ]]; then
        # Ask sshd what it resolves FOR THAT USER — this honours AllowUsers,
        # AllowGroups, DenyUsers and any Match block at once.
        if sshd -T -C "user=$admin" >/dev/null 2>&1; then
            success "sshd resolves a config for '$admin' (not blocked by an allow/deny rule)"
        else
            error "sshd -T -C user=$admin FAILED — '$admin' may be blocked from logging in"; ok=1
        fi
    fi

    if [[ $ok -ne 0 ]]; then
        echo ""
        warn "The directive IS in $HARDENING_DROPIN, but sshd kept an earlier value."
        warn "sshd uses the FIRST value it obtains, and Include reads"
        warn "$DROPIN_DIR/*.conf in FILENAME order — so a lower-numbered"
        warn "file wins. On Ubuntu that is usually 50-cloud-init.conf."
        local k
        if [[ ${#_SSH_FAILED_KEYS[@]} -gt 0 ]]; then
            for k in "${_SSH_FAILED_KEYS[@]}"; do
                echo ""
                warn "Every active '$k' line sshd can see:"
                _ssh_keyword_sites "$k" | sed 's/^/      /'
            done
        fi
        return 1
    fi
    return 0
}

# Post-apply gate: verify, and when a directive did not take, show exactly which
# file beat it and offer the reversible fix, then verify again. Loops until the
# config is right, the operator stops, or there is nothing left to try.
# Returns 0 only when everything resolved. $1 = expected PermitRootLogin,
# $2 = admin user ("" to skip the per-user check).
_ssh_postapply_gate() {
    local want_rl="$1" admin="${2:-}" k
    while true; do
        if _ssh_verify_effective "$want_rl" "$admin"; then
            return 0
        fi
        if [[ ${#_SSH_FAILED_KEYS[@]} -eq 0 ]]; then
            # Failed for a reason conflict-resolution cannot fix (e.g. the user
            # is blocked by an allow/deny rule we did not write).
            return 1
        fi
        echo ""
        echo -e "${BOLD}This is fixable${RESET} — the directive is written, but another file sets the"
        echo -e "same keyword earlier, and sshd keeps the first value it reads."
        echo ""
        echo -e "  ${BOLD}f${RESET}) show the conflicting lines and comment them out (reversible)"
        echo -e "  ${BOLD}q${RESET}) stop and roll the hardening back"
        echo -ne "${BOLD}Choose [f/q]: ${RESET}"
        local c
        if ! read -r c; then
            echo ""
            warn "No input available — rolling back."
            return 1
        fi
        [[ "${c,,}" != "f" ]] && return 1

        local progressed=1
        for k in "${_SSH_FAILED_KEYS[@]}"; do
            if _ssh_resolve_conflicts "$k"; then progressed=0; fi
        done
        if [[ $progressed -ne 0 ]]; then
            warn "Nothing was changed, so the result would be the same."
            return 1
        fi
        echo ""
        info "Re-checking what sshd resolves now ..."
    done
}

_ssh_revert_hardening() {
    _ssh_backup_config >/dev/null
    _ssh_remove_hardening
    if ! sshd -t 2>/tmp/grin_sshd_err; then
        error "sshd config invalid after revert — manual check needed:"
        sed 's/^/    /' /tmp/grin_sshd_err
        return 1
    fi
    _ssh_service_reload || { error "ssh reload failed."; return 1; }
    return 0
}

# =============================================================================
# Dead-man safety timer
# =============================================================================
_ssh_autorevert_active() {
    [[ -f "$AUTOREVERT_PID" ]] && kill -0 "$(cat "$AUTOREVERT_PID" 2>/dev/null)" 2>/dev/null
}

_ssh_schedule_autorevert() {
    local mins="$1"
    # Standalone by design: this must undo the change with no help from the
    # toolkit, so it repeats the removal inline rather than sourcing anything.
    # It has to undo ALL THREE parts of an apply — our drop-in, the in-place
    # marked block, and any directive we parked in another file — or the
    # "passwords come back on their own" promise is false.
    cat > "$AUTOREVERT_SH" <<EOF
#!/bin/bash
sleep $((mins * 60))
rm -f "$HARDENING_DROPIN" "$LEGACY_DROPIN" 2>/dev/null
sed -i "/$MARK_BEGIN/,/$MARK_END/d" "$SSHD_CONFIG" 2>/dev/null
for f in "$SSHD_CONFIG" "$DROPIN_DIR"/*.conf; do
    [ -f "\$f" ] || continue
    sed -i "s|^${DISABLED_MARK}||" "\$f" 2>/dev/null
done
if sshd -t 2>/dev/null; then
    systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || service ssh reload 2>/dev/null || service sshd reload 2>/dev/null
fi
rm -f "$AUTOREVERT_PID" "$AUTOREVERT_SH" 2>/dev/null
EOF
    chmod +x "$AUTOREVERT_SH"
    nohup bash "$AUTOREVERT_SH" >/dev/null 2>&1 &
    echo $! > "$AUTOREVERT_PID"
    log "Scheduled auto-revert in $mins min (pid $(cat "$AUTOREVERT_PID"))"
}

_ssh_cancel_autorevert() {
    if _ssh_autorevert_active; then
        kill "$(cat "$AUTOREVERT_PID" 2>/dev/null)" 2>/dev/null || true
    fi
    rm -f "$AUTOREVERT_PID" "$AUTOREVERT_SH" 2>/dev/null || true
}

# =============================================================================
# Disable password login (key-only)
# =============================================================================
disable_password_auth() {
    clear
    echo -e "${BOLD}${CYAN}  Disable password login (key-only root access)${RESET}"
    echo ""

    if [[ ! -s "$AUTH_KEYS" ]]; then
        error "No authorized keys installed — add a key first (option 1)."
        error "Disabling passwords now would LOCK YOU OUT."
        pause; return 0
    fi

    local kcount
    kcount="$(grep -cvE '^[[:space:]]*($|#)' "$AUTH_KEYS" 2>/dev/null || echo 0)"
    info "$kcount key(s) currently authorized for root."

    # A policy left by the guided setup makes this option do MORE than its name
    # says — surface it rather than silently shutting root out of SSH.
    if [[ "$(_ssh_policy_get ROOT_LOGIN || echo prohibit-password)" == "no" ]]; then
        echo ""
        warn "A stored policy from the guided setup is in effect: applying here will"
        warn "ALSO set PermitRootLogin no (admin user: $(_ssh_policy_get ADMIN_USER || echo none))."
        warn "Prefer the wizard (W) for its proof gates; option 6 can clear the policy."
    fi

    # Anti-lockout pre-flight — surface the verdict before any change.
    if verify_key_login quiet; then
        success "Self-test: key login is CONFIRMED working (this session is key-authenticated)."
    else
        local _m; _m="$(_ssh_current_session_auth)"
        warn "Self-test: key login NOT confirmed (current session: ${_m})."
        warn "Run option 3 (Verify key login) for details — or use the safety timer below."
    fi

    # Firewall sanity — is the SSH port reachable?
    local port; port="$(_ssh_port)"
    if command -v ufw &>/dev/null && ufw status 2>/dev/null | grep -qi '^Status: active'; then
        if ufw status 2>/dev/null | grep -qE "(^|[[:space:]])$port(/tcp)?[[:space:]]"; then
            info "UFW: port $port appears allowed."
        else
            warn "UFW is active but no explicit rule for SSH port $port was found."
            warn "Make sure you can still reach the server on port $port."
        fi
    fi

    echo ""
    echo -e "${BOLD}${YELLOW}IMPORTANT — verify key login BEFORE relying on this.${RESET}"
    echo -e "Open a ${BOLD}second${RESET} terminal and confirm: ${DIM}ssh root@<server-ip> -p $port${RESET}"
    echo -e "logs in using your key (no password prompt)."
    echo ""
    echo -e "Two ways to proceed safely:"
    echo -e "  ${BOLD}A)${RESET} Safety timer — apply now, passwords auto-restore in N minutes"
    echo -e "     unless you commit with option 5. Best if you haven't tested yet."
    echo -e "  ${BOLD}B)${RESET} Apply permanently — only if you've ALREADY confirmed key login."
    echo ""
    echo -ne "${BOLD}Choose [A/b]: ${RESET}"
    local mode; read -r mode
    mode="${mode:-A}"

    if [[ "${mode,,}" == "b" ]]; then
        if ! confirm "Confirm: you have ALREADY logged in with your key in another session?"; then
            info "Aborted — nothing changed."; pause; return 0
        fi
        if _ssh_apply_hardening; then
            echo ""
            info "Checking what sshd actually resolved (not just what we wrote) ..."
            if _ssh_postapply_gate "$(_ssh_policy_get ROOT_LOGIN || echo prohibit-password)" ""; then
                _ssh_cancel_autorevert
                success "Password authentication DISABLED. Login is key-only now."
            else
                warn "The change did not take effect — rolling it back rather than"
                warn "leaving you in a half-applied state."
                _ssh_revert_hardening || error "Rollback FAILED — fix $SSHD_CONFIG by hand NOW, in this session."
            fi
        else
            error "Hardening not applied (see above). Passwords remain enabled."
        fi
        pause; return 0
    fi

    # Mode A — dead-man safety timer
    echo -ne "${BOLD}Auto-restore passwords after how many minutes? [5]: ${RESET}"
    local mins; read -r mins
    mins="${mins:-5}"
    if ! [[ "$mins" =~ ^[0-9]+$ ]] || [[ "$mins" -lt 1 ]]; then mins=5; fi

    if ! confirm "Apply key-only login now with a ${mins}-minute safety timer?"; then
        info "Aborted — nothing changed."; pause; return 0
    fi

    if _ssh_apply_hardening; then
        echo ""
        info "Checking what sshd actually resolved (not just what we wrote) ..."
        if ! _ssh_postapply_gate "$(_ssh_policy_get ROOT_LOGIN || echo prohibit-password)" ""; then
            warn "The change did not take effect — rolling it back. Nothing is half-applied,"
            warn "and no timer was armed."
            _ssh_revert_hardening || error "Rollback FAILED — fix $SSHD_CONFIG by hand NOW, in this session."
            pause; return 0
        fi
        _ssh_cancel_autorevert      # clear any previous timer
        _ssh_schedule_autorevert "$mins"
        echo ""
        success "Password login DISABLED with a ${mins}-minute safety timer."
        echo ""
        echo -e "${BOLD}Now, in another terminal:${RESET} ${DIM}ssh root@<server-ip> -p $port${RESET}"
        echo -e "  • If key login works  → return here and run ${BOLD}option 5${RESET} to make it permanent."
        echo -e "  • If you get locked out → do nothing; passwords auto-restore in ${mins} min."
    else
        error "Hardening not applied (see above). Passwords remain enabled."
    fi
    pause
}

# =============================================================================
# Commit — cancel the safety timer, keep key-only login
# =============================================================================
commit_hardening() {
    clear
    echo -e "${BOLD}${CYAN}  Make key-only login permanent${RESET}"
    echo ""
    if [[ "$(_ssh_effective passwordauthentication)" != "no" ]]; then
        warn "Password authentication is currently ENABLED — nothing to commit."
        warn "Run option 4 first to disable it."
        pause; return 0
    fi
    if _ssh_autorevert_active; then
        if confirm "Key login confirmed working — cancel the safety timer and keep key-only login?"; then
            _ssh_cancel_autorevert
            success "Safety timer cancelled. Key-only root login is now permanent."
        else
            info "Left the safety timer running."
        fi
    else
        info "No safety timer is running — key-only login is already permanent."
    fi
    pause
}

# =============================================================================
# Re-enable password login (rollback / break-glass)
# =============================================================================
enable_password_auth() {
    clear
    echo -e "${BOLD}${CYAN}  Re-enable password login (rollback)${RESET}"
    echo ""
    if ! confirm "Re-enable SSH password authentication for root?"; then
        info "Cancelled."; pause; return 0
    fi
    _ssh_cancel_autorevert
    if _ssh_revert_hardening; then
        success "Password authentication RE-ENABLED (toolkit hardening removed)."
        info "Distro defaults now apply. Your installed keys still work too."
        # The whole drop-in went, so PermitRootLogin/AllowUsers are back to the
        # distro default too — but the POLICY file survives and option 4 would
        # re-apply it. Say so: a silent re-lock is the surprise here.
        if [[ "$(_ssh_policy_get ROOT_LOGIN || echo prohibit-password)" == "no" ]]; then
            echo ""
            warn "Direct root SSH is available again — but the stored policy still says"
            warn "ROOT_LOGIN=no, ADMIN_USER=$(_ssh_policy_get ADMIN_USER || echo '(none)')."
            warn "Option 4 (or the wizard) would re-apply it."
            if confirm "Forget the stored policy, so future hardening only turns passwords off?"; then
                rm -f "$POLICY_CONF" && success "Policy cleared."
            else
                info "Policy kept."
            fi
        fi
    else
        error "Revert ran into a problem — check $SSHD_CONFIG and run 'sshd -t' manually."
    fi
    pause
}

# =============================================================================
# Status & audit
# =============================================================================
ssh_status() {
    clear
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${CYAN}  SSH status & audit${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""

    local port pw pubkey rootlogin
    port="$(_ssh_port)"
    pw="$(_ssh_effective passwordauthentication)"
    pubkey="$(_ssh_effective pubkeyauthentication)"
    rootlogin="$(_ssh_effective permitrootlogin)"

    printf "  ${BOLD}%-26s${RESET} %s\n" "SSH port:" "$port"
    printf "  ${BOLD}%-26s${RESET} %s\n" "PubkeyAuthentication:" "${pubkey:-unknown}"

    local pw_col="$pw"
    [[ "$pw" == "no"  ]] && pw_col="${GREEN}no  (key-only)${RESET}"
    [[ "$pw" == "yes" ]] && pw_col="${YELLOW}yes (passwords allowed)${RESET}"
    printf "  ${BOLD}%-26s${RESET} %b\n" "PasswordAuthentication:" "${pw_col:-unknown}"

    local rl_col="$rootlogin"
    [[ "$rootlogin" == "yes" ]] && rl_col="${YELLOW}yes${RESET}"
    [[ "$rootlogin" == "prohibit-password" ]] && rl_col="${GREEN}prohibit-password${RESET}"
    [[ "$rootlogin" == "no" ]] && rl_col="${RED}no (root SSH blocked)${RESET}"
    printf "  ${BOLD}%-26s${RESET} %b\n" "PermitRootLogin:" "${rl_col:-unknown}"

    local kcount=0
    [[ -s "$AUTH_KEYS" ]] && kcount="$(grep -cvE '^[[:space:]]*($|#)' "$AUTH_KEYS" 2>/dev/null || echo 0)"
    printf "  ${BOLD}%-26s${RESET} %s\n" "Authorized keys (root):" "$kcount"
    printf "  ${BOLD}%-26s${RESET} %s\n" "AllowUsers (effective):" "$(_ssh_effective_all allowusers || true)"

    # Admin accounts from the guided setup: key count + whether sudo really
    # grants root (asked of sudo itself, not guessed from group membership).
    local pol_users pu ph pk sudo_txt
    if pol_users="$(_ssh_policy_get ADMIN_USER)"; then
        for pu in $pol_users; do
            pk=0
            if ph="$(_ssh_user_home "$pu" 2>/dev/null)"; then
                if [[ -s "$ph/.ssh/authorized_keys" ]]; then
                    pk="$(grep -cvE '^[[:space:]]*($|#)' "$ph/.ssh/authorized_keys" 2>/dev/null || echo 0)"
                fi
            fi
            if _wz_sudo_ok "$pu"; then sudo_txt="${GREEN}sudo→root OK${RESET}"
            else sudo_txt="${RED}NO sudo→root${RESET}"; fi
            printf "  ${BOLD}%-26s${RESET} %b\n" "Admin user '$pu':" "$pk key(s), $sudo_txt"
        done
    fi

    if _ssh_dropin_supported; then
        printf "  ${BOLD}%-26s${RESET} %s\n" "Config method:" "drop-in ($DROPIN_DIR)"
    else
        printf "  ${BOLD}%-26s${RESET} %s\n" "Config method:" "managed block in $SSHD_CONFIG"
    fi

    # Duplicate definitions are the trap that makes a written directive silently
    # not apply, so name them here too — this screen is the "check your work" step.
    local dup_kw dup_n dup_txt=""
    for dup_kw in PasswordAuthentication PermitRootLogin; do
        dup_n="$(_ssh_keyword_sites "$dup_kw" | wc -l | tr -d ' ')"
        [[ "${dup_n:-0}" -gt 1 ]] && dup_txt+="$dup_kw ($dup_n files) "
    done
    if [[ -n "$dup_txt" ]]; then
        printf "  ${BOLD}%-26s${RESET} %b\n" "Duplicate directives:" "${YELLOW}${dup_txt}${RESET}"
        echo -e "  ${DIM}   sshd keeps the FIRST it reads — run option 4 or the wizard to see${RESET}"
        echo -e "  ${DIM}   which file wins and comment the loser out.${RESET}"
    fi

    if _ssh_autorevert_active; then
        printf "  ${BOLD}%-26s${RESET} %b\n" "Safety timer:" "${YELLOW}ARMED — passwords will auto-restore; commit with option 5${RESET}"
    else
        printf "  ${BOLD}%-26s${RESET} %s\n" "Safety timer:" "none"
    fi

    # ── Firewall view for the SSH port ─────────────────────────────────────────
    echo ""
    echo -e "${BOLD}Firewall (SSH port $port):${RESET}"
    if command -v ufw &>/dev/null; then
        local ufw_stat; ufw_stat="$(ufw status 2>/dev/null | head -1 || echo unknown)"
        echo -e "  UFW: $ufw_stat"
        ufw status 2>/dev/null | grep -E "(^|[[:space:]])$port(/tcp)?[[:space:]]" \
            | sed 's/^/    /' || echo -e "    ${DIM}no explicit rule for port $port${RESET}"
    elif command -v iptables &>/dev/null; then
        iptables -L INPUT -n 2>/dev/null | grep -E "dpt:$port(\b|$)" \
            | sed 's/^/    /' || echo -e "    ${DIM}no iptables rule referencing port $port${RESET}"
    else
        echo -e "    ${DIM}neither ufw nor iptables found${RESET}"
    fi

    echo ""
    echo -e "  ${DIM}Recommendation: add a key (option 1), run Verify (option 3) until it${RESET}"
    echo -e "  ${DIM}reads READY, then disable passwords (option 4) with the safety timer.${RESET}"
    pause
}

# =============================================================================
# How to connect with your key (remote-tool walkthrough for new users)
# =============================================================================
connect_help() {
    clear
    echo -e "${BOLD}${CYAN}  Connect to this server with your private key${RESET}"
    echo ""

    local port ip
    port="$(_ssh_port)"
    # Public IP this session came in on, falling back to a best-effort lookup.
    ip="$(awk '{print $3}' <<<"${SSH_CONNECTION:-}")"
    [[ -z "$ip" ]] && ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
    [[ -z "$ip" ]] && ip="<server-ip>"

    # Once the guided setup has run, root cannot log in at all — printing
    # root@ here would hand the operator a line that is guaranteed to fail.
    local login="root" rl
    rl="$(_ssh_effective permitrootlogin)"
    if [[ "$rl" == "no" ]]; then
        login="$(_ssh_policy_get ADMIN_USER | awk '{print $1}')"
        [[ -z "$login" ]] && login="<your-admin-user>"
    fi

    echo -e "Your server: ${BOLD}${login}@${ip}${RESET}   SSH port: ${BOLD}${port}${RESET}"
    if [[ "$rl" == "no" ]]; then
        echo -e "${YELLOW}Direct root login is disabled on this box${RESET} — log in as ${BOLD}${login}${RESET}"
        echo -e "and then run ${BOLD}sudo -i${RESET} for a root shell."
    fi
    echo -e "${DIM}You connect with the PRIVATE key that matches a public key installed here${RESET}"
    echo -e "${DIM}(option 1). Keep the private key on your laptop — never upload it.${RESET}"
    echo ""

    echo -e "${BOLD}${GREEN}1) Windows${RESET} ${DIM}— built-in OpenSSH (PowerShell or CMD, no PuTTY needed)${RESET}"
    echo -e "   ${DIM}Private key lives at %USERPROFILE%\\.ssh\\id_ed25519${RESET}"
    echo -e "   ${BOLD}ssh -i %USERPROFILE%\\.ssh\\id_ed25519 ${login}@${ip} -p ${port}${RESET}"
    echo -e "   ${DIM}If you get a 'permissions too open' / 'bad permissions' error:${RESET}"
    echo -e "   ${DIM}icacls \"%USERPROFILE%\\.ssh\\id_ed25519\" /inheritance:r /grant:r \"%USERNAME%:R\"${RESET}"
    echo -e "   ${DIM}Prefer a GUI? PuTTY needs the key converted to .ppk with PuTTYgen${RESET}"
    echo -e "   ${DIM}(Load your id_ed25519 → Save private key), then point PuTTY at the .ppk.${RESET}"
    echo ""

    echo -e "${BOLD}${GREEN}2) Linux / macOS${RESET} ${DIM}— built-in OpenSSH terminal${RESET}"
    echo -e "   ${BOLD}chmod 600 ~/.ssh/id_ed25519${RESET}   ${DIM}# once, so ssh accepts the key${RESET}"
    echo -e "   ${BOLD}ssh -i ~/.ssh/id_ed25519 ${login}@${ip} -p ${port}${RESET}"
    echo ""

    echo -e "${BOLD}${GREEN}3) Save it once${RESET} ${DIM}— so you can just type 'ssh grin-vps'${RESET}"
    echo -e "   ${DIM}Add to ~/.ssh/config (Windows: %USERPROFILE%\\.ssh\\\\config):${RESET}"
    echo -e "     ${DIM}Host grin-vps${RESET}"
    echo -e "     ${DIM}    HostName ${ip}${RESET}"
    echo -e "     ${DIM}    User ${login}${RESET}"
    echo -e "     ${DIM}    Port ${port}${RESET}"
    echo -e "     ${DIM}    IdentityFile ~/.ssh/id_ed25519${RESET}"
    echo -e "   ${DIM}Then connect with just: ${BOLD}ssh grin-vps${RESET}"
    echo ""

    echo -e "${BOLD}${GREEN}4) GUI clients${RESET} ${DIM}— Remote Desktop Manager, MobaXterm, WinSCP, Termius, PuTTY${RESET}"
    echo -e "   ${BOLD}${YELLOW}The key field wants the PRIVATE key — NOT the .pub file.${RESET}"
    echo -e "   ${GREEN}correct${RESET}  ${BOLD}%USERPROFILE%\\.ssh\\id_ed25519${RESET}       ${DIM}(no extension)${RESET}"
    echo -e "   ${RED}wrong${RESET}    ${DIM}%USERPROFILE%\\.ssh\\id_ed25519.pub   (that copy lives HERE already)${RESET}"
    echo -e "   ${DIM}The .pub half is what you installed on the server. Your client proves who${RESET}"
    echo -e "   ${DIM}it is by SIGNING with the private half, so handing it the .pub gives it${RESET}"
    echo -e "   ${DIM}nothing to sign with — the server never sees a signature and refuses.${RESET}"
    echo -e "   ${DIM}Labels vary: 'Private key', 'Identity file', 'Key file', 'Certificate'.${RESET}"
    echo ""
    echo -e "   ${BOLD}Still refused after pointing at the private key?${RESET}"
    echo -e "   ${DIM}· Clients built on PuTTY (and PuTTY itself) cannot read OpenSSH's format.${RESET}"
    echo -e "   ${DIM}  If the file starts '-----BEGIN OPENSSH PRIVATE KEY-----', convert it:${RESET}"
    echo -e "   ${DIM}  PuTTYgen ▸ Load (set filter to All Files) ▸ Save private key ▸ .ppk,${RESET}"
    echo -e "   ${DIM}  then point the client at the .ppk. Keep the original.${RESET}"
    echo -e "   ${DIM}· If the key has a passphrase, it goes in the client's passphrase field —${RESET}"
    echo -e "   ${DIM}  not the account-password field. Many clients silently try the password.${RESET}"
    echo -e "   ${DIM}· Check the USERNAME field matches an account allowed here (see above).${RESET}"
    echo -e "   ${DIM}· Make sure it is an SSH session type, not RDP/VNC/Telnet.${RESET}"
    echo ""
    echo -e "   ${BOLD}Prove which key the client should use${RESET} ${DIM}— compare fingerprints:${RESET}"
    echo -e "   ${DIM}  laptop: ssh-keygen -lf \$env:USERPROFILE\\.ssh\\id_ed25519${RESET}"
    echo -e "   ${DIM}  server: this tool's option 2 lists every installed key's fingerprint.${RESET}"
    echo -e "   ${DIM}  They must match. ssh-keygen -lf reads either half of a pair.${RESET}"
    echo ""
    echo -e "${YELLOW}Tips${RESET}"
    echo -e "  ${DIM}· First connect prints a host-key fingerprint — type 'yes' to trust it.${RESET}"
    echo -e "  ${DIM}· 'Permission denied (publickey)' has two usual causes: the client was${RESET}"
    echo -e "  ${DIM}  given the .pub file instead of the private key (see 4), or the matching${RESET}"
    echo -e "  ${DIM}  public key is not installed here — add it with option 1, list with 2.${RESET}"
    echo -e "  ${DIM}· Test the key BEFORE disabling passwords (option 4). Verify with option 3.${RESET}"
    echo ""
    pause
}

# =============================================================================
# GUIDED SETUP WIZARD — "log in as a normal user, sudo to root"
# =============================================================================
# The end state:
#     laptop key ──ssh──▶ user x  ──sudo -i──▶ root
#     root is NOT reachable over SSH; passwords are NOT accepted over SSH.
#
# The order below is the whole point of the wizard: every step that could lock
# you out is gated on PROOF that the next way in already works. Nothing touches
# sshd until the new account has been shown to log in by key AND to reach root.
#
# Two proofs are deliberately evidence-based, not self-declared:
#   · key login  — an "Accepted publickey for <user>" line in the SSH log, or a
#                  real loopback SSH using a private key we hold
#   · sudo       — `sudo -l -U <user>` (root can ask this without the password)
# A wizard that accepts "yes I tested it" is how people lock themselves out.
# =============================================================================

_wz_step() {
    echo ""
    echo -e "${BOLD}${CYAN}━━━ Step $1/$2 — $3 ${RESET}"
    echo ""
}

_wz_valid_username() {
    # Conservative: POSIX portable set, must start with a letter, <=32 chars.
    [[ "$1" =~ ^[a-z][a-z0-9_-]{0,31}$ ]]
}

# Human (non-system) accounts with a real login shell.
_wz_human_users() {
    getent passwd | awk -F: '$3>=1000 && $3<65534 && $7 !~ /(nologin|false)$/ {print $1}'
}

# Evidence of a successful PUBLIC-KEY login by $1, ever, from the SSH log.
# Echoes the matching line; returns 1 when there is none.
_wz_key_login_seen() {
    local u="$1" line="" f
    if command -v journalctl &>/dev/null; then
        line="$(journalctl _COMM=sshd --no-pager 2>/dev/null \
                | grep -E "Accepted publickey for ${u} " | tail -1 || true)"
    fi
    if [[ -z "$line" ]]; then
        for f in /var/log/auth.log /var/log/secure; do
            [[ -r "$f" ]] || continue
            line="$(grep -E "Accepted publickey for ${u} " "$f" 2>/dev/null | tail -1 || true)"
            [[ -n "$line" ]] && break
        done
    fi
    [[ -n "$line" ]] || return 1
    echo "$line"
}

# Can $1 reach root through sudo?  `sudo -l -U <user>` answers as root, with no
# knowledge of the user's password, and honours the real sudoers rules (group
# membership, NOPASSWD, per-command limits) instead of guessing from groups.
_wz_sudo_ok() {
    local u="$1" out
    command -v sudo &>/dev/null || return 2
    out="$(sudo -l -U "$u" 2>/dev/null)" || return 1
    grep -qE '\(ALL(\s*:\s*ALL)?\)\s+(NOPASSWD:\s*)?ALL' <<<"$out"
}

# A usable password is REQUIRED: sudo asks for the *user's own* password, so an
# account created with no password (or a locked one) can log in by key and then
# be unable to become root at all. `passwd -S` field 2: P usable, NP none, L locked.
_wz_password_state() {
    local st
    st="$(passwd -S "$1" 2>/dev/null | awk '{print $2}')"
    echo "${st:-unknown}"
}

_wz_set_password() {
    local u="$1" tries=0
    while [[ $tries -lt 3 ]]; do
        tries=$((tries + 1))
        echo -e "${DIM}  (typed straight into passwd — the toolkit never sees or logs it)${RESET}"
        if passwd "$u"; then
            [[ "$(_wz_password_state "$u")" == "P" ]] && { success "Password set for $u."; return 0; }
            warn "Password still not usable for $u — the account may be locked."
            usermod -U "$u" 2>/dev/null || true
            [[ "$(_wz_password_state "$u")" == "P" ]] && { success "Account unlocked; password usable."; return 0; }
        fi
        warn "passwd did not complete (attempt $tries of 3)."
    done
    return 1
}

# Optional convenience step: a group that owns the backup dir, so files move in
# and out with plain scp/sftp and NO sudo in the transfer path.
_wz_transfer_group() {
    local u="$1" grp="grinops" dir="/opt/grin/backups"
    groupadd -f "$grp" || { error "groupadd $grp failed"; return 1; }
    usermod -aG "$grp" "$u" || { error "Could not add $u to $grp"; return 1; }
    if [[ -d "$dir" ]]; then
        chgrp -R "$grp" "$dir" || { error "chgrp on $dir failed"; return 1; }
        chmod -R g+rX "$dir"   || { error "chmod on $dir failed"; return 1; }
        chmod g+s "$dir"       || { error "setgid on $dir failed"; return 1; }
        success "$dir is now group-readable by '$grp' (setgid: new files inherit it)."
        echo -e "  ${DIM}Pull a backup from your laptop with no sudo at all:${RESET}"
        echo -e "    ${DIM}scp ${u}@<server-ip>:$dir/'*.tar.gz*' .${RESET}"
    else
        info "$dir does not exist yet (089 Backup creates it) — group '$grp' is ready for when it does."
    fi
    warn "Group membership applies at NEXT login: $u must log out and back in."
    return 0
}

wizard_admin_user() {
    local TOTAL=7
    clear
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${CYAN}  GUIDED SETUP — key ▸ normal user ▸ sudo ▸ root${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
    echo -e "  This walks the whole job in the only safe order. At the end:"
    echo ""
    echo -e "    ${BOLD}your laptop key${RESET} ──ssh──▶ ${BOLD}user you name${RESET} ──${BOLD}sudo -i${RESET}──▶ ${BOLD}root${RESET}"
    echo ""
    echo -e "    • SSH passwords: ${BOLD}off${RESET}          • direct root SSH: ${BOLD}off${RESET}"
    echo -e "    • the new user's own password is kept — ${BOLD}sudo needs it${RESET}"
    echo ""
    echo -e "  ${DIM}Steps 1–5 change users and keys but NOT sshd, so they cannot lock${RESET}"
    echo -e "  ${DIM}you out. Step 7 is the only one that touches SSH, and it refuses to${RESET}"
    echo -e "  ${DIM}run until step 6 has PROVEN the new way in works.${RESET}"
    echo ""
    echo -e "  ${YELLOW}Keep this session open until the very end.${RESET} It is your fallback."
    echo ""
    if ! confirm "Start the guided setup?"; then info "Cancelled — nothing changed."; pause; return 0; fi

    # ── Step 1 — name the account ────────────────────────────────────────────
    local user
    while true; do
        _wz_step 1 $TOTAL "Name the admin user"
        echo -e "Lowercase letters, digits, - and _ ; must start with a letter."
        echo -e "${DIM}Avoid 'admin' and 'grin' — pick something not in a bot's word list.${RESET}"
        echo ""
        echo -ne "${BOLD}Username (blank to cancel): ${RESET}"
        read -r user
        [[ -z "$user" ]] && { info "Cancelled — nothing changed."; pause; return 0; }
        if ! _wz_valid_username "$user"; then
            warn "'$user' is not a valid Linux username."; continue
        fi
        if [[ "$user" == "root" ]]; then
            warn "That is root — the point of this wizard is to stop using it over SSH."; continue
        fi
        local prev
        if prev="$(_ssh_policy_get ADMIN_USER)" && [[ " $prev " != *" $user "* ]]; then
            echo ""
            warn "A stored policy already names: $prev"
            warn "Finishing this run REPLACES it with '$user'. Step 7 will ask whether"
            warn "$prev keeps SSH access."
        fi
        if id -u "$user" &>/dev/null; then
            info "User '$user' already exists — the wizard will adopt it, not recreate it."
            confirm "Use the existing account '$user'?" && break
            continue
        fi
        if ! confirm "Create new user '$user'?"; then continue; fi
        if useradd -m -s /bin/bash "$user"; then
            success "Created '$user' with home $(_ssh_user_home "$user")."
            break
        else
            error "useradd failed for '$user'."; pause; return 1
        fi
    done

    # ── Step 2 — password (for sudo, not for SSH) ─────────────────────────────
    _wz_step 2 $TOTAL "Set the account password (this is what sudo will ask for)"
    local pstate; pstate="$(_wz_password_state "$user")"
    echo -e "SSH will not accept this password — passwords get turned off in step 7."
    echo -e "It exists so ${BOLD}sudo${RESET} can ask for it. ${BOLD}An account with no password"
    echo -e "cannot sudo at all${RESET}, which is the classic way this setup half-works."
    echo -e "  ${DIM}Current state of '$user': $pstate  (P=usable, NP=none, L=locked)${RESET}"
    echo ""
    if [[ "$pstate" == "P" ]]; then
        if confirm "'$user' already has a usable password. Change it anyway?"; then
            _wz_set_password "$user" || { error "Could not set a password — stopping here."; pause; return 1; }
        else
            info "Keeping the existing password."
        fi
    else
        if ! _wz_set_password "$user"; then
            error "Could not set a usable password for '$user' — stopping."
            error "Without one, '$user' could not reach root. Nothing was changed in sshd."
            pause; return 1
        fi
    fi

    # ── Step 3 — sudo ────────────────────────────────────────────────────────
    _wz_step 3 $TOTAL "Give '$user' the right to become root"
    if ! command -v sudo &>/dev/null; then
        warn "sudo is not installed (minimal images often ship without it)."
        if confirm "Install sudo now?"; then
            if command -v apt-get &>/dev/null; then
                DEBIAN_FRONTEND=noninteractive apt-get install -y sudo || { error "apt-get install sudo failed"; pause; return 1; }
            elif command -v dnf &>/dev/null; then
                dnf install -y sudo || { error "dnf install sudo failed"; pause; return 1; }
            else
                error "No apt-get or dnf found — install sudo manually, then re-run."; pause; return 1
            fi
            success "sudo installed."
        else
            error "sudo is required for this model — stopping. Nothing was changed in sshd."
            pause; return 1
        fi
    fi
    local sgrp
    if ! sgrp="$(_ssh_sudo_group)"; then
        error "Neither a 'sudo' nor a 'wheel' group exists — cannot grant root rights safely."
        pause; return 1
    fi
    if id -nG "$user" 2>/dev/null | tr ' ' '\n' | grep -qx "$sgrp"; then
        success "'$user' is already in group '$sgrp'."
    else
        usermod -aG "$sgrp" "$user" || { error "usermod -aG $sgrp $user failed"; pause; return 1; }
        success "Added '$user' to group '$sgrp'."
    fi
    echo -e "  ${DIM}Group membership is read at LOGIN — a session '$user' already has open${RESET}"
    echo -e "  ${DIM}will not see it. That is why step 6 asks for a fresh login.${RESET}"

    # ── Step 4 — the public key ──────────────────────────────────────────────
    _wz_step 4 $TOTAL "Install your laptop's public key for '$user'"
    local uhome ukeys
    uhome="$(_ssh_user_home "$user")" || { error "No home directory for '$user'."; pause; return 1; }
    ukeys="$uhome/.ssh/authorized_keys"
    echo -e "Keys go to ${BOLD}$ukeys${RESET} — root's own keys are left alone."
    echo ""
    local have_keys=0
    if [[ -s "$ukeys" ]]; then
        have_keys="$(grep -cvE '^[[:space:]]*($|#)' "$ukeys" 2>/dev/null || echo 0)"
        info "'$user' already has $have_keys key(s) installed."
    fi
    # Re-running the wizard on an already-set-up account is the normal path after
    # a rolled-back step 7, so don't force a trip through the add-key menu.
    if [[ "${have_keys:-0}" -gt 0 ]] && confirm "Keep those and skip to the next step?"; then
        info "Keeping the existing key(s)."
    else
        # Point the shared key-installer at this account for the duration of the call.
        SSH_KEYS_OWNER="$user" SSH_KEYS_TARGET="$ukeys" menu_add_key || true
        unset SSH_KEYS_OWNER SSH_KEYS_TARGET
    fi
    if [[ ! -s "$ukeys" ]]; then
        error "No key was installed for '$user' — cannot continue."
        error "Nothing was changed in sshd; root access is untouched."
        pause; return 1
    fi
    success "'$user' has $(grep -cvE '^[[:space:]]*($|#)' "$ukeys" 2>/dev/null || echo 0) authorized key(s)."

    # ── Step 5 — optional file-transfer group ────────────────────────────────
    _wz_step 5 $TOTAL "File transfer without sudo (optional)"
    echo -e "With root SSH off, ${BOLD}scp root@host:...${RESET} stops working. The clean fix is a"
    echo -e "group that owns the backup directory, so '$user' reads and writes it"
    echo -e "directly — no sudo anywhere in the transfer path."
    echo ""
    echo -e "  ${DIM}Alternative, NOT done here: passwordless 'sudo rsync'. That grants${RESET}"
    echo -e "  ${DIM}write access to every file on the box, which is root by another name.${RESET}"
    echo ""
    if confirm "Create group 'grinops' and give '$user' access to /opt/grin/backups?"; then
        _wz_transfer_group "$user" || warn "Transfer group setup did not complete — SSH hardening can still continue."
    else
        info "Skipped — you can run this later from the wizard again."
    fi

    # ── Step 6 — PROVE the new way in works ──────────────────────────────────
    local port sip
    port="$(_ssh_port)"
    sip="$(awk '{print $3}' <<<"${SSH_CONNECTION:-}")"
    local key_ok=0 sudo_ok=0
    while true; do
        _wz_step 6 $TOTAL "Prove it works — BEFORE anything is locked down"
        echo -e "In a ${BOLD}second terminal${RESET} (keep this one open), run:"
        echo ""
        echo -e "   ${BOLD}ssh ${user}@${sip:-<server-ip>} -p ${port}${RESET}"
        echo -e "   ${BOLD}sudo -i${RESET}     ${DIM}← asks for ${user}'s password, gives you a root shell${RESET}"
        echo ""
        echo -e "${DIM}Then come back here and re-check. Both lines must go green.${RESET}"
        echo ""

        local ev
        if ev="$(_wz_key_login_seen "$user")"; then
            key_ok=1
            success "Key login by '$user': PROVEN in the SSH log — check the date:"
            echo -e "    ${DIM}${ev: -110}${RESET}"
        else
            key_ok=0
            local priv
            priv="$(ls -1t "$uhome"/.ssh/grin_ed25519_* 2>/dev/null | grep -v '\.pub$' | head -1 || true)"
            if [[ -n "$priv" ]] && _ssh_loopback_test "$priv" "$user"; then
                key_ok=1
                success "Key login by '$user': PROVEN by loopback SSH using $priv"
            else
                error "Key login by '$user': no successful publickey login found in the log yet"
            fi
        fi

        local src=0
        _wz_sudo_ok "$user" || src=$?
        case "$src" in
            0) sudo_ok=1; success "Root via sudo for '$user': CONFIRMED (sudo -l -U $user grants ALL)" ;;
            2) sudo_ok=0; error "sudo is not installed — cannot confirm root access" ;;
            *) sudo_ok=0; error "Root via sudo for '$user': NOT granted (check group '$sgrp' / sudoers)" ;;
        esac

        echo ""
        if [[ $key_ok -eq 1 && $sudo_ok -eq 1 ]]; then
            echo -e "${BOLD}${GREEN}  Both proofs are green — safe to lock down.${RESET}"
            echo ""
            echo -ne "${BOLD}Continue to step 7 (change sshd)? [Y/n]: ${RESET}"
            local go
            if ! read -r go; then
                echo ""
                warn "No input available — declining the sshd change."
                return 0
            fi
            if [[ -z "$go" || "${go,,}" == "y" ]]; then
                break
            fi
            info "Stopped before any sshd change. Re-run the wizard when ready."
            pause; return 0
        fi
        echo -e "${BOLD}${YELLOW}  Not proven yet — sshd has NOT been touched.${RESET}"
        echo ""
        echo -e "  ${BOLD}r${RESET}) re-check   ${BOLD}q${RESET}) stop here (nothing changed)"
        echo -ne "${BOLD}Choose [r/q]: ${RESET}"
        local c
        if ! read -r c; then
            echo ""
            warn "No input available — stopping. No SSH changes were made."
            return 0
        fi
        if [[ "${c,,}" == "q" ]]; then
            info "Stopped. No SSH changes were made."
            pause; return 0
        fi
    done

    # ── Step 7 — apply, with a dead-man timer ────────────────────────────────
    _wz_step 7 $TOTAL "Lock it down"
    local others others_list=""
    others="$(_wz_human_users | grep -vx "$user" || true)"
    echo -e "About to apply:"
    echo -e "  ${BOLD}PasswordAuthentication no${RESET}   ${DIM}keys only${RESET}"
    echo -e "  ${BOLD}PermitRootLogin no${RESET}          ${DIM}no direct root SSH, key or not${RESET}"
    echo ""
    local allow="$user"
    if [[ -n "$others" ]]; then
        echo -e "${YELLOW}Other human accounts exist on this box:${RESET}"
        local o keyed="" keyed_n=0
        while IFS= read -r o; do
            [[ -z "$o" ]] && continue
            local oh
            oh="$(_ssh_user_home "$o" 2>/dev/null || echo "")"
            if [[ -n "$oh" && -s "$oh/.ssh/authorized_keys" ]]; then
                echo -e "   • $o   ${YELLOW}HAS ssh keys — can log in today${RESET}"
                keyed+="$o "
                keyed_n=$((keyed_n + 1))
            else
                echo -e "   • $o   ${DIM}no keys — cannot log in once passwords are off anyway${RESET}"
            fi
            others_list+="$o "
        done <<<"$others"
        echo ""
        echo -e "An ${BOLD}AllowUsers${RESET} allow-list is the strongest form of this: SSH accepts"
        echo -e "the listed names and refuses every other account at the door."
        echo ""
        if [[ $keyed_n -gt 0 ]]; then
            echo -e "${BOLD}${YELLOW}  Restricting to '$user' alone WILL lock out: $(echo "$keyed" | xargs)${RESET}"
            echo -e "  ${DIM}Their accounts, passwords, sudo rights and keys all stay — they simply${RESET}"
            echo -e "  ${DIM}cannot connect over SSH. Reachable again via 'sudo -u <name> -i' from${RESET}"
            echo -e "  ${DIM}'$user', or by re-running this wizard and allowing them.${RESET}"
            echo ""
        fi
        if confirm "Restrict SSH to '$user' ONLY (add AllowUsers)?"; then
            allow="$user"
        elif confirm "Allow '$user' plus the accounts listed above?"; then
            allow="$user $(echo "$others_list" | xargs)"
        else
            allow=""
            info "No AllowUsers rule — any account with a key may log in (root still cannot)."
        fi
    else
        if ! confirm "Also add 'AllowUsers $user' (recommended — blocks every other account)?"; then
            allow=""
        fi
    fi

    _ssh_policy_set "$allow" "no"
    echo ""
    echo -e "${BOLD}A safety timer is strongly recommended:${RESET} the change is applied now and"
    echo -e "automatically undone in N minutes ${BOLD}unless${RESET} you confirm you can still get"
    echo -e "in. If anything is wrong, you wait it out and nothing is lost."
    echo ""
    echo -ne "${BOLD}Auto-undo after how many minutes? [10, 0 = no timer]: ${RESET}"
    local mins; read -r mins
    mins="${mins:-10}"
    [[ "$mins" =~ ^[0-9]+$ ]] || mins=10

    if ! confirm "Apply now?"; then
        info "Not applied. The user, key, sudo and group setup all remain in place."
        pause; return 0
    fi

    if ! _ssh_apply_hardening; then
        error "sshd would not accept the change — nothing was applied."
        error "Password login and root access are exactly as they were."
        pause; return 1
    fi

    echo ""
    info "Checking what sshd actually resolved (not just what we wrote) ..."
    local eff_ok=0
    _ssh_postapply_gate "no" "$user" || eff_ok=1
    if [[ $eff_ok -ne 0 ]]; then
        echo ""
        warn "The hardening did not fully take. Rolling it back so you are not left"
        warn "in a half-applied state."
        _ssh_revert_hardening || error "Rollback ALSO failed — fix $SSHD_CONFIG by hand NOW, in this session."
        pause; return 1
    fi

    _ssh_cancel_autorevert
    if [[ "$mins" -gt 0 ]]; then
        _ssh_schedule_autorevert "$mins"
        success "Applied, with a ${mins}-minute auto-undo."
    else
        success "Applied permanently (no timer)."
    fi

    # ── Closing instructions ─────────────────────────────────────────────────
    echo ""
    echo -e "${BOLD}${CYAN}━━━ From now on ━━━${RESET}"
    echo ""
    echo -e "  ${BOLD}ssh ${user}@${sip:-<server-ip>} -p ${port}${RESET}"
    echo -e "  ${BOLD}sudo -i${RESET}                 ${DIM}← root shell; run the toolkit from here${RESET}"
    echo ""
    echo -e "  ${YELLOW}Use 'sudo -i', not 'sudo ./grin-node-toolkit.sh'.${RESET} Bare sudo keeps"
    echo -e "  HOME=$uhome, and parts of the toolkit read \$HOME/.grin — plus you"
    echo -e "  need a root shell to see the node's tmux sessions."
    echo ""
    echo -e "  ${BOLD}Put this in your laptop's ~/.ssh/config${RESET} ${DIM}(then it is just 'ssh grinvps')${RESET}"
    echo -e "  ${DIM}Windows: %USERPROFILE%\\.ssh\\\\config${RESET}"
    echo ""
    echo -e "    ${DIM}Host grinvps${RESET}"
    echo -e "    ${DIM}    HostName ${sip:-<server-ip>}${RESET}"
    echo -e "    ${DIM}    User ${user}${RESET}"
    echo -e "    ${DIM}    Port ${port}${RESET}"
    echo -e "    ${DIM}    IdentityFile ~/.ssh/id_ed25519${RESET}"
    echo ""
    echo -e "  Then: ${DIM}ssh grinvps${RESET} · ${DIM}scp grinvps:/opt/grin/backups/x.tar.gz .${RESET}"
    echo ""
    if [[ "$mins" -gt 0 ]]; then
        echo -e "${BOLD}${YELLOW}  NOT FINISHED — the timer is running.${RESET}"
        echo -e "  Log in as ${BOLD}${user}${RESET} in a new terminal right now."
        echo -e "   • it works  → come back and run ${BOLD}option 5${RESET} (make permanent)"
        echo -e "   • it fails  → do nothing; everything reverts in ${mins} min"
    else
        echo -e "  ${DIM}Break-glass: option 6 re-enables password login and root SSH.${RESET}"
    fi
    pause
}

# =============================================================================
# Main menu
# =============================================================================
show_menu() {
    clear
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${CYAN} 085)  SSH Key Hardening  ${DIM}(login by key, not password)${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
    echo -e "${BOLD}  Start here${RESET}"
    echo -e "  ${BOLD}${GREEN}W${RESET})  GUIDED SETUP →          ${DIM}key ▸ normal user ▸ sudo ▸ root, in order${RESET}"
    echo -e "      ${DIM}Creates the user, installs the key, proves both work, THEN locks${RESET}"
    echo -e "      ${DIM}SSH down. Does every step below in the safe sequence.${RESET}"
    echo ""
    echo -e "${BOLD}  Keys${RESET}   ${DIM}individual actions — to adjust, not to set up${RESET}"
    echo -e "  ${GREEN}1${RESET})  Add a public key          ${DIM}paste · generate on server · fetch URL${RESET}"
    echo -e "  ${GREEN}2${RESET})  List installed keys       ${DIM}fingerprints in /root/.ssh/authorized_keys${RESET}"
    echo ""
    echo -e "${BOLD}  Hardening${RESET}"
    echo -e "  ${GREEN}3${RESET})  Verify key login          ${DIM}anti-lockout self-test (run this first!)${RESET}"
    echo -e "  ${YELLOW}4${RESET})  Disable password login    ${DIM}key-only; optional safety timer${RESET}"
    echo -e "  ${YELLOW}5${RESET})  Make key-only permanent   ${DIM}cancel safety timer after testing${RESET}"
    echo -e "  ${YELLOW}6${RESET})  Re-enable password login  ${DIM}rollback / break-glass${RESET}"
    echo ""
    echo -e "${BOLD}  Info${RESET}"
    echo -e "  ${CYAN}7${RESET})  SSH status & audit        ${DIM}effective config, keys, firewall${RESET}"
    echo -e "  ${CYAN}8${RESET})  How to connect with key   ${DIM}remote-tool steps (Windows/Linux/macOS)${RESET}"
    echo ""
    echo -e "  ${DIM}0${RESET})  Return to admin menu"
    echo ""
    echo -e "${DIM}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -ne "${BOLD}Select [W / 1-8 / 0]: ${RESET}"
}

main() {
    while true; do
        show_menu
        local choice; read -r choice
        case "${choice,,}" in
            w) wizard_admin_user     || true ;;
            1) menu_add_key          || true ;;
            2) list_keys             || true ;;
            3) verify_key_login      || true ;;
            4) disable_password_auth || true ;;
            5) commit_hardening      || true ;;
            6) enable_password_auth  || true ;;
            7) ssh_status            || true ;;
            8) connect_help          || true ;;
            0) break ;;
            *) warn "Invalid option."; sleep 1 ;;
        esac
    done
}

main "$@"
