#!/bin/bash
# =============================================================================
# 085_ssh_hardening.sh - SSH Key Hardening (root login by key, not password)
# =============================================================================
# Gets a working SSH public key onto the server, verifies key login, then
# optionally disables password authentication so the box is reachable by key
# only — with a guaranteed rollback / break-glass path so you can never lock
# yourself out.
#
# Scope: root account only (the toolkit already runs as root on the VPS).
#
# Key handling (3 methods, in order):
#   1) Paste manually          — paste the public key from your laptop
#   2) Generate on server      — ssh-keygen here; private key shown ONCE to save
#   3) Fetch from URL          — github username, or any raw URL serving a
#                                PUBLIC key (e.g. github.com/<user>.keys, or a
#                                self-hosted pubkey directory). Private keys are
#                                NEVER generated by or fetched from a website.
#
# Hardening is staged safely:
#   · changes go to a drop-in (/etc/ssh/sshd_config.d/99-grin-hardening.conf)
#     when the distro supports Include, else a marked block in sshd_config
#   · every change is validated with `sshd -t` BEFORE it is applied
#   · sshd is RELOADED, never restarted (your current session survives)
#   · disabling passwords is gated behind an authorized_keys check + an
#     optional dead-man safety timer that auto-restores passwords unless you
#     explicitly commit
#   · "Re-enable password login" is always available as break-glass
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ─── Paths ────────────────────────────────────────────────────────────────────
LOG_DIR="/opt/grin/logs"
LOG_FILE="$LOG_DIR/grin_ssh_hardening_$(date +%Y%m%d_%H%M%S).log"
CONF_DIR="/opt/grin/conf"
BACKUP_DIR="$CONF_DIR/ssh_backups"
SSHD_CONFIG="/etc/ssh/sshd_config"
DROPIN_DIR="/etc/ssh/sshd_config.d"
HARDENING_DROPIN="$DROPIN_DIR/99-grin-hardening.conf"
AUTH_KEYS="/root/.ssh/authorized_keys"
AUTOREVERT_PID="$CONF_DIR/ssh_autorevert.pid"
AUTOREVERT_SH="$CONF_DIR/ssh_autorevert.sh"
MARK_BEGIN="# >>> grin-toolkit ssh hardening >>>"
MARK_END="# <<< grin-toolkit ssh hardening <<<"
mkdir -p "$LOG_DIR" "$CONF_DIR" "$BACKUP_DIR"

# ─── Colors ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; DIM='\033[2m'; RESET='\033[0m'

# ─── Logging ──────────────────────────────────────────────────────────────────
log()     { echo "[$(date -u '+%Y-%m-%d %H:%M:%S UTC')] $*" >> "$LOG_FILE" 2>/dev/null || true; }
info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; log "[INFO]  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; log "[OK]    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; log "[WARN]  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*"; log "[ERROR] $*"; }

pause() { echo ""; echo "Press Enter to return to menu..."; read -r; }

confirm() {
    local prompt="$1"
    echo ""
    echo -ne "${BOLD}${YELLOW}▶ $prompt [y/N]: ${RESET}"
    local ans; read -r ans
    [[ "${ans,,}" == "y" ]]
}

# ─── Root guard ────────────────────────────────────────────────────────────────
if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
    error "This tool must run as root (it edits /etc/ssh and /root/.ssh)."
    exit 1
fi

if ! command -v ssh-keygen &>/dev/null; then
    error "ssh-keygen not found — install the openssh client/server first."
    exit 1
fi

# =============================================================================
# SSH service helpers
# =============================================================================
_ssh_service_reload() {
    systemctl reload ssh   2>/dev/null && return 0
    systemctl reload sshd  2>/dev/null && return 0
    service ssh reload     2>/dev/null && return 0
    service sshd reload    2>/dev/null && return 0
    return 1
}

# Effective config value via `sshd -T` (lower-cased keyword), with a grep fallback.
_ssh_effective() {
    local key="$1"
    sshd -T 2>/dev/null | awk -v k="${key,,}" 'tolower($1)==k {print $2; exit}'
}

_ssh_port() {
    local p; p="$(_ssh_effective port)"
    echo "${p:-22}"
}

_ssh_dropin_supported() {
    [[ -d "$DROPIN_DIR" ]] && \
    grep -Eq '^[[:space:]]*Include[[:space:]]+/etc/ssh/sshd_config\.d/\*\.conf' "$SSHD_CONFIG"
}

_ssh_backup_config() {
    local ts dest
    ts="$(date +%Y%m%d_%H%M%S)"
    dest="$BACKUP_DIR/sshd_config.$ts.bak"
    cp -a "$SSHD_CONFIG" "$dest" 2>/dev/null && log "Backed up $SSHD_CONFIG -> $dest"
    echo "$dest"
}

_ssh_remove_managed_block() {
    [[ -f "$SSHD_CONFIG" ]] || return 0
    sed -i "/$MARK_BEGIN/,/$MARK_END/d" "$SSHD_CONFIG" 2>/dev/null || true
}

_ssh_remove_hardening() {
    rm -f "$HARDENING_DROPIN" 2>/dev/null || true
    _ssh_remove_managed_block
}

# =============================================================================
# Key installation (shared by all 3 add methods)
# Reads candidate public-key lines from stdin; validates + dedupes into
# /root/.ssh/authorized_keys.
# =============================================================================
_ssh_install_keys() {
    mkdir -p /root/.ssh
    chmod 700 /root/.ssh
    touch "$AUTH_KEYS"
    chmod 600 "$AUTH_KEYS"

    local installed=0 skipped=0 invalid=0 line tmp fp
    while IFS= read -r line; do
        line="$(printf '%s' "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
        [[ -z "$line" || "$line" == \#* ]] && continue

        tmp="$(mktemp)"
        printf '%s\n' "$line" > "$tmp"
        if fp="$(ssh-keygen -l -f "$tmp" 2>/dev/null)"; then
            if grep -qxF "$line" "$AUTH_KEYS"; then
                skipped=$((skipped + 1))
                info "Already present: $fp"
            else
                printf '%s\n' "$line" >> "$AUTH_KEYS"
                installed=$((installed + 1))
                success "Installed: $fp"
            fi
        else
            invalid=$((invalid + 1))
            warn "Not a valid public key, skipped: ${line:0:42}..."
        fi
        rm -f "$tmp"
    done

    echo ""
    info "Summary — installed: $installed, already-present: $skipped, invalid: $invalid"
    [[ $installed -gt 0 || $skipped -gt 0 ]]
}

# =============================================================================
# 1) Add key — paste manually
# =============================================================================
add_key_paste() {
    clear
    echo -e "${BOLD}${CYAN}  Add public key — paste manually${RESET}"
    echo ""
    echo -e "On your laptop the public key is usually in ${BOLD}~/.ssh/id_ed25519.pub${RESET}"
    echo -e "(or ${BOLD}id_rsa.pub${RESET}). Print it with: ${DIM}cat ~/.ssh/id_ed25519.pub${RESET}"
    echo ""
    echo -e "Paste one or more PUBLIC key lines below. Finish with an ${BOLD}empty line${RESET}:"
    echo ""

    local lines="" l
    while IFS= read -r l; do
        [[ -z "$l" ]] && break
        lines+="$l"$'\n'
    done

    if [[ -z "${lines//[$'\n\t ']/}" ]]; then
        warn "Nothing pasted — no changes made."
        pause; return 0
    fi
    printf '%s' "$lines" | _ssh_install_keys || true
    pause
}

# =============================================================================
# 2) Add key — generate on server
# =============================================================================
add_key_generate() {
    clear
    echo -e "${BOLD}${CYAN}  Add public key — generate on server${RESET}"
    echo ""
    echo -e "${YELLOW}Note:${RESET} the safest keys are generated on YOUR OWN machine and"
    echo -e "imported. Generate-on-server is a convenience — the private key is"
    echo -e "shown here ${BOLD}once${RESET}; you must copy it to your laptop now."
    echo ""
    if ! confirm "Generate a new ed25519 key pair on this server?"; then
        info "Cancelled."; pause; return 0
    fi

    local ts kf
    ts="$(date +%Y%m%d_%H%M%S)"
    kf="/root/.ssh/grin_ed25519_$ts"
    mkdir -p /root/.ssh; chmod 700 /root/.ssh
    if ! ssh-keygen -t ed25519 -N "" -C "grin-toolkit-$ts" -f "$kf" >/dev/null 2>&1; then
        error "ssh-keygen failed."; pause; return 0
    fi
    success "Key pair generated: $kf{,.pub}"

    # Install the public half into authorized_keys.
    _ssh_install_keys < "$kf.pub" || true

    echo ""
    echo -e "${BOLD}${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${RED}  PRIVATE KEY — shown ONCE. Save it to your laptop NOW.${RESET}"
    echo -e "${BOLD}${RED}  Store it at ~/.ssh/grin_ed25519 and: chmod 600 ~/.ssh/grin_ed25519${RESET}"
    echo -e "${BOLD}${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
    cat "$kf"
    echo ""
    echo -e "${BOLD}Connect with:${RESET} ${DIM}ssh -i ~/.ssh/grin_ed25519 root@<server-ip> -p $(_ssh_port)${RESET}"
    echo ""

    if confirm "Have you saved the private key? Delete the server's private-key copy now (recommended)?"; then
        shred -u "$kf" 2>/dev/null || rm -f "$kf"
        success "Server private-key copy deleted ($kf). Public key stays in authorized_keys."
    else
        warn "Private key left on server at $kf — delete it once you've copied it."
    fi
    pause
}

# =============================================================================
# 3) Add key — fetch from URL (github username or raw URL)
# =============================================================================
add_key_url() {
    clear
    echo -e "${BOLD}${CYAN}  Add public key — fetch from URL${RESET}"
    echo ""
    echo -e "Enter a ${BOLD}GitHub username${RESET} (keys pulled from github.com/<user>.keys),"
    echo -e "or any ${BOLD}raw URL${RESET} that serves PUBLIC key lines"
    echo -e "(GitLab, or a self-hosted pubkey directory)."
    echo ""
    if ! command -v curl &>/dev/null; then
        error "curl not found — install curl or use paste instead."; pause; return 0
    fi
    echo -ne "${BOLD}GitHub username or URL: ${RESET}"
    local src url; read -r src
    src="$(printf '%s' "$src" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    if [[ -z "$src" ]]; then
        warn "Nothing entered."; pause; return 0
    fi
    if [[ "$src" == *"://"* ]]; then
        url="$src"
    else
        url="https://github.com/${src}.keys"
    fi
    info "Fetching $url ..."
    local body
    if ! body="$(curl -fsSL --max-time 20 "$url" 2>/dev/null)" || [[ -z "$body" ]]; then
        error "Could not fetch any key from $url"
        pause; return 0
    fi
    printf '%s\n' "$body" | _ssh_install_keys || true
    pause
}

# =============================================================================
# Add-key submenu
# =============================================================================
menu_add_key() {
    while true; do
        clear
        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo -e "${BOLD}${CYAN}  Add a public key to root${RESET}"
        echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
        echo ""
        echo -e "  ${GREEN}1${RESET})  Paste manually        ${DIM}paste your laptop's *.pub line${RESET}"
        echo -e "  ${GREEN}2${RESET})  Generate on server    ${DIM}ssh-keygen here, private key shown once${RESET}"
        echo -e "  ${GREEN}3${RESET})  Fetch from URL        ${DIM}github username or raw pubkey URL${RESET}"
        echo ""
        echo -e "  ${DIM}0${RESET})  Back"
        echo ""
        echo -ne "${BOLD}Select [0-3]: ${RESET}"
        local c; read -r c
        case "$c" in
            1) add_key_paste    || true ;;
            2) add_key_generate || true ;;
            3) add_key_url      || true ;;
            0) break ;;
            *) warn "Invalid option."; sleep 1 ;;
        esac
    done
}

# =============================================================================
# List installed keys
# =============================================================================
list_keys() {
    clear
    echo -e "${BOLD}${CYAN}  Installed authorized keys (root)${RESET}"
    echo ""
    if [[ ! -s "$AUTH_KEYS" ]]; then
        warn "No keys installed yet ($AUTH_KEYS is empty or missing)."
        pause; return 0
    fi
    local n=0 line tmp
    while IFS= read -r line; do
        [[ -z "$line" || "$line" == \#* ]] && continue
        n=$((n + 1))
        tmp="$(mktemp)"; printf '%s\n' "$line" > "$tmp"
        printf "  ${BOLD}%2d)${RESET} %s\n" "$n" "$(ssh-keygen -l -f "$tmp" 2>/dev/null || echo '(unparseable line)')"
        rm -f "$tmp"
    done < "$AUTH_KEYS"
    echo ""
    info "$n key(s) in $AUTH_KEYS"
    pause
}

# =============================================================================
# Anti-lockout self-test — verify key login BEFORE disabling passwords
# =============================================================================

# How did THIS session authenticate? (publickey|password|keyboard-interactive|unknown)
# The strongest proof key auth works: if you're reading this over a key session,
# disabling passwords can't lock you out.
_ssh_current_session_auth() {
    if [[ -z "${SSH_CONNECTION:-}" ]]; then echo "unknown"; return 0; fi
    local cip cport line=""
    cip="$(awk '{print $1}' <<<"$SSH_CONNECTION")"
    cport="$(awk '{print $2}' <<<"$SSH_CONNECTION")"
    if command -v journalctl &>/dev/null; then
        line="$(journalctl _COMM=sshd -n 3000 --no-pager 2>/dev/null \
                | grep -E "Accepted .* from ${cip} port ${cport}( |$)" | tail -1 || true)"
    fi
    if [[ -z "$line" ]]; then
        local f
        for f in /var/log/auth.log /var/log/secure; do
            [[ -r "$f" ]] || continue
            line="$(grep -E "Accepted .* from ${cip} port ${cport}( |$)" "$f" 2>/dev/null | tail -1 || true)"
            [[ -n "$line" ]] && break
        done
    fi
    case "$line" in
        *"Accepted publickey"*)            echo "publickey" ;;
        *"Accepted password"*)             echo "password" ;;
        *"Accepted keyboard-interactive"*) echo "keyboard-interactive" ;;
        *)                                 echo "unknown" ;;
    esac
}

# Real end-to-end key-auth probe: SSH to ourselves using a PRIVATE key, with
# passwords forced off. Returns 0 only if the key alone authenticates.
# Needs the private key on disk (generate-on-server case, or a path the operator
# supplies for a one-off test). $1 = private key path.
_ssh_loopback_test() {
    local key="$1" port host
    [[ -r "$key" ]] || return 2
    command -v ssh &>/dev/null || return 2
    port="$(_ssh_port)"
    for host in 127.0.0.1 "$(awk '{print $3}' <<<"${SSH_CONNECTION:-}")"; do
        [[ -n "$host" ]] || continue
        if ssh -i "$key" -p "$port" \
                -o BatchMode=yes -o StrictHostKeyChecking=no \
                -o UserKnownHostsFile=/dev/null \
                -o PreferredAuthentications=publickey \
                -o PasswordAuthentication=no \
                -o ConnectTimeout=8 \
                "root@${host}" true 2>/dev/null; then
            return 0
        fi
    done
    return 1
}

# Pre-flight readiness check. Returns 0 if key login is CONFIRMED safe, else 1.
# When $1 == "quiet" it prints a one-line verdict only (used inside the disable
# flow); otherwise it prints the full report.
verify_key_login() {
    local quiet="${1:-}"
    [[ "$quiet" != "quiet" ]] && { clear; echo -e "${BOLD}${CYAN}  Verify key login (anti-lockout self-test)${RESET}"; echo ""; }

    local keys_ok=0 config_ok=0 pubkey_ok=0 confirmed=0
    local kcount=0
    [[ -s "$AUTH_KEYS" ]] && kcount="$(grep -cvE '^[[:space:]]*($|#)' "$AUTH_KEYS" 2>/dev/null || echo 0)"
    [[ "$kcount" -gt 0 ]] && keys_ok=1

    local meth; meth="$(_ssh_current_session_auth)"

    if [[ "$quiet" != "quiet" ]]; then
        # 1) keys present
        if [[ $keys_ok -eq 1 ]]; then success "authorized_keys: $kcount key(s) installed for root"
        else error "authorized_keys: empty — add a key first (option 1)"; fi

        # 2) perms / ownership
        local dperm fperm downer
        dperm="$(stat -c '%a' /root/.ssh 2>/dev/null || echo '?')"
        fperm="$(stat -c '%a' "$AUTH_KEYS" 2>/dev/null || echo '?')"
        downer="$(stat -c '%U' "$AUTH_KEYS" 2>/dev/null || echo '?')"
        if [[ "$dperm" == "700" && ( "$fperm" == "600" || "$fperm" == "644" ) && "$downer" == "root" ]]; then
            success "Permissions: ~/.ssh=$dperm authorized_keys=$fperm owner=$downer"
        else
            warn "Permissions look off: ~/.ssh=$dperm authorized_keys=$fperm owner=$downer (want 700/600 root)"
        fi
    fi

    # 3) sshd config valid
    if sshd -t 2>/tmp/grin_sshd_err; then
        config_ok=1
        [[ "$quiet" != "quiet" ]] && success "sshd config: valid (sshd -t)"
    else
        [[ "$quiet" != "quiet" ]] && { error "sshd config: INVALID — fix before hardening:"; sed 's/^/      /' /tmp/grin_sshd_err; }
    fi

    # 4) pubkey auth effective for root (honours Match blocks)
    local epub
    epub="$(sshd -T -C user=root 2>/dev/null | awk 'tolower($1)=="pubkeyauthentication"{print $2; exit}')"
    [[ -z "$epub" ]] && epub="$(_ssh_effective pubkeyauthentication)"
    [[ "$epub" == "yes" ]] && pubkey_ok=1
    if [[ "$quiet" != "quiet" ]]; then
        if [[ $pubkey_ok -eq 1 ]]; then success "PubkeyAuthentication: yes (effective for root)"
        else error "PubkeyAuthentication: ${epub:-unknown} — keys won't be accepted"; fi
    fi

    # 5) how the CURRENT session got in
    if [[ "$quiet" != "quiet" ]]; then
        case "$meth" in
            publickey) success "This session authenticated by: ${BOLD}publickey${RESET} ← key login already works" ;;
            password)  warn "This session authenticated by: ${BOLD}password${RESET} — not proof your key works yet" ;;
            keyboard-interactive) warn "This session authenticated by: keyboard-interactive (not pubkey)" ;;
            *)         warn "Could not determine how this session authenticated (no log match)" ;;
        esac
    fi

    # 6) optional real loopback probe with a private key we hold
    local loop_ok=0 priv=""
    priv="$(ls -1t /root/.ssh/grin_ed25519_* 2>/dev/null | grep -v '\.pub$' | head -1 || true)"
    if [[ "$quiet" != "quiet" ]]; then
        if [[ -n "$priv" ]]; then
            info "Loopback key-auth probe using $priv ..."
            if _ssh_loopback_test "$priv"; then loop_ok=1; success "Loopback login with key: SUCCESS"
            else warn "Loopback login with key: failed (server may not accept SSH on localhost — not conclusive)"; fi
        else
            echo -ne "${DIM}  Optional: path to a private key to test now (Enter to skip): ${RESET}"
            local p; read -r p
            if [[ -n "$p" ]]; then
                if _ssh_loopback_test "$p"; then loop_ok=1; success "Loopback login with key: SUCCESS"
                else warn "Loopback login with key: failed or key unreadable"; fi
            fi
        fi
    fi

    # Verdict: confirmed if you're already on a key session, OR a loopback key
    # login succeeded — and the static prerequisites hold.
    if [[ ( "$meth" == "publickey" || $loop_ok -eq 1 ) && $keys_ok -eq 1 && $config_ok -eq 1 && $pubkey_ok -eq 1 ]]; then
        confirmed=1
    fi

    if [[ "$quiet" != "quiet" ]]; then
        echo ""
        local port; port="$(_ssh_port)"
        local sip; sip="$(awk '{print $3}' <<<"${SSH_CONNECTION:-}")"
        if [[ $confirmed -eq 1 ]]; then
            echo -e "${BOLD}${GREEN}  VERDICT: READY — key login is confirmed working.${RESET}"
            echo -e "  Disabling passwords (option 4) is safe; you will not be locked out."
        else
            echo -e "${BOLD}${YELLOW}  VERDICT: NOT CONFIRMED — do NOT disable passwords yet.${RESET}"
            echo ""
            echo -e "  Make it green:"
            [[ $keys_ok -eq 0 ]]   && echo -e "   • add your public key (option 1)"
            [[ $pubkey_ok -eq 0 ]] && echo -e "   • enable PubkeyAuthentication / fix sshd config"
            if [[ "$meth" != "publickey" ]]; then
                echo -e "   • open a NEW terminal and log in with your key:"
                echo -e "       ${DIM}ssh root@${sip:-<server-ip>} -p $port${RESET}"
                echo -e "     then re-run this check — it should turn green."
            fi
            echo -e "  ${DIM}If unsure, use option 4's safety timer: it auto-restores passwords${RESET}"
            echo -e "  ${DIM}unless you confirm you can still get in.${RESET}"
        fi
        pause
    fi

    [[ $confirmed -eq 1 ]]
}

# =============================================================================
# Apply / revert the password-off hardening
# =============================================================================
_ssh_apply_hardening() {
    _ssh_backup_config >/dev/null
    if _ssh_dropin_supported; then
        cat > "$HARDENING_DROPIN" <<EOF
# Managed by Grin Node Toolkit (085_ssh_hardening.sh) — do not edit by hand.
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin prohibit-password
EOF
        chmod 644 "$HARDENING_DROPIN"
        log "Wrote drop-in $HARDENING_DROPIN"
    else
        _ssh_remove_managed_block
        {
            echo ""
            echo "$MARK_BEGIN"
            echo "PubkeyAuthentication yes"
            echo "PasswordAuthentication no"
            echo "KbdInteractiveAuthentication no"
            echo "PermitRootLogin prohibit-password"
            echo "$MARK_END"
        } >> "$SSHD_CONFIG"
        log "Appended managed block to $SSHD_CONFIG"
    fi

    if ! sshd -t 2>/tmp/grin_sshd_err; then
        error "sshd config validation FAILED — reverting, nothing applied:"
        sed 's/^/    /' /tmp/grin_sshd_err
        _ssh_remove_hardening
        return 1
    fi
    if ! _ssh_service_reload; then
        error "Could not reload the ssh service — reverting to be safe."
        _ssh_remove_hardening
        return 1
    fi
    return 0
}

_ssh_revert_hardening() {
    _ssh_backup_config >/dev/null
    _ssh_remove_hardening
    if ! sshd -t 2>/tmp/grin_sshd_err; then
        error "sshd config invalid after revert — manual check needed:"
        sed 's/^/    /' /tmp/grin_sshd_err
        return 1
    fi
    _ssh_service_reload || { error "ssh reload failed."; return 1; }
    return 0
}

# =============================================================================
# Dead-man safety timer
# =============================================================================
_ssh_autorevert_active() {
    [[ -f "$AUTOREVERT_PID" ]] && kill -0 "$(cat "$AUTOREVERT_PID" 2>/dev/null)" 2>/dev/null
}

_ssh_schedule_autorevert() {
    local mins="$1"
    cat > "$AUTOREVERT_SH" <<EOF
#!/bin/bash
sleep $((mins * 60))
rm -f "$HARDENING_DROPIN" 2>/dev/null
sed -i "/$MARK_BEGIN/,/$MARK_END/d" "$SSHD_CONFIG" 2>/dev/null
if sshd -t 2>/dev/null; then
    systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || \
    service ssh reload 2>/dev/null || service sshd reload 2>/dev/null
fi
rm -f "$AUTOREVERT_PID" "$AUTOREVERT_SH" 2>/dev/null
EOF
    chmod +x "$AUTOREVERT_SH"
    nohup bash "$AUTOREVERT_SH" >/dev/null 2>&1 &
    echo $! > "$AUTOREVERT_PID"
    log "Scheduled auto-revert in $mins min (pid $(cat "$AUTOREVERT_PID"))"
}

_ssh_cancel_autorevert() {
    if _ssh_autorevert_active; then
        kill "$(cat "$AUTOREVERT_PID" 2>/dev/null)" 2>/dev/null || true
    fi
    rm -f "$AUTOREVERT_PID" "$AUTOREVERT_SH" 2>/dev/null || true
}

# =============================================================================
# Disable password login (key-only)
# =============================================================================
disable_password_auth() {
    clear
    echo -e "${BOLD}${CYAN}  Disable password login (key-only root access)${RESET}"
    echo ""

    if [[ ! -s "$AUTH_KEYS" ]]; then
        error "No authorized keys installed — add a key first (option 1)."
        error "Disabling passwords now would LOCK YOU OUT."
        pause; return 0
    fi

    local kcount
    kcount="$(grep -cvE '^[[:space:]]*($|#)' "$AUTH_KEYS" 2>/dev/null || echo 0)"
    info "$kcount key(s) currently authorized for root."

    # Anti-lockout pre-flight — surface the verdict before any change.
    if verify_key_login quiet; then
        success "Self-test: key login is CONFIRMED working (this session is key-authenticated)."
    else
        local _m; _m="$(_ssh_current_session_auth)"
        warn "Self-test: key login NOT confirmed (current session: ${_m})."
        warn "Run option 3 (Verify key login) for details — or use the safety timer below."
    fi

    # Firewall sanity — is the SSH port reachable?
    local port; port="$(_ssh_port)"
    if command -v ufw &>/dev/null && ufw status 2>/dev/null | grep -qi '^Status: active'; then
        if ufw status 2>/dev/null | grep -qE "(^|[[:space:]])$port(/tcp)?[[:space:]]"; then
            info "UFW: port $port appears allowed."
        else
            warn "UFW is active but no explicit rule for SSH port $port was found."
            warn "Make sure you can still reach the server on port $port."
        fi
    fi

    echo ""
    echo -e "${BOLD}${YELLOW}IMPORTANT — verify key login BEFORE relying on this.${RESET}"
    echo -e "Open a ${BOLD}second${RESET} terminal and confirm: ${DIM}ssh root@<server-ip> -p $port${RESET}"
    echo -e "logs in using your key (no password prompt)."
    echo ""
    echo -e "Two ways to proceed safely:"
    echo -e "  ${BOLD}A)${RESET} Safety timer — apply now, passwords auto-restore in N minutes"
    echo -e "     unless you commit with option 5. Best if you haven't tested yet."
    echo -e "  ${BOLD}B)${RESET} Apply permanently — only if you've ALREADY confirmed key login."
    echo ""
    echo -ne "${BOLD}Choose [A/b]: ${RESET}"
    local mode; read -r mode
    mode="${mode:-A}"

    if [[ "${mode,,}" == "b" ]]; then
        if ! confirm "Confirm: you have ALREADY logged in with your key in another session?"; then
            info "Aborted — nothing changed."; pause; return 0
        fi
        if _ssh_apply_hardening; then
            _ssh_cancel_autorevert
            success "Password authentication DISABLED. Root login is key-only now."
        else
            error "Hardening not applied (see above). Passwords remain enabled."
        fi
        pause; return 0
    fi

    # Mode A — dead-man safety timer
    echo -ne "${BOLD}Auto-restore passwords after how many minutes? [5]: ${RESET}"
    local mins; read -r mins
    mins="${mins:-5}"
    if ! [[ "$mins" =~ ^[0-9]+$ ]] || [[ "$mins" -lt 1 ]]; then mins=5; fi

    if ! confirm "Apply key-only login now with a ${mins}-minute safety timer?"; then
        info "Aborted — nothing changed."; pause; return 0
    fi

    if _ssh_apply_hardening; then
        _ssh_cancel_autorevert      # clear any previous timer
        _ssh_schedule_autorevert "$mins"
        echo ""
        success "Password login DISABLED with a ${mins}-minute safety timer."
        echo ""
        echo -e "${BOLD}Now, in another terminal:${RESET} ${DIM}ssh root@<server-ip> -p $port${RESET}"
        echo -e "  • If key login works  → return here and run ${BOLD}option 5${RESET} to make it permanent."
        echo -e "  • If you get locked out → do nothing; passwords auto-restore in ${mins} min."
    else
        error "Hardening not applied (see above). Passwords remain enabled."
    fi
    pause
}

# =============================================================================
# Commit — cancel the safety timer, keep key-only login
# =============================================================================
commit_hardening() {
    clear
    echo -e "${BOLD}${CYAN}  Make key-only login permanent${RESET}"
    echo ""
    if [[ "$(_ssh_effective passwordauthentication)" != "no" ]]; then
        warn "Password authentication is currently ENABLED — nothing to commit."
        warn "Run option 4 first to disable it."
        pause; return 0
    fi
    if _ssh_autorevert_active; then
        if confirm "Key login confirmed working — cancel the safety timer and keep key-only login?"; then
            _ssh_cancel_autorevert
            success "Safety timer cancelled. Key-only root login is now permanent."
        else
            info "Left the safety timer running."
        fi
    else
        info "No safety timer is running — key-only login is already permanent."
    fi
    pause
}

# =============================================================================
# Re-enable password login (rollback / break-glass)
# =============================================================================
enable_password_auth() {
    clear
    echo -e "${BOLD}${CYAN}  Re-enable password login (rollback)${RESET}"
    echo ""
    if ! confirm "Re-enable SSH password authentication for root?"; then
        info "Cancelled."; pause; return 0
    fi
    _ssh_cancel_autorevert
    if _ssh_revert_hardening; then
        success "Password authentication RE-ENABLED (toolkit hardening removed)."
        info "Distro defaults now apply. Your installed keys still work too."
    else
        error "Revert ran into a problem — check $SSHD_CONFIG and run 'sshd -t' manually."
    fi
    pause
}

# =============================================================================
# Status & audit
# =============================================================================
ssh_status() {
    clear
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${CYAN}  SSH status & audit${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""

    local port pw pubkey rootlogin
    port="$(_ssh_port)"
    pw="$(_ssh_effective passwordauthentication)"
    pubkey="$(_ssh_effective pubkeyauthentication)"
    rootlogin="$(_ssh_effective permitrootlogin)"

    printf "  ${BOLD}%-26s${RESET} %s\n" "SSH port:" "$port"
    printf "  ${BOLD}%-26s${RESET} %s\n" "PubkeyAuthentication:" "${pubkey:-unknown}"

    local pw_col="$pw"
    [[ "$pw" == "no"  ]] && pw_col="${GREEN}no  (key-only)${RESET}"
    [[ "$pw" == "yes" ]] && pw_col="${YELLOW}yes (passwords allowed)${RESET}"
    printf "  ${BOLD}%-26s${RESET} %b\n" "PasswordAuthentication:" "${pw_col:-unknown}"

    local rl_col="$rootlogin"
    [[ "$rootlogin" == "yes" ]] && rl_col="${YELLOW}yes${RESET}"
    [[ "$rootlogin" == "prohibit-password" ]] && rl_col="${GREEN}prohibit-password${RESET}"
    [[ "$rootlogin" == "no" ]] && rl_col="${RED}no (root SSH blocked)${RESET}"
    printf "  ${BOLD}%-26s${RESET} %b\n" "PermitRootLogin:" "${rl_col:-unknown}"

    local kcount=0
    [[ -s "$AUTH_KEYS" ]] && kcount="$(grep -cvE '^[[:space:]]*($|#)' "$AUTH_KEYS" 2>/dev/null || echo 0)"
    printf "  ${BOLD}%-26s${RESET} %s\n" "Authorized keys (root):" "$kcount"

    if _ssh_dropin_supported; then
        printf "  ${BOLD}%-26s${RESET} %s\n" "Config method:" "drop-in ($DROPIN_DIR)"
    else
        printf "  ${BOLD}%-26s${RESET} %s\n" "Config method:" "managed block in $SSHD_CONFIG"
    fi

    if _ssh_autorevert_active; then
        printf "  ${BOLD}%-26s${RESET} %b\n" "Safety timer:" "${YELLOW}ARMED — passwords will auto-restore; commit with option 5${RESET}"
    else
        printf "  ${BOLD}%-26s${RESET} %s\n" "Safety timer:" "none"
    fi

    # ── Firewall view for the SSH port ─────────────────────────────────────────
    echo ""
    echo -e "${BOLD}Firewall (SSH port $port):${RESET}"
    if command -v ufw &>/dev/null; then
        local ufw_stat; ufw_stat="$(ufw status 2>/dev/null | head -1 || echo unknown)"
        echo -e "  UFW: $ufw_stat"
        ufw status 2>/dev/null | grep -E "(^|[[:space:]])$port(/tcp)?[[:space:]]" \
            | sed 's/^/    /' || echo -e "    ${DIM}no explicit rule for port $port${RESET}"
    elif command -v iptables &>/dev/null; then
        iptables -L INPUT -n 2>/dev/null | grep -E "dpt:$port(\b|$)" \
            | sed 's/^/    /' || echo -e "    ${DIM}no iptables rule referencing port $port${RESET}"
    else
        echo -e "    ${DIM}neither ufw nor iptables found${RESET}"
    fi

    echo ""
    echo -e "  ${DIM}Recommendation: add a key (option 1), run Verify (option 3) until it${RESET}"
    echo -e "  ${DIM}reads READY, then disable passwords (option 4) with the safety timer.${RESET}"
    pause
}

# =============================================================================
# Main menu
# =============================================================================
show_menu() {
    clear
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${CYAN} 085)  SSH Key Hardening  ${DIM}(root login by key, not password)${RESET}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
    echo -e "${BOLD}  Keys${RESET}"
    echo -e "  ${GREEN}1${RESET})  Add a public key          ${DIM}paste · generate on server · fetch URL${RESET}"
    echo -e "  ${GREEN}2${RESET})  List installed keys       ${DIM}fingerprints in /root/.ssh/authorized_keys${RESET}"
    echo ""
    echo -e "${BOLD}  Hardening${RESET}"
    echo -e "  ${GREEN}3${RESET})  Verify key login          ${DIM}anti-lockout self-test (run this first!)${RESET}"
    echo -e "  ${YELLOW}4${RESET})  Disable password login    ${DIM}key-only; optional safety timer${RESET}"
    echo -e "  ${YELLOW}5${RESET})  Make key-only permanent   ${DIM}cancel safety timer after testing${RESET}"
    echo -e "  ${YELLOW}6${RESET})  Re-enable password login  ${DIM}rollback / break-glass${RESET}"
    echo ""
    echo -e "${BOLD}  Info${RESET}"
    echo -e "  ${CYAN}7${RESET})  SSH status & audit        ${DIM}effective config, keys, firewall${RESET}"
    echo ""
    echo -e "  ${DIM}0${RESET})  Return to admin menu"
    echo ""
    echo -e "${DIM}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -ne "${BOLD}Select [0-7]: ${RESET}"
}

main() {
    while true; do
        show_menu
        local choice; read -r choice
        case "$choice" in
            1) menu_add_key          || true ;;
            2) list_keys             || true ;;
            3) verify_key_login      || true ;;
            4) disable_password_auth || true ;;
            5) commit_hardening      || true ;;
            6) enable_password_auth  || true ;;
            7) ssh_status            || true ;;
            0) break ;;
            *) warn "Invalid option."; sleep 1 ;;
        esac
    done
}

main "$@"
